-- ============================================================
-- Auto-generated SQL import script from List.csv
-- Generated at: 2026-02-27 14:55:51
-- Statistics:
--   - Countries: 15
--   - Offices: 210
--   - Sales PICs: 1472
-- ============================================================

USE logitrack;
SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

-- ============================================================
-- Step 1: Insert country data
-- ============================================================
INSERT INTO country (country_code, country_name_en, country_name_cn, is_active, is_core) VALUES
  ('AG', 'AGENTS', 'Agents', 1, 0),
  ('BE', 'BELGIUM', 'Belgium', 1, 0),
  ('CH', 'SWITZERLAND', 'Switzerland', 1, 0),
  ('CN', 'CHINA', 'China', 1, 1),
  ('DE', 'GERMANY', 'Germany', 1, 1),
  ('FR', 'FRANCE', 'France', 1, 1),
  ('GB', 'United Kingdom', 'United Kingdom', 1, 1),
  ('GR', 'GREECE', 'Greece', 1, 0),
  ('MA', 'MOROCCO', 'Morocco', 1, 0),
  ('NL', 'NETHERLANDS', 'Netherlands', 1, 0),
  ('OT', 'OTHERS', 'Others', 1, 0),
  ('PL', 'POLAND', 'Poland', 1, 0),
  ('TB', 'TBA', 'TBA', 1, 0),
  ('US', 'USA', 'USA', 1, 1),
  ('ZA', 'SOUTH AFRICA', 'South Africa', 1, 0)
ON DUPLICATE KEY UPDATE
  country_name_en = VALUES(country_name_en),
  country_name_cn = VALUES(country_name_cn),
  updated_at = CURRENT_TIMESTAMP;

SELECT 'Inserted/updated 15 countries' AS status;

-- ============================================================
-- Step 2: Insert sales office data
-- ============================================================

INSERT INTO dict_sales_office (code, name, name_norm, country_code, is_active, sort_order) VALUES
  ('AG-AABITORT', 'AABITORT', 'AABITORT', 'AG', 1, 0),
  ('AG-AFS', 'AFS', 'AFS', 'AG', 1, 10),
  ('AG-AIRMAX', 'AIRMAX', 'AIRMAX', 'AG', 1, 20),
  ('AG-ALASRINTERNATIONAL', 'ALASR INTERNATIONAL', 'ALASR INTERNATIONAL', 'AG', 1, 30),
  ('AG-ALLIEDLOGISTICS', 'ALLIED LOGISTICS', 'ALLIED LOGISTICS', 'AG', 1, 40),
  ('AG-AMIGLOBALLOGISTICS', 'AMI GLOBAL LOGISTICS', 'AMI GLOBAL LOGISTICS', 'AG', 1, 50),
  ('AG-ANICAMCARGO', 'ANICAM CARGO', 'ANICAM CARGO', 'AG', 1, 60),
  ('AG-AREO', 'AREO', 'AREO', 'AG', 1, 70),
  ('AG-ATATTRANSPORTSOLUTIONS', 'ATAT TRANSPORT SOLUTIONS', 'ATAT TRANSPORT SOLUTIONS', 'AG', 1, 80),
  ('AG-AUSCORP', 'AUSCORP', 'AUSCORP', 'AG', 1, 90),
  ('AG-AVIATUR', 'AVIATUR', 'AVIATUR', 'AG', 1, 100),
  ('AG-BANWARI', 'BANWARI', 'BANWARI', 'AG', 1, 110),
  ('AG-BELGOBEARINGS', 'BELGO BEARINGS', 'BELGO BEARINGS', 'AG', 1, 120),
  ('AG-BENDIXTRANSPORT', 'BENDIX TRANSPORT', 'BENDIX TRANSPORT', 'AG', 1, 130),
  ('AG-BERELAX', 'BERELAX', 'BERELAX', 'AG', 1, 140),
  ('AG-BLUEPLANET', 'BLUE PLANET', 'BLUE PLANET', 'AG', 1, 150),
  ('AG-BRENDONINTERNATIONAL', 'BRENDON INTERNATIONAL', 'BRENDON INTERNATIONAL', 'AG', 1, 160),
  ('AG-BRUNINEXPRESS', 'BRUNIN EXPRESS', 'BRUNIN EXPRESS', 'AG', 1, 170),
  ('AG-CALGARYLOGISTICS', 'CALGARY LOGISTICS', 'CALGARY LOGISTICS', 'AG', 1, 180),
  ('AG-CARGOCARE', 'CARGO CARE', 'CARGO CARE', 'AG', 1, 190),
  ('AG-CARGOCORPLOGISTICS', 'CARGOCORP LOGISTICS', 'CARGOCORP LOGISTICS', 'AG', 1, 200),
  ('AG-CCR', 'CCR', 'CCR', 'AG', 1, 210),
  ('AG-CELERCO', 'CELERCO', 'CELERCO', 'AG', 1, 220),
  ('AG-CELERITY', 'CELERITY', 'CELERITY', 'AG', 1, 230),
  ('AG-CESAR', 'CESAR', 'CESAR', 'AG', 1, 240),
  ('AG-CFI', 'CFI', 'CFI', 'AG', 1, 250),
  ('AG-CLKWORLD', 'CLKWORLD', 'CLKWORLD', 'AG', 1, 260),
  ('AG-CMPILOGISTICS', 'CMPI LOGISTICS', 'CMPI LOGISTICS', 'AG', 1, 270),
  ('AG-CMSHIP', 'CMSHIP', 'CMSHIP', 'AG', 1, 280),
  ('AG-COMBINEDFREIGHTINTERNATIONAL', 'COMBINED FREIGHT INTERNATIONAL', 'COMBINED FREIGHT INTERNATIONAL', 'AG', 1, 290),
  ('AG-CRAYZHAO', 'CRAY ZHAO', 'CRAY ZHAO', 'AG', 1, 300),
  ('AG-CUSTOMERAGENCY', 'CUSTOMER AGENCY', 'CUSTOMER AGENCY', 'AG', 1, 310),
  ('AG-DACOTRANS', 'DACOTRANS', 'DACOTRANS', 'AG', 1, 320),
  ('AG-DCSDAHSTARLOGISTICSCOLTD', 'DCS DAH STAR LOGISTICS CO.,LTD', 'DCS DAH STAR LOGISTICS CO.,LTD', 'AG', 1, 330),
  ('AG-DEGOGLOBAL', 'DEGO GLOBAL', 'DEGO GLOBAL', 'AG', 1, 340),
  ('AG-DESERTHORIZON', 'DESERT HORIZON', 'DESERT HORIZON', 'AG', 1, 350),
  ('AG-DUPORT', 'DUPORT', 'DUPORT', 'AG', 1, 360),
  ('AG-DYNASTYSHIPPING', 'DYNASTY SHIPPING', 'DYNASTY SHIPPING', 'AG', 1, 370),
  ('AG-ELOG', 'ELOG', 'ELOG', 'AG', 1, 380),
  ('AG-ELOGBOLIVIA', 'ELOG BOLIVIA', 'ELOG BOLIVIA', 'AG', 1, 390),
  ('AG-ELOTRANS', 'ELOTRANS', 'ELOTRANS', 'AG', 1, 400),
  ('AG-ENGERGYGLOALLOGSITICS', 'ENGERGY GLOAL LOGSITICS', 'ENGERGY GLOAL LOGSITICS', 'AG', 1, 410),
  ('AG-ESSERS', 'ESSERS', 'ESSERS', 'AG', 1, 420),
  ('AG-EUROATLA', 'EUROATLA', 'EUROATLA', 'AG', 1, 430),
  ('AG-EXCELFREIGHTSYSTEMS', 'EXCEL FREIGHT SYSTEMS', 'EXCEL FREIGHT SYSTEMS', 'AG', 1, 440),
  ('AG-FALCONSHIPPINGLOGISTICS', 'FALCON SHIPPING & LOGISTICS', 'FALCON SHIPPING & LOGISTICS', 'AG', 1, 450),
  ('AG-FFLOGISTIK', 'FF LOGISTIK', 'FF LOGISTIK', 'AG', 1, 460),
  ('AG-FIBSLOGISTICS', 'FIBS LOGISTICS', 'FIBS LOGISTICS', 'AG', 1, 470),
  ('AG-FIGWAL', 'FIGWAL', 'FIGWAL', 'AG', 1, 480),
  ('AG-FLYINGSHRIMPGROUP', 'FLYING SHRIMP GROUP', 'FLYING SHRIMP GROUP', 'AG', 1, 490),
  ('AG-FORWARDAIRLTD', 'FORWARDAIR LTD', 'FORWARDAIR LTD', 'AG', 1, 500),
  ('AG-FREIGHTSOLUTIONS', 'FREIGHT SOLUTIONS', 'FREIGHT SOLUTIONS', 'AG', 1, 510),
  ('AG-FREIGHTLINKS', 'FREIGHTLINKS', 'FREIGHTLINKS', 'AG', 1, 520),
  ('AG-FREIGHTWAYSGLOBALSOLUTIONS', 'FREIGHTWAYS GLOBAL SOLUTIONS', 'FREIGHTWAYS GLOBAL SOLUTIONS', 'AG', 1, 530),
  ('AG-FRIDENSON', 'FRIDENSON', 'FRIDENSON', 'AG', 1, 540),
  ('AG-GALPER', 'GALPER', 'GALPER', 'AG', 1, 550),
  ('AG-GAMECHANGE', 'GAME CHANGE', 'GAME CHANGE', 'AG', 1, 560),
  ('AG-GENERALMERCHANDISECONSOLIDATORS', 'GENERAL MERCHANDISE CONSOLIDATORS', 'GENERAL MERCHANDISE CONSOLIDATORS', 'AG', 1, 570),
  ('AG-GEXLOGISTICS', 'GEX LOGISTICS', 'GEX LOGISTICS', 'AG', 1, 580),
  ('AG-GEZAIRITRANSPORT', 'GEZAIRI TRANSPORT', 'GEZAIRI TRANSPORT', 'AG', 1, 590),
  ('AG-GHABZE', 'GHABZE', 'GHABZE', 'AG', 1, 600),
  ('AG-GIMEX', 'GIMEX', 'GIMEX', 'AG', 1, 610),
  ('AG-GLOBALFREIGHTSYSTEMSCO', 'GLOBAL FREIGHT SYSTEMS CO', 'GLOBAL FREIGHT SYSTEMS CO', 'AG', 1, 620),
  ('AG-GLOBALHELLENIC', 'GLOBAL HELLENIC', 'GLOBAL HELLENIC', 'AG', 1, 630),
  ('AG-GLOBALLOGISTICS', 'GLOBAL LOGISTICS', 'GLOBAL LOGISTICS', 'AG', 1, 640),
  ('AG-GMCTXG', 'GMC TXG', 'GMC TXG', 'AG', 1, 650),
  ('AG-GOLDENDRAGON', 'GOLDEN DRAGON', 'GOLDEN DRAGON', 'AG', 1, 660),
  ('AG-GOLDLOGBRAZIL', 'GOLDLOG BRAZIL', 'GOLDLOG BRAZIL', 'AG', 1, 670),
  ('AG-GORGONISRL', 'GORGONI SRL', 'GORGONI SRL', 'AG', 1, 680),
  ('AG-GSM', 'GSM', 'GSM', 'AG', 1, 690),
  ('AG-GUANGZHOUMINTONGTRADING', 'GUANGZHOU MINTONG TRADING', 'GUANGZHOU MINTONG TRADING', 'AG', 1, 700),
  ('AG-GULFAGENCYCOMPANY', 'GULF AGENCY COMPANY', 'GULF AGENCY COMPANY', 'AG', 1, 710),
  ('AG-GUNTERMEDICALGMBH', 'GUNTER MEDICAL GMBH', 'GUNTER MEDICAL GMBH', 'AG', 1, 720),
  ('AG-GWL', 'GWL', 'GWL', 'AG', 1, 730),
  ('AG-HARFORDMETALWARELTD', 'HARFORD METALWARE LTD.', 'HARFORD METALWARE LTD.', 'AG', 1, 740),
  ('AG-HKFLYINGSHRIMP', 'HK FLYING SHRIMP', 'HK FLYING SHRIMP', 'AG', 1, 750),
  ('AG-HKFLYINGSHRIMPGROUP', 'HK FLYING SHRIMP GROUP', 'HK FLYING SHRIMP GROUP', 'AG', 1, 760),
  ('AG-HOMEBESTINTERNATIONAL', 'HOME BEST INTERNATIONAL', 'HOME BEST INTERNATIONAL', 'AG', 1, 770),
  ('AG-HTLLOGISTICS', 'HTL LOGISTICS', 'HTL LOGISTICS', 'AG', 1, 780),
  ('AG-INCOTRANS', 'INCOTRANS', 'INCOTRANS', 'AG', 1, 790),
  ('AG-INDEPENDENTTRANSPORTSHIPPING', 'INDEPENDENT TRANSPORT SHIPPING', 'INDEPENDENT TRANSPORT SHIPPING', 'AG', 1, 800),
  ('AG-INTERBORDERS', 'INTERBORDERS', 'INTERBORDERS', 'AG', 1, 810),
  ('AG-INTERGLOBALCARGO', 'INTERGLOBAL CARGO', 'INTERGLOBAL CARGO', 'AG', 1, 820),
  ('AG-ISOX', 'ISOX', 'ISOX', 'AG', 1, 830),
  ('AG-KERRYLOGISTICSBAHRAIN', 'KERRY LOGISTICS BAHRAIN', 'KERRY LOGISTICS BAHRAIN', 'AG', 1, 840),
  ('AG-KEYSTONETRADING', 'KEYSTONE TRADING', 'KEYSTONE TRADING', 'AG', 1, 850),
  ('AG-KINIFISOLOPRIMO', 'KINIFI SOLOPRIMO', 'KINIFI SOLOPRIMO', 'AG', 1, 860),
  ('AG-KLM', 'KLM', 'KLM', 'AG', 1, 870),
  ('AG-KONNECTSHIPPING', 'KONNECT SHIPPING', 'KONNECT SHIPPING', 'AG', 1, 880),
  ('AG-LAMWORLD', 'LAM WORLD', 'LAM WORLD', 'AG', 1, 890),
  ('AG-LEMAN', 'LEMAN', 'LEMAN', 'AG', 1, 900),
  ('AG-LEXULUSLARARASI', 'LEX ULUSLARARASI', 'LEX ULUSLARARASI', 'AG', 1, 910),
  ('AG-LOGENIXLOGISTICS', 'LOGENIX LOGISTICS', 'LOGENIX LOGISTICS', 'AG', 1, 920),
  ('AG-LOGISTICSPLUS', 'LOGISTICS PLUS', 'LOGISTICS PLUS', 'AG', 1, 930),
  ('AG-LOGISTICSSERVICESPAKISTAN', 'LOGISTICS SERVICES PAKISTAN', 'LOGISTICS SERVICES PAKISTAN', 'AG', 1, 940),
  ('AG-LOGIWORKS', 'LOGIWORKS', 'LOGIWORKS', 'AG', 1, 950),
  ('AG-LUSTERSHIPPING', 'LUSTER SHIPPING', 'LUSTER SHIPPING', 'AG', 1, 960),
  ('AG-LXCGLOBALLOGISTICS', 'LXC GLOBAL LOGISTICS', 'LXC GLOBAL LOGISTICS', 'AG', 1, 970),
  ('AG-MAINSTREAMSHIPPING', 'MAINSTREAM SHIPPING', 'MAINSTREAM SHIPPING', 'AG', 1, 980),
  ('AG-MARIAASIA', 'MARIA ASIA', 'MARIA ASIA', 'AG', 1, 990),
  ('AG-MASTERLINEGROUP', 'MASTERLINE GROUP', 'MASTERLINE GROUP', 'AG', 1, 1000),
  ('AG-MCTC', 'MCTC', 'MCTC', 'AG', 1, 1010),
  ('AG-MENILLOGISTICS', 'MENIL LOGISTICS', 'MENIL LOGISTICS', 'AG', 1, 1020),
  ('AG-MFS', 'MFS', 'MFS', 'AG', 1, 1030),
  ('AG-MII', 'MII', 'MII', 'AG', 1, 1040),
  ('AG-MODA', 'MODA', 'MODA', 'AG', 1, 1050),
  ('AG-MODAVITTA', 'MODA VITTA', 'MODA VITTA', 'AG', 1, 1060),
  ('AG-MULTIMODELFREIGHTSOLUTIONS', 'MULTI MODEL FREIGHT SOLUTIONS', 'MULTI MODEL FREIGHT SOLUTIONS', 'AG', 1, 1070),
  ('AG-NEARNORTHCUSTOMS', 'NEAR NORTH CUSTOMS', 'NEAR NORTH CUSTOMS', 'AG', 1, 1080),
  ('AG-NENACOMEXLOGISTICS', 'NENACOMEX LOGISTICS', 'NENACOMEX LOGISTICS', 'AG', 1, 1090),
  ('AG-OCEANLINK', 'OCEAN LINK', 'OCEAN LINK', 'AG', 1, 1100),
  ('AG-ONTIME', 'ON TIME', 'ON TIME', 'AG', 1, 1110),
  ('AG-ONWARD', 'ONWARD', 'ONWARD', 'AG', 1, 1120),
  ('AG-OSHAIGER', 'OSHAIGER', 'OSHAIGER', 'AG', 1, 1130),
  ('AG-PACIFICANCHORLINE', 'PACIFIC ANCHOR LINE', 'PACIFIC ANCHOR LINE', 'AG', 1, 1140),
  ('AG-PACIFICOCEAN', 'PACIFIC OCEAN', 'PACIFIC OCEAN', 'AG', 1, 1150),
  ('AG-PAKISTANCARGOSERVICE', 'PAKISTAN CARGO SERVICE', 'PAKISTAN CARGO SERVICE', 'AG', 1, 1160),
  ('AG-PALLOGISTICS', 'PAL LOGISTICS', 'PAL LOGISTICS', 'AG', 1, 1170),
  ('AG-PANINDIACHRISTA', 'PAN INDIA/CHRISTA', 'PAN INDIA/CHRISTA', 'AG', 1, 1180),
  ('AG-PARC', 'PARC', 'PARC', 'AG', 1, 1190),
  ('AG-PCS', 'PCS', 'PCS', 'AG', 1, 1200),
  ('AG-PHILIORIENT', 'PHILI ORIENT', 'PHILI ORIENT', 'AG', 1, 1210),
  ('AG-PLASCOWLOGISTICSLTD', 'PLASCOW LOGISTICS LTD', 'PLASCOW LOGISTICS LTD', 'AG', 1, 1220),
  ('AG-PREMIUMPARTNERS', 'PREMIUM-PARTNERS', 'PREMIUM-PARTNERS', 'AG', 1, 1230),
  ('AG-PTFIDO', 'PT FIDO', 'PT FIDO', 'AG', 1, 1240),
  ('AG-PTSILKARGOINDONESIA', 'PT SILKARGO INDONESIA', 'PT SILKARGO INDONESIA', 'AG', 1, 1250),
  ('AG-PTMILITZERANDMUENCHINDONESIA', 'PT. MILITZER AND MUENCH INDONESIA', 'PT. MILITZER AND MUENCH INDONESIA', 'AG', 1, 1260),
  ('AG-PTSENATOR', 'PT. SENATOR', 'PT. SENATOR', 'AG', 1, 1270),
  ('AG-QUALITY', 'QUALITY', 'QUALITY', 'AG', 1, 1280),
  ('AG-RACHAELMARTHAATOO', 'RACHAEL MARTHA ATOO', 'RACHAEL MARTHA ATOO', 'AG', 1, 1290),
  ('AG-RAINBOWSPRING', 'RAINBOW SPRING', 'RAINBOW SPRING', 'AG', 1, 1300),
  ('AG-RAVIANINTERNATIONAL', 'RAVIAN INTERNATIONAL', 'RAVIAN INTERNATIONAL', 'AG', 1, 1310),
  ('AG-REXCARGO', 'REXCARGO', 'REXCARGO', 'AG', 1, 1320),
  ('AG-SAMMANTRANS', 'SAMMAN TRANS', 'SAMMAN TRANS', 'AG', 1, 1330),
  ('AG-SAMUDERA', 'SAMUDERA', 'SAMUDERA', 'AG', 1, 1340),
  ('AG-SBLOGISTICS', 'SB LOGISTICS', 'SB LOGISTICS', 'AG', 1, 1350),
  ('AG-SEGURO', 'SEGURO', 'SEGURO', 'AG', 1, 1360),
  ('AG-SES', 'SES', 'SES', 'AG', 1, 1370),
  ('AG-SF', 'SF', 'SF', 'AG', 1, 1380),
  ('AG-SHIFTCO', 'SHIFTCO', 'SHIFTCO', 'AG', 1, 1390),
  ('AG-SHPR', 'SHPR', 'SHPR', 'AG', 1, 1400),
  ('AG-SINDBAD', 'SINDBAD', 'SINDBAD', 'AG', 1, 1410),
  ('AG-SINDBADGROUPE', 'SINDBAD GROUPE', 'SINDBAD GROUPE', 'AG', 1, 1420),
  ('AG-SPEEDCARGO', 'SPEED CARGO', 'SPEED CARGO', 'AG', 1, 1430),
  ('AG-SPEEDFREIGHT', 'SPEEDFREIGHT', 'SPEEDFREIGHT', 'AG', 1, 1440),
  ('AG-SUNGGONGLOGISTICS', 'SUNGGONG LOGISTICS', 'SUNGGONG LOGISTICS', 'AG', 1, 1450),
  ('AG-SUREFREIGHTINTERNATIONAL', 'SUREFREIGHT INTERNATIONAL', 'SUREFREIGHT INTERNATIONAL', 'AG', 1, 1460),
  ('AG-TALOS', 'TALOS', 'TALOS', 'AG', 1, 1470),
  ('AG-TAMANHTRADING', 'TAM ANH TRADING', 'TAM ANH TRADING', 'AG', 1, 1480),
  ('AG-TEAMFREIGHTMANAGEMENT', 'TEAM FREIGHT MANAGEMENT', 'TEAM FREIGHT MANAGEMENT', 'AG', 1, 1490),
  ('AG-TIFFANYCARGOSYSTEM', 'TIFFANY CARGO SYSTEM', 'TIFFANY CARGO SYSTEM', 'AG', 1, 1500),
  ('AG-TRACOSA', 'TRACOSA', 'TRACOSA', 'AG', 1, 1510),
  ('AG-TRANSMERIDIAN', 'TRANSMERIDIAN', 'TRANSMERIDIAN', 'AG', 1, 1520),
  ('AG-UCI', 'UCI', 'UCI', 'AG', 1, 1530),
  ('AG-UNIVERSALBRIDGELOGISTICS', 'UNIVERSAL BRIDGE LOGISTICS', 'UNIVERSAL BRIDGE LOGISTICS', 'AG', 1, 1540),
  ('AG-UTCMEDITERRANEANSRLU', 'UTC MEDITERRANEAN SRLU', 'UTC MEDITERRANEAN SRLU', 'AG', 1, 1550),
  ('AG-VANLOGISTICSBGD', 'VAN LOGISTICS BGD', 'VAN LOGISTICS BGD', 'AG', 1, 1560),
  ('AG-VELOCITYSHIPPINGPVT', 'VELOCITY SHIPPING (PVT)', 'VELOCITY SHIPPING (PVT)', 'AG', 1, 1570),
  ('AG-VIECOM', 'VIECOM', 'VIECOM', 'AG', 1, 1580),
  ('AG-VINALINK', 'VINALINK', 'VINALINK', 'AG', 1, 1590),
  ('AG-VRRDHI', 'VRRDHI', 'VRRDHI', 'AG', 1, 1600),
  ('AG-WESTCOASTAVIATION', 'WEST COAST AVIATION', 'WEST COAST AVIATION', 'AG', 1, 1610),
  ('AG-WIDELOGISTICS', 'WIDE LOGISTICS', 'WIDE LOGISTICS', 'AG', 1, 1620),
  ('AG-WIDEAL', 'WIDEAL', 'WIDEAL', 'AG', 1, 1630),
  ('AG-WORLDFAMOUS', 'WORLD FAMOUS', 'WORLD FAMOUS', 'AG', 1, 1640),
  ('AG-WUXIJIAHUAINTERNATIONALFREIGHT', 'WUXI JIAHUA INTERNATIONAL FREIGHT', 'WUXI JIAHUA INTERNATIONAL FREIGHT', 'AG', 1, 1650),
  ('AG-WUXIJIAYIINTERNATIONAL', 'WUXI JIAYI INTERNATIONAL', 'WUXI JIAYI INTERNATIONAL', 'AG', 1, 1660),
  ('AG-ZUSTAMBROSETTI', 'ZUST AMBROSETTI', 'ZUST AMBROSETTI', 'AG', 1, 1670),
  ('BE-ZIEGLERBELGIUM', 'ZIEGLER BELGIUM', 'ZIEGLER BELGIUM', 'BE', 1, 1680),
  ('CH-ZIEGLERSWITZERLAND', 'ZIEGLER SWITZERLAND', 'ZIEGLER SWITZERLAND', 'CH', 1, 1690),
  ('CN-ZIEGLERHONGKONG', 'ZIEGLER HONG KONG', 'ZIEGLER HONG KONG', 'CN', 1, 1700),
  ('CN-ZIEGLERNINGBO', 'ZIEGLER NINGBO', 'ZIEGLER NINGBO', 'CN', 1, 1710),
  ('CN-ZIEGLERQINGDAO', 'ZIEGLER QINGDAO', 'ZIEGLER QINGDAO', 'CN', 1, 1720),
  ('CN-ZIEGLERSHANGHAI', 'ZIEGLER SHANGHAI', 'ZIEGLER SHANGHAI', 'CN', 1, 1730),
  ('CN-ZIEGLERSHENZHEN', 'ZIEGLER SHENZHEN', 'ZIEGLER SHENZHEN', 'CN', 1, 1740),
  ('CN-ZIEGLERTIANJIN', 'ZIEGLER TIANJIN', 'ZIEGLER TIANJIN', 'CN', 1, 1750),
  ('CN-ZIEGLERXIAMEN', 'ZIEGLER XIAMEN', 'ZIEGLER XIAMEN', 'CN', 1, 1760),
  ('DE-ZIEGLERGERMANY', 'ZIEGLER GERMANY', 'ZIEGLER GERMANY', 'DE', 1, 1770),
  ('FR-ZIEGLERFRANCE', 'ZIEGLER FRANCE', 'ZIEGLER FRANCE', 'FR', 1, 1780),
  ('GB-ZIEGLERBIRMINGHAM', 'ZIEGLER BIRMINGHAM', 'ZIEGLER BIRMINGHAM', 'GB', 1, 1790),
  ('GB-ZIEGLERBRADFORD', 'ZIEGLER BRADFORD', 'ZIEGLER BRADFORD', 'GB', 1, 1800),
  ('GB-ZIEGLERBRISTOL', 'ZIEGLER BRISTOL', 'ZIEGLER BRISTOL', 'GB', 1, 1810),
  ('GB-ZIEGLERCOLNBROOK', 'ZIEGLER COLNBROOK', 'ZIEGLER COLNBROOK', 'GB', 1, 1820),
  ('GB-ZIEGLERDURHAM', 'ZIEGLER DURHAM', 'ZIEGLER DURHAM', 'GB', 1, 1830),
  ('GB-ZIEGLERFELIXSTOWE', 'ZIEGLER FELIXSTOWE', 'ZIEGLER FELIXSTOWE', 'GB', 1, 1840),
  ('GB-ZIEGLERHEATHROW', 'ZIEGLER HEATHROW', 'ZIEGLER HEATHROW', 'GB', 1, 1850),
  ('GB-ZIEGLERMANCHESTER', 'ZIEGLER MANCHESTER', 'ZIEGLER MANCHESTER', 'GB', 1, 1860),
  ('GB-ZIEGLERNEWPORT', 'ZIEGLER NEWPORT', 'ZIEGLER NEWPORT', 'GB', 1, 1870),
  ('GB-ZIEGLERNORTHAMPTON', 'ZIEGLER NORTHAMPTON', 'ZIEGLER NORTHAMPTON', 'GB', 1, 1880),
  ('GB-ZIEGLERPORTSMOUTH', 'ZIEGLER PORTSMOUTH', 'ZIEGLER PORTSMOUTH', 'GB', 1, 1890),
  ('GB-ZIEGLERWARRINGTON', 'ZIEGLER WARRINGTON', 'ZIEGLER WARRINGTON', 'GB', 1, 1900),
  ('GR-ZIEGLERGREECE', 'ZIEGLER GREECE', 'ZIEGLER GREECE', 'GR', 1, 1910),
  ('MA-ZIEGLERMOROCCO', 'ZIEGLER MOROCCO', 'ZIEGLER MOROCCO', 'MA', 1, 1920),
  ('NL-ZIEGLERNETHERLANDS', 'ZIEGLER NETHERLANDS', 'ZIEGLER NETHERLANDS', 'NL', 1, 1930),
  ('OT-AMARIMETALSCHINA', 'AMARI METALS CHINA', 'AMARI METALS CHINA', 'OT', 1, 1940),
  ('OT-ATLANTICALCHKLIMITED', 'ATLANTIC ALC (HK) LIMITED', 'ATLANTIC ALC (HK) LIMITED', 'OT', 1, 1950),
  ('OT-EC4ULIMITED', 'EC4U LIMITED', 'EC4U LIMITED', 'OT', 1, 1960),
  ('OT-GRUPOVSANTOS', 'GRUPO V.SANTOS', 'GRUPO V.SANTOS', 'OT', 1, 1970),
  ('OT-GUANGHZOUSOURCING', 'GUANGHZOU SOURCING', 'GUANGHZOU SOURCING', 'OT', 1, 1980),
  ('OT-HONGKONGHOYOGO', 'HONG KONG HOYOGO', 'HONG KONG HOYOGO', 'OT', 1, 1990),
  ('OT-JABEZFURNITURE', 'JABEZ FURNITURE', 'JABEZ FURNITURE', 'OT', 1, 2000),
  ('OT-SHANDONGJULIALUMINIUM', 'SHANDONG JULI ALUMINIUM', 'SHANDONG JULI ALUMINIUM', 'OT', 1, 2010),
  ('OT-TAMANHTRADING', 'TAM ANH TRADING', 'TAM ANH TRADING', 'OT', 1, 2020),
  ('OT-TREMAIL', 'TREMAIL', 'TREMAIL', 'OT', 1, 2030),
  ('PL-ZIEGLERPOLAND', 'ZIEGLER POLAND', 'ZIEGLER POLAND', 'PL', 1, 2040),
  ('TB-TBA', 'TBA', 'TBA', 'TB', 1, 2050),
  ('US-ZIEGLERUSA', 'ZIEGLER USA', 'ZIEGLER USA', 'US', 1, 2060),
  ('ZA-', '-', '-', 'ZA', 1, 2070),
  ('ZA-ZIEGLERCAPETOWN', 'ZIEGLER CAPETOWN', 'ZIEGLER CAPETOWN', 'ZA', 1, 2080),
  ('ZA-ZIEGLERJOHANNESBURG', 'ZIEGLER JOHANNESBURG', 'ZIEGLER JOHANNESBURG', 'ZA', 1, 2090)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  name_norm = VALUES(name_norm),
  country_code = VALUES(country_code),
  updated_at = CURRENT_TIMESTAMP;

SELECT 'Inserted/updated 210 sales offices' AS status;

-- ============================================================
-- Step 3: Insert sales PIC data (deduplicated)
-- ============================================================

INSERT INTO sales_pic (name, name_norm, country_code, sales_office_id, is_active)
SELECT
  pic_data.name,
  pic_data.name_norm,
  pic_data.country_code,
  so.id AS sales_office_id,
  1 AS is_active
FROM (
  SELECT 'RAJ KUMAR' AS name, 'RAJ KUMAR' AS name_norm, 'AG' AS country_code, 'AG-AABITORT' AS office_code
  UNION ALL SELECT 'MELANIE CASTILLO', 'MELANIE CASTILLO', 'AG', 'AG-AFS'
  UNION ALL SELECT 'GERGELY BARANYAI', 'GERGELY BARANYAI', 'AG', 'AG-AIRMAX'
  UNION ALL SELECT 'SHAHEBAZ KHAN', 'SHAHEBAZ KHAN', 'AG', 'AG-ALASRINTERNATIONAL'
  UNION ALL SELECT 'LAIBA ARSHAD ALI', 'LAIBA ARSHAD ALI', 'AG', 'AG-ALLIEDLOGISTICS'
  UNION ALL SELECT 'KARUNA BHATE', 'KARUNA BHATE', 'AG', 'AG-AMIGLOBALLOGISTICS'
  UNION ALL SELECT 'MAYUR', 'MAYUR', 'AG', 'AG-AMIGLOBALLOGISTICS'
  UNION ALL SELECT 'RUPALI DESHMUKH', 'RUPALI DESHMUKH', 'AG', 'AG-AMIGLOBALLOGISTICS'
  UNION ALL SELECT 'SERGIO BUSTAMANTE', 'SERGIO BUSTAMANTE', 'AG', 'AG-ANICAMCARGO'
  UNION ALL SELECT 'RAY LIU', 'RAY LIU', 'AG', 'AG-AREO'
  UNION ALL SELECT 'BURCU DÜZDAŞ', 'BURCU DÜZDAŞ', 'AG', 'AG-ATATTRANSPORTSOLUTIONS'
  UNION ALL SELECT 'EMIR SOYSAL', 'EMIR SOYSAL', 'AG', 'AG-ATATTRANSPORTSOLUTIONS'
  UNION ALL SELECT 'ANA JULIA PRADO', 'ANA JULIA PRADO', 'AG', 'AG-AUSCORP'
  UNION ALL SELECT 'LUISA FERNANDA SUAREZ CASALLAS', 'LUISA FERNANDA SUAREZ CASALLAS', 'AG', 'AG-AVIATUR'
  UNION ALL SELECT 'PRAVIN JAISWAR', 'PRAVIN JAISWAR', 'AG', 'AG-BANWARI'
  UNION ALL SELECT 'SINAN SENER', 'SINAN SENER', 'AG', 'AG-BELGOBEARINGS'
  UNION ALL SELECT 'DINO SKRIJELJ', 'DINO SKRIJELJ', 'AG', 'AG-BENDIXTRANSPORT'
  UNION ALL SELECT 'CARLA GREJALVO', 'CARLA GREJALVO', 'AG', 'AG-BERELAX'
  UNION ALL SELECT 'GISSELLE OCOT', 'GISSELLE OCOT', 'AG', 'AG-BERELAX'
  UNION ALL SELECT 'KEN ZHANG', 'KEN ZHANG', 'AG', 'AG-BERELAX'
  UNION ALL SELECT 'GAYLIN FERRIER', 'GAYLIN FERRIER', 'AG', 'AG-BLUEPLANET'
  UNION ALL SELECT 'BAN NGUYEN', 'BAN NGUYEN', 'AG', 'AG-BRENDONINTERNATIONAL'
  UNION ALL SELECT 'JOE CHAN', 'JOE CHAN', 'AG', 'AG-BRENDONINTERNATIONAL'
  UNION ALL SELECT 'LAURA SCULL', 'LAURA SCULL', 'AG', 'AG-BRENDONINTERNATIONAL'
  UNION ALL SELECT 'NICOLA SCULL', 'NICOLA SCULL', 'AG', 'AG-BRENDONINTERNATIONAL'
  UNION ALL SELECT 'RACHAEL PLUMB', 'RACHAEL PLUMB', 'AG', 'AG-BRENDONINTERNATIONAL'
  UNION ALL SELECT 'VAN NGUYEN', 'VAN NGUYEN', 'AG', 'AG-BRENDONINTERNATIONAL'
  UNION ALL SELECT 'VAN THANH NGUYEN', 'VAN THANH NGUYEN', 'AG', 'AG-BRENDONINTERNATIONAL'
  UNION ALL SELECT 'GIOVANNI PIMENTEL', 'GIOVANNI PIMENTEL', 'AG', 'AG-BRUNINEXPRESS'
  UNION ALL SELECT 'VINÍCIUS BLAU', 'VINÍCIUS BLAU', 'AG', 'AG-BRUNINEXPRESS'
  UNION ALL SELECT 'GIGI LIU', 'GIGI LIU', 'AG', 'AG-CALGARYLOGISTICS'
  UNION ALL SELECT 'DAN ULEIA', 'DAN ULEIA', 'AG', 'AG-CARGOCARE'
  UNION ALL SELECT 'LESLIE ESPINOZA', 'LESLIE ESPINOZA', 'AG', 'AG-CARGOCORPLOGISTICS'
  UNION ALL SELECT 'FERNANDO ARMIJO', 'FERNANDO ARMIJO', 'AG', 'AG-CCR'
  UNION ALL SELECT 'ANDREEA APOSTOL', 'ANDREEA APOSTOL', 'AG', 'AG-CELERCO'
  UNION ALL SELECT 'COSTI COSTACHE', 'COSTI COSTACHE', 'AG', 'AG-CELERCO'
  UNION ALL SELECT 'NAEEM UDDIN', 'NAEEM UDDIN', 'AG', 'AG-CELERITY'
  UNION ALL SELECT 'RAMEEZ SARWAR', 'RAMEEZ SARWAR', 'AG', 'AG-CELERITY'
  UNION ALL SELECT 'SARFRAZ AHMAD', 'SARFRAZ AHMAD', 'AG', 'AG-CELERITY'
  UNION ALL SELECT 'AYETCHO', 'AYETCHO', 'AG', 'AG-CESAR'
  UNION ALL SELECT 'AHMED', 'AHMED', 'AG', 'AG-CFI'
  UNION ALL SELECT 'SERAP KARAHUN UZUN', 'SERAP KARAHUN UZUN', 'AG', 'AG-CLKWORLD'
  UNION ALL SELECT 'XUKA', 'XUKA', 'AG', 'AG-CMPILOGISTICS'
  UNION ALL SELECT 'CRISTIAN MASSARA', 'CRISTIAN MASSARA', 'AG', 'AG-CMSHIP'
  UNION ALL SELECT 'MOHAMMAD AHMED SHEIKH', 'MOHAMMAD AHMED SHEIKH', 'AG', 'AG-COMBINEDFREIGHTINTERNATIONAL'
  UNION ALL SELECT 'CHUNGTAI', 'CHUNGTAI', 'AG', 'AG-CRAYZHAO'
  UNION ALL SELECT 'ADRIANA CASALLAS PENA', 'ADRIANA CASALLAS PENA', 'AG', 'AG-CUSTOMERAGENCY'
  UNION ALL SELECT 'CHRISTINE KNUTH', 'CHRISTINE KNUTH', 'AG', 'AG-DACOTRANS'
  UNION ALL SELECT 'FANNY HUANG', 'FANNY HUANG', 'AG', 'AG-DCSDAHSTARLOGISTICSCOLTD'
  UNION ALL SELECT 'JENNY DONG', 'JENNY DONG', 'AG', 'AG-DEGOGLOBAL'
  UNION ALL SELECT 'MAXIM EVTUSHENKO', 'MAXIM EVTUSHENKO', 'AG', 'AG-DESERTHORIZON'
  UNION ALL SELECT 'MIRANDA', 'MIRANDA', 'AG', 'AG-DUPORT'
  UNION ALL SELECT 'HINSON', 'HINSON', 'AG', 'AG-DYNASTYSHIPPING'
  UNION ALL SELECT 'CESAR MOLINA', 'CESAR MOLINA', 'AG', 'AG-ELOGBOLIVIA'
  UNION ALL SELECT 'DANIELA CARVAJAL', 'DANIELA CARVAJAL', 'AG', 'AG-ELOG'
  UNION ALL SELECT 'EDUARDO MALDONADO', 'EDUARDO MALDONADO', 'AG', 'AG-ELOG'
  UNION ALL SELECT 'GEOVANA MOLLINEDO', 'GEOVANA MOLLINEDO', 'AG', 'AG-ELOG'
  UNION ALL SELECT 'KATHERINE ANDRADE', 'KATHERINE ANDRADE', 'AG', 'AG-ELOG'
  UNION ALL SELECT 'JEFFERSON JANZEN', 'JEFFERSON JANZEN', 'AG', 'AG-ELOTRANS'
  UNION ALL SELECT 'MARKK CUCEK', 'MARKK CUCEK', 'AG', 'AG-ENGERGYGLOALLOGSITICS'
  UNION ALL SELECT 'EVA FERRER', 'EVA FERRER', 'AG', 'AG-ESSERS'
  UNION ALL SELECT 'MÓNICA ROLDÃO', 'MÓNICA ROLDÃO', 'AG', 'AG-EUROATLA'
  UNION ALL SELECT 'SYED WASI IMRAN', 'SYED WASI IMRAN', 'AG', 'AG-EXCELFREIGHTSYSTEMS'
  UNION ALL SELECT 'PINTU DATTA', 'PINTU DATTA', 'AG', 'AG-FALCONSHIPPINGLOGISTICS'
  UNION ALL SELECT 'PULAK DATTA', 'PULAK DATTA', 'AG', 'AG-FALCONSHIPPINGLOGISTICS'
  UNION ALL SELECT 'RENNY', 'RENNY', 'AG', 'AG-FFLOGISTIK'
  UNION ALL SELECT 'SONYA THELMA', 'SONYA THELMA', 'AG', 'AG-FFLOGISTIK'
  UNION ALL SELECT 'AAZMA SIDDIQUI', 'AAZMA SIDDIQUI', 'AG', 'AG-FIBSLOGISTICS'
  UNION ALL SELECT 'ANDRE ALMEIDA', 'ANDRE ALMEIDA', 'AG', 'AG-FIGWAL'
  UNION ALL SELECT 'CLANAIR GURGEL', 'CLANAIR GURGEL', 'AG', 'AG-FIGWAL'
  UNION ALL SELECT 'DAVID MAIA', 'DAVID MAIA', 'AG', 'AG-FIGWAL'
  UNION ALL SELECT 'DIEGO DA SILVA', 'DIEGO DA SILVA', 'AG', 'AG-FIGWAL'
  UNION ALL SELECT 'FABIO BADIA', 'FABIO BADIA', 'AG', 'AG-FIGWAL'
  UNION ALL SELECT 'PATRÍCIA MEDEIROS', 'PATRÍCIA MEDEIROS', 'AG', 'AG-FIGWAL'
  UNION ALL SELECT 'SONIA SALOMAO', 'SONIA SALOMAO', 'AG', 'AG-FIGWAL'
  UNION ALL SELECT 'WALTER  COSTA', 'WALTER  COSTA', 'AG', 'AG-FIGWAL'
  UNION ALL SELECT 'ELLA GU', 'ELLA GU', 'AG', 'AG-FLYINGSHRIMPGROUP'
  UNION ALL SELECT 'FRED LUAHA', 'FRED LUAHA', 'AG', 'AG-FORWARDAIRLTD'
  UNION ALL SELECT 'JASMIN AHMED', 'JASMIN AHMED', 'AG', 'AG-FREIGHTSOLUTIONS'
  UNION ALL SELECT 'MENNA-TULLAH NABIL', 'MENNA-TULLAH NABIL', 'AG', 'AG-FREIGHTSOLUTIONS'
  UNION ALL SELECT 'MOHAMED GAWEESH', 'MOHAMED GAWEESH', 'AG', 'AG-FREIGHTSOLUTIONS'
  UNION ALL SELECT 'MS. JASMIN AHMED', 'MS. JASMIN AHMED', 'AG', 'AG-FREIGHTSOLUTIONS'
  UNION ALL SELECT 'RUPALI TARACHAND', 'RUPALI TARACHAND', 'AG', 'AG-FREIGHTLINKS'
  UNION ALL SELECT 'CAROL MWANGI', 'CAROL MWANGI', 'AG', 'AG-FREIGHTWAYSGLOBALSOLUTIONS'
  UNION ALL SELECT 'EMMANUEL', 'EMMANUEL', 'AG', 'AG-FREIGHTWAYSGLOBALSOLUTIONS'
  UNION ALL SELECT 'EMMANUEL CHUMBA', 'EMMANUEL CHUMBA', 'AG', 'AG-FREIGHTWAYSGLOBALSOLUTIONS'
  UNION ALL SELECT 'HELLEN KYALO', 'HELLEN KYALO', 'AG', 'AG-FREIGHTWAYSGLOBALSOLUTIONS'
  UNION ALL SELECT 'SHELLY SHIMON', 'SHELLY SHIMON', 'AG', 'AG-FRIDENSON'
  UNION ALL SELECT 'TAL LEVY', 'TAL LEVY', 'AG', 'AG-FRIDENSON'
  UNION ALL SELECT 'RODRIGO MONSALVE SOLAR', 'RODRIGO MONSALVE SOLAR', 'AG', 'AG-GALPER'
  UNION ALL SELECT 'JOE WANG', 'JOE WANG', 'AG', 'AG-GAMECHANGE'
  UNION ALL SELECT 'DORA CHANG', 'DORA CHANG', 'AG', 'AG-GENERALMERCHANDISECONSOLIDATORS'
  UNION ALL SELECT 'ABIDJAH KAGUONGO', 'ABIDJAH KAGUONGO', 'AG', 'AG-GEXLOGISTICS'
  UNION ALL SELECT 'CYNTHIA BUJULA', 'CYNTHIA BUJULA', 'AG', 'AG-GEXLOGISTICS'
  UNION ALL SELECT 'ESTHER ABIGAEL KIMANI', 'ESTHER ABIGAEL KIMANI', 'AG', 'AG-GEXLOGISTICS'
  UNION ALL SELECT 'RACHEAL MARTHA ATOO', 'RACHEAL MARTHA ATOO', 'AG', 'AG-GEXLOGISTICS'
  UNION ALL SELECT 'SHARON OJUNJU', 'SHARON OJUNJU', 'AG', 'AG-GEXLOGISTICS'
  UNION ALL SELECT 'THUSHARA PRIYADHARSHANA', 'THUSHARA PRIYADHARSHANA', 'AG', 'AG-GEXLOGISTICS'
  UNION ALL SELECT 'OSEN ARABOGA', 'OSEN ARABOGA', 'AG', 'AG-GEZAIRITRANSPORT'
  UNION ALL SELECT 'YUSUF YAZIRLIOGLU', 'YUSUF YAZIRLIOGLU', 'AG', 'AG-GEZAIRITRANSPORT'
  UNION ALL SELECT 'TIBOR BALAZS', 'TIBOR BALAZS', 'AG', 'AG-GHABZE'
  UNION ALL SELECT 'DELIA GOMARA NAVARRO', 'DELIA GOMARA NAVARRO', 'AG', 'AG-GIMEX'
  UNION ALL SELECT 'ROOPA SHRISHAR', 'ROOPA SHRISHAR', 'AG', 'AG-GLOBALFREIGHTSYSTEMSCO'
  UNION ALL SELECT 'SPYROS ZAFEIRIS', 'SPYROS ZAFEIRIS', 'AG', 'AG-GLOBALHELLENIC'
  UNION ALL SELECT 'BANSI AHARI', 'BANSI AHARI', 'AG', 'AG-GLOBALLOGISTICS'
  UNION ALL SELECT 'JAYDEV OZA', 'JAYDEV OZA', 'AG', 'AG-GLOBALLOGISTICS'
  UNION ALL SELECT 'ANNE CHANG', 'ANNE CHANG', 'AG', 'AG-GMCTXG'
  UNION ALL SELECT 'JOAN LIN', 'JOAN LIN', 'AG', 'AG-GMCTXG'
  UNION ALL SELECT 'MANDY LIN', 'MANDY LIN', 'AG', 'AG-GMCTXG'
  UNION ALL SELECT 'VESTA WANG', 'VESTA WANG', 'AG', 'AG-GMCTXG'
  UNION ALL SELECT 'J.XIN.Y', 'J.XIN.Y', 'AG', 'AG-GOLDENDRAGON'
  UNION ALL SELECT 'GABRIEL MANRIQUE', 'GABRIEL MANRIQUE', 'AG', 'AG-GOLDLOGBRAZIL'
  UNION ALL SELECT 'GIANNA TESTA', 'GIANNA TESTA', 'AG', 'AG-GORGONISRL'
  UNION ALL SELECT 'ISMAIL NAZAR', 'ISMAIL NAZAR', 'AG', 'AG-GSM'
  UNION ALL SELECT 'LIZ', 'LIZ', 'AG', 'AG-GUANGZHOUMINTONGTRADING'
  UNION ALL SELECT 'SNEHA SAAMPAT', 'SNEHA SAAMPAT', 'AG', 'AG-GULFAGENCYCOMPANY'
  UNION ALL SELECT 'NATALYA EROKHINA', 'NATALYA EROKHINA', 'AG', 'AG-GUNTERMEDICALGMBH'
  UNION ALL SELECT 'CAMILA ALVES', 'CAMILA ALVES', 'AG', 'AG-GWL'
  UNION ALL SELECT 'CARLOS BATISTA', 'CARLOS BATISTA', 'AG', 'AG-GWL'
  UNION ALL SELECT 'GUSTAVO HENRIQUE', 'GUSTAVO HENRIQUE', 'AG', 'AG-GWL'
  UNION ALL SELECT 'MURILO LUIZ', 'MURILO LUIZ', 'AG', 'AG-GWL'
  UNION ALL SELECT 'JOPHY LAM', 'JOPHY LAM', 'AG', 'AG-HARFORDMETALWARELTD'
  UNION ALL SELECT 'KEILAH CHAO', 'KEILAH CHAO', 'AG', 'AG-HKFLYINGSHRIMPGROUP'
  UNION ALL SELECT 'MIKO DONG', 'MIKO DONG', 'AG', 'AG-HKFLYINGSHRIMPGROUP'
  UNION ALL SELECT 'WINDY MAO', 'WINDY MAO', 'AG', 'AG-HKFLYINGSHRIMP'
  UNION ALL SELECT 'SANDRA', 'SANDRA', 'AG', 'AG-HOMEBESTINTERNATIONAL'
  UNION ALL SELECT 'LATHA', 'LATHA', 'AG', 'AG-HTLLOGISTICS'
  UNION ALL SELECT 'SRIDHAR BABU', 'SRIDHAR BABU', 'AG', 'AG-HTLLOGISTICS'
  UNION ALL SELECT 'NOHA MOUSTAFA', 'NOHA MOUSTAFA', 'AG', 'AG-INCOTRANS'
  UNION ALL SELECT 'RANDA SABER', 'RANDA SABER', 'AG', 'AG-INCOTRANS'
  UNION ALL SELECT 'ANTON ELOFSSON', 'ANTON ELOFSSON', 'AG', 'AG-INDEPENDENTTRANSPORTSHIPPING'
  UNION ALL SELECT 'FACUNDO CUELLO', 'FACUNDO CUELLO', 'AG', 'AG-INTERBORDERS'
  UNION ALL SELECT 'GABI AVNI', 'GABI AVNI', 'AG', 'AG-INTERGLOBALCARGO'
  UNION ALL SELECT 'KELLY SHUKRON', 'KELLY SHUKRON', 'AG', 'AG-INTERGLOBALCARGO'
  UNION ALL SELECT 'OLALEKAN OKEBANJO', 'OLALEKAN OKEBANJO', 'AG', 'AG-ISOX'
  UNION ALL SELECT 'LANICE FERNANDES', 'LANICE FERNANDES', 'AG', 'AG-KERRYLOGISTICSBAHRAIN'
  UNION ALL SELECT 'ADOLPHE MARRACHE', 'ADOLPHE MARRACHE', 'AG', 'AG-KEYSTONETRADING'
  UNION ALL SELECT 'JOSEPH', 'JOSEPH', 'AG', 'AG-KINIFISOLOPRIMO'
  UNION ALL SELECT 'MINH HA', 'MINH HA', 'AG', 'AG-KLM'
  UNION ALL SELECT 'KARINA BORGES', 'KARINA BORGES', 'AG', 'AG-KONNECTSHIPPING'
  UNION ALL SELECT 'MS. DENIZ AKSOY', 'MS. DENIZ AKSOY', 'AG', 'AG-LAMWORLD'
  UNION ALL SELECT 'DAVID SIMMONS', 'DAVID SIMMONS', 'AG', 'AG-LEMAN'
  UNION ALL SELECT 'ROY PLUSH', 'ROY PLUSH', 'AG', 'AG-LEMAN'
  UNION ALL SELECT 'SUSANA MARTINEZ', 'SUSANA MARTINEZ', 'AG', 'AG-LEMAN'
  UNION ALL SELECT 'TRICIA PREESADA', 'TRICIA PREESADA', 'AG', 'AG-LEMAN'
  UNION ALL SELECT 'KUTAL TASKAYA', 'KUTAL TASKAYA', 'AG', 'AG-LEXULUSLARARASI'
  UNION ALL SELECT 'ANITHA', 'ANITHA', 'AG', 'AG-LOGENIXLOGISTICS'
  UNION ALL SELECT 'DIVYA CHAUDHARY', 'DIVYA CHAUDHARY', 'AG', 'AG-LOGENIXLOGISTICS'
  UNION ALL SELECT 'E ATMARAM', 'E ATMARAM', 'AG', 'AG-LOGENIXLOGISTICS'
  UNION ALL SELECT 'E. RANI', 'E. RANI', 'AG', 'AG-LOGENIXLOGISTICS'
  UNION ALL SELECT 'K.ANITHA', 'K.ANITHA', 'AG', 'AG-LOGENIXLOGISTICS'
  UNION ALL SELECT 'RAKESH G', 'RAKESH G', 'AG', 'AG-LOGENIXLOGISTICS'
  UNION ALL SELECT 'SATYAJIT DAS', 'SATYAJIT DAS', 'AG', 'AG-LOGENIXLOGISTICS'
  UNION ALL SELECT 'VINNY P. KUMAR', 'VINNY P. KUMAR', 'AG', 'AG-LOGENIXLOGISTICS'
  UNION ALL SELECT 'EMAD ALADEM', 'EMAD ALADEM', 'AG', 'AG-LOGISTICSPLUS'
  UNION ALL SELECT 'M. ZAHID', 'M. ZAHID', 'AG', 'AG-LOGISTICSSERVICESPAKISTAN'
  UNION ALL SELECT 'AYSENUR KABADAYI', 'AYSENUR KABADAYI', 'AG', 'AG-LOGIWORKS'
  UNION ALL SELECT 'VINNI VARGHESE', 'VINNI VARGHESE', 'AG', 'AG-LUSTERSHIPPING'
  UNION ALL SELECT 'GILBERT WANG', 'GILBERT WANG', 'AG', 'AG-LXCGLOBALLOGISTICS'
  UNION ALL SELECT 'MARY D''SOUZA', 'MARY D''SOUZA', 'AG', 'AG-MAINSTREAMSHIPPING'
  UNION ALL SELECT 'SHAYIL IRSHAD', 'SHAYIL IRSHAD', 'AG', 'AG-MAINSTREAMSHIPPING'
  UNION ALL SELECT 'TESNY THOMAS', 'TESNY THOMAS', 'AG', 'AG-MAINSTREAMSHIPPING'
  UNION ALL SELECT 'MICHELLE LAM', 'MICHELLE LAM', 'AG', 'AG-MARIAASIA'
  UNION ALL SELECT 'ALEJANDRA GONZALEZ', 'ALEJANDRA GONZALEZ', 'AG', 'AG-MASTERLINEGROUP'
  UNION ALL SELECT 'LEILA EL ATRI', 'LEILA EL ATRI', 'AG', 'AG-MCTC'
  UNION ALL SELECT 'SANJAY TALAISA', 'SANJAY TALAISA', 'AG', 'AG-MENILLOGISTICS'
  UNION ALL SELECT 'BHAJAN', 'BHAJAN', 'AG', 'AG-MFS'
  UNION ALL SELECT 'SREEKUTTAN K.P', 'SREEKUTTAN K.P', 'AG', 'AG-MFS'
  UNION ALL SELECT 'DEDE FITRIA', 'DEDE FITRIA', 'AG', 'AG-MII'
  UNION ALL SELECT 'DINA', 'DINA', 'AG', 'AG-MII'
  UNION ALL SELECT 'DINA NURSANTI', 'DINA NURSANTI', 'AG', 'AG-MII'
  UNION ALL SELECT 'DONNY', 'DONNY', 'AG', 'AG-MII'
  UNION ALL SELECT 'DONNY DHARMAWAN ASSAARIE', 'DONNY DHARMAWAN ASSAARIE', 'AG', 'AG-MII'
  UNION ALL SELECT 'HERI', 'HERI', 'AG', 'AG-MII'
  UNION ALL SELECT 'HERI ABDULRACHMAN', 'HERI ABDULRACHMAN', 'AG', 'AG-MII'
  UNION ALL SELECT 'NAIMA', 'NAIMA', 'AG', 'AG-MII'
  UNION ALL SELECT 'PRASETYO WIBOWO', 'PRASETYO WIBOWO', 'AG', 'AG-MII'
  UNION ALL SELECT 'VICKY', 'VICKY', 'AG', 'AG-MII'
  UNION ALL SELECT 'VICKY W ZAHID', 'VICKY W ZAHID', 'AG', 'AG-MII'
  UNION ALL SELECT 'SUBU', 'SUBU', 'AG', 'AG-MODA'
  UNION ALL SELECT 'SURESH', 'SURESH', 'AG', 'AG-MODAVITTA'
  UNION ALL SELECT 'BHAJAN VINODKUMAR', 'BHAJAN VINODKUMAR', 'AG', 'AG-MULTIMODELFREIGHTSOLUTIONS'
  UNION ALL SELECT 'GLENDA SAKAITIS', 'GLENDA SAKAITIS', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'GWEN AREVALO', 'GWEN AREVALO', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'JENNIFER HALE SANDERS', 'JENNIFER HALE SANDERS', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'JENNIFER HALE-SANDERS', 'JENNIFER HALE-SANDERS', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'KIM EDMUNSON', 'KIM EDMUNSON', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'MELISSA CAMPBELL', 'MELISSA CAMPBELL', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'NHI NGUY', 'NHI NGUY', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'RINA PRICE', 'RINA PRICE', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'SHEFALI PANCHAL', 'SHEFALI PANCHAL', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'TRACIE SILVER-WILSON', 'TRACIE SILVER-WILSON', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'VEENA ABRAHAM', 'VEENA ABRAHAM', 'AG', 'AG-NEARNORTHCUSTOMS'
  UNION ALL SELECT 'RICARDO VILA', 'RICARDO VILA', 'AG', 'AG-NENACOMEXLOGISTICS'
  UNION ALL SELECT 'SHAHNAS PN', 'SHAHNAS PN', 'AG', 'AG-OCEANLINK'
  UNION ALL SELECT 'CRYSTAL LABORTE', 'CRYSTAL LABORTE', 'AG', 'AG-ONTIME'
  UNION ALL SELECT 'LUZEL LANUZO', 'LUZEL LANUZO', 'AG', 'AG-ONTIME'
  UNION ALL SELECT 'SHAHAB KHAN', 'SHAHAB KHAN', 'AG', 'AG-ONWARD'
  UNION ALL SELECT 'CRISTALLE LIMJOCO', 'CRISTALLE LIMJOCO', 'AG', 'AG-OSHAIGER'
  UNION ALL SELECT 'JANE MANGARING', 'JANE MANGARING', 'AG', 'AG-OSHAIGER'
  UNION ALL SELECT 'JENZEL MARIE M. NARCISO', 'JENZEL MARIE M. NARCISO', 'AG', 'AG-OSHAIGER'
  UNION ALL SELECT 'JULIUS CAESAR B. ROQUE', 'JULIUS CAESAR B. ROQUE', 'AG', 'AG-OSHAIGER'
  UNION ALL SELECT 'NEIL TAYLOR M.', 'NEIL TAYLOR M.', 'AG', 'AG-PACIFICANCHORLINE'
  UNION ALL SELECT 'ARPITA', 'ARPITA', 'AG', 'AG-PACIFICOCEAN'
  UNION ALL SELECT 'HALEEMA ASIF', 'HALEEMA ASIF', 'AG', 'AG-PAKISTANCARGOSERVICE'
  UNION ALL SELECT 'MUHAMMAD NAEEM', 'MUHAMMAD NAEEM', 'AG', 'AG-PAKISTANCARGOSERVICE'
  UNION ALL SELECT 'MUHAMMAD USMAN UL HAQ', 'MUHAMMAD USMAN UL HAQ', 'AG', 'AG-PAKISTANCARGOSERVICE'
  UNION ALL SELECT 'DYLAN TAYLOR', 'DYLAN TAYLOR', 'AG', 'AG-PALLOGISTICS'
  UNION ALL SELECT 'CHRISTA', 'CHRISTA', 'AG', 'AG-PANINDIACHRISTA'
  UNION ALL SELECT 'CYRIL SORDA', 'CYRIL SORDA', 'AG', 'AG-PARC'
  UNION ALL SELECT 'HAMID MUMTAZ', 'HAMID MUMTAZ', 'AG', 'AG-PCS'
  UNION ALL SELECT 'IMRAN KHAN', 'IMRAN KHAN', 'AG', 'AG-PCS'
  UNION ALL SELECT 'MUHAMMAD', 'MUHAMMAD', 'AG', 'AG-PCS'
  UNION ALL SELECT 'ERIC TRUC', 'ERIC TRUC', 'AG', 'AG-PHILIORIENT'
  UNION ALL SELECT 'ZIPPI ZIMMERMAN', 'ZIPPI ZIMMERMAN', 'AG', 'AG-PLASCOWLOGISTICSLTD'
  UNION ALL SELECT 'ZEINA HAMED', 'ZEINA HAMED', 'AG', 'AG-PREMIUMPARTNERS'
  UNION ALL SELECT 'DINI', 'DINI', 'AG', 'AG-PTFIDO'
  UNION ALL SELECT 'DINI YANRIANI', 'DINI YANRIANI', 'AG', 'AG-PTFIDO'
  UNION ALL SELECT 'HARRISON TAMPUBOLON', 'HARRISON TAMPUBOLON', 'AG', 'AG-PTFIDO'
  UNION ALL SELECT 'RENNNY LUBIS', 'RENNNY LUBIS', 'AG', 'AG-PTFIDO'
  UNION ALL SELECT 'ANGGIE', 'ANGGIE', 'AG', 'AG-PTSILKARGOINDONESIA'
  UNION ALL SELECT 'DIOFALDO D ARDHANA', 'DIOFALDO D ARDHANA', 'AG', 'AG-PTSILKARGOINDONESIA'
  UNION ALL SELECT 'SARAH F LIANDAR', 'SARAH F LIANDAR', 'AG', 'AG-PTSILKARGOINDONESIA'
  UNION ALL SELECT 'LIELA MONICA', 'LIELA MONICA', 'AG', 'AG-PTMILITZERANDMUENCHINDONESIA'
  UNION ALL SELECT 'GITA MAULINDA', 'GITA MAULINDA', 'AG', 'AG-PTSENATOR'
  UNION ALL SELECT 'MARIAN PARK', 'MARIAN PARK', 'AG', 'AG-PTSENATOR'
  UNION ALL SELECT 'MUDASSAR', 'MUDASSAR', 'AG', 'AG-QUALITY'
  UNION ALL SELECT 'MUDASSAR BASHIR KAMBOH', 'MUDASSAR BASHIR KAMBOH', 'AG', 'AG-QUALITY'
  UNION ALL SELECT 'RACHAEL MARTHA ATOO', 'RACHAEL MARTHA ATOO', 'AG', 'AG-RACHAELMARTHAATOO'
  UNION ALL SELECT 'QIUER WU', 'QIUER WU', 'AG', 'AG-RAINBOWSPRING'
  UNION ALL SELECT 'ASIF HUSSAIN', 'ASIF HUSSAIN', 'AG', 'AG-RAVIANINTERNATIONAL'
  UNION ALL SELECT 'NAVEED', 'NAVEED', 'AG', 'AG-RAVIANINTERNATIONAL'
  UNION ALL SELECT 'UROOJ MEHAR', 'UROOJ MEHAR', 'AG', 'AG-RAVIANINTERNATIONAL'
  UNION ALL SELECT 'ELUANI VILLALOBOS NUÑEZ', 'ELUANI VILLALOBOS NUÑEZ', 'AG', 'AG-REXCARGO'
  UNION ALL SELECT 'JAMIE', 'JAMIE', 'AG', 'AG-REXCARGO'
  UNION ALL SELECT 'KENSY TRIGUEROS ESTRADA', 'KENSY TRIGUEROS ESTRADA', 'AG', 'AG-REXCARGO'
  UNION ALL SELECT 'SABRINA MARIN', 'SABRINA MARIN', 'AG', 'AG-REXCARGO'
  UNION ALL SELECT 'ALAA KAMEL', 'ALAA KAMEL', 'AG', 'AG-SAMMANTRANS'
  UNION ALL SELECT 'MS. ALAA KAMEL', 'MS. ALAA KAMEL', 'AG', 'AG-SAMMANTRANS'
  UNION ALL SELECT 'INDRA PRASETIA KUSUMA', 'INDRA PRASETIA KUSUMA', 'AG', 'AG-SAMUDERA'
  UNION ALL SELECT 'SHINTA APRILIA', 'SHINTA APRILIA', 'AG', 'AG-SAMUDERA'
  UNION ALL SELECT 'WAHYU PUSPITA ANGGRAENI (ANGGIE)', 'WAHYU PUSPITA ANGGRAENI (ANGGIE)', 'AG', 'AG-SAMUDERA'
  UNION ALL SELECT 'LILIANA ALFARO ALVAREZ', 'LILIANA ALFARO ALVAREZ', 'AG', 'AG-SBLOGISTICS'
  UNION ALL SELECT 'NIA SANDEEP', 'NIA SANDEEP', 'AG', 'AG-SEGURO'
  UNION ALL SELECT 'NATALIA VÉLIZ', 'NATALIA VÉLIZ', 'AG', 'AG-SES'
  UNION ALL SELECT 'ORBETA', 'ORBETA', 'AG', 'AG-SES'
  UNION ALL SELECT 'ADAM BULLAS', 'ADAM BULLAS', 'AG', 'AG-SF'
  UNION ALL SELECT 'GOPI R.', 'GOPI R.', 'AG', 'AG-SHIFTCO'
  UNION ALL SELECT 'CSD FASHION', 'CSD FASHION', 'AG', 'AG-SHPR'
  UNION ALL SELECT 'JIHEN SALLEM', 'JIHEN SALLEM', 'AG', 'AG-SINDBADGROUPE'
  UNION ALL SELECT 'NEDRA BEN SALEM', 'NEDRA BEN SALEM', 'AG', 'AG-SINDBADGROUPE'
  UNION ALL SELECT 'HELMI BEN SHIL', 'HELMI BEN SHIL', 'AG', 'AG-SINDBAD'
  UNION ALL SELECT 'MENYAR HAMLIA', 'MENYAR HAMLIA', 'AG', 'AG-SINDBAD'
  UNION ALL SELECT 'AKCES', 'AKCES', 'AG', 'AG-SPEEDCARGO'
  UNION ALL SELECT 'CESAR AKOU', 'CESAR AKOU', 'AG', 'AG-SPEEDCARGO'
  UNION ALL SELECT 'CESAR AYETCHO', 'CESAR AYETCHO', 'AG', 'AG-SPEEDCARGO'
  UNION ALL SELECT 'FREDERICK HAGGOO', 'FREDERICK HAGGOO', 'AG', 'AG-SPEEDFREIGHT'
  UNION ALL SELECT 'HARISH BHAGIRATTY', 'HARISH BHAGIRATTY', 'AG', 'AG-SPEEDFREIGHT'
  UNION ALL SELECT 'JUILA WONG', 'JUILA WONG', 'AG', 'AG-SPEEDFREIGHT'
  UNION ALL SELECT 'JULIA WONG', 'JULIA WONG', 'AG', 'AG-SPEEDFREIGHT'
  UNION ALL SELECT 'RUBINA RAMUDU', 'RUBINA RAMUDU', 'AG', 'AG-SPEEDFREIGHT'
  UNION ALL SELECT 'SAROJA PILLAY', 'SAROJA PILLAY', 'AG', 'AG-SPEEDFREIGHT'
  UNION ALL SELECT 'SHANDOSHINI GOVINDEN', 'SHANDOSHINI GOVINDEN', 'AG', 'AG-SPEEDFREIGHT'
  UNION ALL SELECT 'STEFFEN MANZ', 'STEFFEN MANZ', 'AG', 'AG-SPEEDFREIGHT'
  UNION ALL SELECT 'WENDY', 'WENDY', 'AG', 'AG-SPEEDFREIGHT'
  UNION ALL SELECT 'RIZKI SETIAWAN', 'RIZKI SETIAWAN', 'AG', 'AG-SUNGGONGLOGISTICS'
  UNION ALL SELECT 'DOM MCSPORRAN', 'DOM MCSPORRAN', 'AG', 'AG-SUREFREIGHTINTERNATIONAL'
  UNION ALL SELECT 'MRS.GULMIRA AKYÜREK', 'MRS.GULMIRA AKYÜREK', 'AG', 'AG-TALOS'
  UNION ALL SELECT 'TUAN ANH (MR.)', 'TUAN ANH (MR.)', 'AG', 'AG-TAMANHTRADING'
  UNION ALL SELECT 'YEN DOAN', 'YEN DOAN', 'AG', 'AG-TAMANHTRADING'
  UNION ALL SELECT 'FAYYAZ GAZIANI', 'FAYYAZ GAZIANI', 'AG', 'AG-TEAMFREIGHTMANAGEMENT'
  UNION ALL SELECT 'TAHIR ALI', 'TAHIR ALI', 'AG', 'AG-TEAMFREIGHTMANAGEMENT'
  UNION ALL SELECT 'ESSAM NOUR EL AWAMRY', 'ESSAM NOUR EL AWAMRY', 'AG', 'AG-TIFFANYCARGOSYSTEM'
  UNION ALL SELECT 'JUAN GONZALEZ', 'JUAN GONZALEZ', 'AG', 'AG-TRACOSA'
  UNION ALL SELECT 'GLORIA', 'GLORIA', 'AG', 'AG-TRANSMERIDIAN'
  UNION ALL SELECT 'NICODEMUS KILONZO', 'NICODEMUS KILONZO', 'AG', 'AG-TRANSMERIDIAN'
  UNION ALL SELECT 'TERUKO YASUSHIRO', 'TERUKO YASUSHIRO', 'AG', 'AG-UCI'
  UNION ALL SELECT 'ASHIK NAZEER', 'ASHIK NAZEER', 'AG', 'AG-UNIVERSALBRIDGELOGISTICS'
  UNION ALL SELECT 'ALESSANDRA COMOTTO', 'ALESSANDRA COMOTTO', 'AG', 'AG-UTCMEDITERRANEANSRLU'
  UNION ALL SELECT 'ALESSANDRO BUFFA', 'ALESSANDRO BUFFA', 'AG', 'AG-UTCMEDITERRANEANSRLU'
  UNION ALL SELECT 'ALESSIO DE NICOLO', 'ALESSIO DE NICOLO', 'AG', 'AG-UTCMEDITERRANEANSRLU'
  UNION ALL SELECT 'DAVIDE SCOVERO', 'DAVIDE SCOVERO', 'AG', 'AG-UTCMEDITERRANEANSRLU'
  UNION ALL SELECT 'LAURA TORRE', 'LAURA TORRE', 'AG', 'AG-UTCMEDITERRANEANSRLU'
  UNION ALL SELECT 'NICOLA CALLERI', 'NICOLA CALLERI', 'AG', 'AG-UTCMEDITERRANEANSRLU'
  UNION ALL SELECT 'BIKI', 'BIKI', 'AG', 'AG-VANLOGISTICSBGD'
  UNION ALL SELECT 'BIKIRAN BARUA BIKI', 'BIKIRAN BARUA BIKI', 'AG', 'AG-VANLOGISTICSBGD'
  UNION ALL SELECT 'RUTABA BUTT', 'RUTABA BUTT', 'AG', 'AG-VELOCITYSHIPPINGPVT'
  UNION ALL SELECT 'VINCE CURRO', 'VINCE CURRO', 'AG', 'AG-VIECOM'
  UNION ALL SELECT 'AMY', 'AMY', 'AG', 'AG-VINALINK'
  UNION ALL SELECT 'OM PRASAD', 'OM PRASAD', 'AG', 'AG-VRRDHI'
  UNION ALL SELECT 'GERARD MALCAHY', 'GERARD MALCAHY', 'AG', 'AG-WESTCOASTAVIATION'
  UNION ALL SELECT 'GUSTAVO HENRIQUE CARDOSO', 'GUSTAVO HENRIQUE CARDOSO', 'AG', 'AG-WIDELOGISTICS'
  UNION ALL SELECT 'WINNIE CHEUNG', 'WINNIE CHEUNG', 'AG', 'AG-WIDEAL'
  UNION ALL SELECT 'AZM SALAH UDDIN CHOWDHURY', 'AZM SALAH UDDIN CHOWDHURY', 'AG', 'AG-WORLDFAMOUS'
  UNION ALL SELECT 'SALAH UDDIN', 'SALAH UDDIN', 'AG', 'AG-WORLDFAMOUS'
  UNION ALL SELECT 'JASON', 'JASON', 'AG', 'AG-WUXIJIAHUAINTERNATIONALFREIGHT'
  UNION ALL SELECT 'FIONA', 'FIONA', 'AG', 'AG-WUXIJIAYIINTERNATIONAL'
  UNION ALL SELECT 'IRIS', 'IRIS', 'AG', 'AG-WUXIJIAYIINTERNATIONAL'
  UNION ALL SELECT 'FILIPPA NICOSIA', 'FILIPPA NICOSIA', 'AG', 'AG-ZUSTAMBROSETTI'
  UNION ALL SELECT 'ANN ABRAMS', 'ANN ABRAMS', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'ARIANE DE RAYMAEKER', 'ARIANE DE RAYMAEKER', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'BART VANHAM', 'BART VANHAM', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'BETTINA VAN DER LINDEN', 'BETTINA VAN DER LINDEN', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'CATHY CLERBOIS', 'CATHY CLERBOIS', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'CHRISTIAN', 'CHRISTIAN', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'CHRISTINE TRAPPENIERS', 'CHRISTINE TRAPPENIERS', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'CHRISTOPHE VERMEULEN', 'CHRISTOPHE VERMEULEN', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'GUILAINE LAYAN', 'GUILAINE LAYAN', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'GUY GOESTSCHALCKX', 'GUY GOESTSCHALCKX', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'INGE RYDANT', 'INGE RYDANT', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'INGEMAR ANDERSSON', 'INGEMAR ANDERSSON', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'ISAM EL BEKKAYE', 'ISAM EL BEKKAYE', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'IVAN DE PAUW', 'IVAN DE PAUW', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'JOERI KENNES', 'JOERI KENNES', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'JOHAN ENGELBRECHT', 'JOHAN ENGELBRECHT', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'KARINE VANHUMBEECK', 'KARINE VANHUMBEECK', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'LAETITIA SEDDA', 'LAETITIA SEDDA', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'LUC AUDIENS', 'LUC AUDIENS', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'MATHIAS VERMEIREN', 'MATHIAS VERMEIREN', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'MICHIEL JACOBS', 'MICHIEL JACOBS', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'NATALIA GURANDA', 'NATALIA GURANDA', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'PETER DANIELS', 'PETER DANIELS', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'RUDI VERSCHUEREN', 'RUDI VERSCHUEREN', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'SOFIE MILANTS', 'SOFIE MILANTS', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'STEPHAN VAN DEN BRUEL', 'STEPHAN VAN DEN BRUEL', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'TOM VERKOELEN', 'TOM VERKOELEN', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'WIM PEETERS', 'WIM PEETERS', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'WOLF KUSSÉ', 'WOLF KUSSÉ', 'BE', 'BE-ZIEGLERBELGIUM'
  UNION ALL SELECT 'ALEX', 'ALEX', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'ALEXANDER REISER', 'ALEXANDER REISER', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'ANDY', 'ANDY', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'ANDY EGGENBERGER', 'ANDY EGGENBERGER', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'BAHRIYE ÖZALP', 'BAHRIYE ÖZALP', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'CAMILLE PARENT', 'CAMILLE PARENT', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'CASHROM SELVARATNAM', 'CASHROM SELVARATNAM', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'CÉLINE', 'CÉLINE', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'CELYA GOUBERT', 'CELYA GOUBERT', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'CHRISTIAN BRECHENMACHER', 'CHRISTIAN BRECHENMACHER', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'DANIEL MELE', 'DANIEL MELE', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'DANIEL SIGRIST', 'DANIEL SIGRIST', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'EMANUEL RECHSTEINER', 'EMANUEL RECHSTEINER', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'EMRE KARADENIZ', 'EMRE KARADENIZ', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'ESTELLE KOEHL', 'ESTELLE KOEHL', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'FITIM KRYEZIU', 'FITIM KRYEZIU', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'JOEL WALTER', 'JOEL WALTER', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'JOFFREY FELIX', 'JOFFREY FELIX', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'MARCO SUTER', 'MARCO SUTER', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'MELANIE KÄLIN', 'MELANIE KÄLIN', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'MIRJAM BAERLOCHER', 'MIRJAM BAERLOCHER', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'PATRICK GALLAIS', 'PATRICK GALLAIS', 'CH', 'CH-ZIEGLERSWITZERLAND'
  UNION ALL SELECT 'ANGEL TSE', 'ANGEL TSE', 'CN', 'CN-ZIEGLERHONGKONG'
  UNION ALL SELECT 'DOROTHY LAI', 'DOROTHY LAI', 'CN', 'CN-ZIEGLERHONGKONG'
  UNION ALL SELECT 'KRISTINE HO', 'KRISTINE HO', 'CN', 'CN-ZIEGLERHONGKONG'
  UNION ALL SELECT 'LOUIS CHAN', 'LOUIS CHAN', 'CN', 'CN-ZIEGLERHONGKONG'
  UNION ALL SELECT 'PHILIP WONG', 'PHILIP WONG', 'CN', 'CN-ZIEGLERHONGKONG'
  UNION ALL SELECT 'STONE CHAN', 'STONE CHAN', 'CN', 'CN-ZIEGLERHONGKONG'
  UNION ALL SELECT 'SUSANA WONG', 'SUSANA WONG', 'CN', 'CN-ZIEGLERHONGKONG'
  UNION ALL SELECT 'YUKI CHAN', 'YUKI CHAN', 'CN', 'CN-ZIEGLERHONGKONG'
  UNION ALL SELECT 'ZAKY', 'ZAKY', 'CN', 'CN-ZIEGLERHONGKONG'
  UNION ALL SELECT 'NICY YANG', 'NICY YANG', 'CN', 'CN-ZIEGLERNINGBO'
  UNION ALL SELECT 'VIVIAN LI', 'VIVIAN LI', 'CN', 'CN-ZIEGLERNINGBO'
  UNION ALL SELECT 'HETTY HAO', 'HETTY HAO', 'CN', 'CN-ZIEGLERQINGDAO'
  UNION ALL SELECT 'NICOLE YUAN', 'NICOLE YUAN', 'CN', 'CN-ZIEGLERQINGDAO'
  UNION ALL SELECT 'AMY CHEN', 'AMY CHEN', 'CN', 'CN-ZIEGLERSHANGHAI'
  UNION ALL SELECT 'HAIQING SONG', 'HAIQING SONG', 'CN', 'CN-ZIEGLERSHANGHAI'
  UNION ALL SELECT 'JASON JI', 'JASON JI', 'CN', 'CN-ZIEGLERSHANGHAI'
  UNION ALL SELECT 'SAM LIN', 'SAM LIN', 'CN', 'CN-ZIEGLERSHENZHEN'
  UNION ALL SELECT 'SHAWN LUO', 'SHAWN LUO', 'CN', 'CN-ZIEGLERSHENZHEN'
  UNION ALL SELECT 'SUSAN ZHAO', 'SUSAN ZHAO', 'CN', 'CN-ZIEGLERSHENZHEN'
  UNION ALL SELECT 'TINA WANG', 'TINA WANG', 'CN', 'CN-ZIEGLERTIANJIN'
  UNION ALL SELECT 'HELEN WU', 'HELEN WU', 'CN', 'CN-ZIEGLERXIAMEN'
  UNION ALL SELECT 'AARON KIRBERG', 'AARON KIRBERG', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'ANGELIKA', 'ANGELIKA', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'ANN-KATHRIN ZEHM', 'ANN-KATHRIN ZEHM', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'BARBARA HOFFMANN', 'BARBARA HOFFMANN', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'BURAK HISARKAYA', 'BURAK HISARKAYA', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'DANIEL STENZEL', 'DANIEL STENZEL', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'DENNIS HASSE', 'DENNIS HASSE', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'DILAN ULUS', 'DILAN ULUS', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'EBRU LOVRIC', 'EBRU LOVRIC', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'EDHOFER HANS', 'EDHOFER HANS', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'EMILY MAIER', 'EMILY MAIER', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'ENES AKBALIK', 'ENES AKBALIK', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'HAMZA CHAWKI', 'HAMZA CHAWKI', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'HEIKE OHDE', 'HEIKE OHDE', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'HYEYOUN NAM', 'HYEYOUN NAM', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'JACQUELINE CABRERA', 'JACQUELINE CABRERA', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'JAKOB MATERI', 'JAKOB MATERI', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'JEROME MARSHALL', 'JEROME MARSHALL', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'JONAS NEVALA', 'JONAS NEVALA', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'JULIA SCHLZE', 'JULIA SCHLZE', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'JULIAN SCHERR', 'JULIAN SCHERR', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'JUSTINE RICH', 'JUSTINE RICH', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'LARA DAUM', 'LARA DAUM', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'MANUEL RENZ', 'MANUEL RENZ', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'MARA TABEA ROSEMEIER', 'MARA TABEA ROSEMEIER', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'MARCEL BUNDGENS', 'MARCEL BUNDGENS', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'MARIUS BOEHM', 'MARIUS BOEHM', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'MARIUS PETERS', 'MARIUS PETERS', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'MARKUS MARQUARDT', 'MARKUS MARQUARDT', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'MATTHIAS PICHER', 'MATTHIAS PICHER', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'MOHAMED MIYARA', 'MOHAMED MIYARA', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'NADINE GRUNNERT', 'NADINE GRUNNERT', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'NICOLE DOERRHOEFER', 'NICOLE DOERRHOEFER', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'NILS BERGHOF', 'NILS BERGHOF', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'PETRA JESNOWSKI', 'PETRA JESNOWSKI', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'SABINE STÄBLER', 'SABINE STÄBLER', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'SAMIRA HOFBAUER', 'SAMIRA HOFBAUER', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'SELIN TEKER', 'SELIN TEKER', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'TANJA', 'TANJA', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'TANJA DEGENHARDT', 'TANJA DEGENHARDT', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'THORSTEN SCHOLZ', 'THORSTEN SCHOLZ', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'TIM STECK', 'TIM STECK', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'TOBIAS SCHROTH', 'TOBIAS SCHROTH', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'UFUK YILDIZ', 'UFUK YILDIZ', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'YOUNG KANG', 'YOUNG KANG', 'DE', 'DE-ZIEGLERGERMANY'
  UNION ALL SELECT 'ADAN BULLAS', 'ADAN BULLAS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'AHDMRA', 'AHDMRA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'AKIM JEGO', 'AKIM JEGO', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ALICE CAMI', 'ALICE CAMI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ALIX MEYER', 'ALIX MEYER', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'AMELIE ZIEGLER', 'AMELIE ZIEGLER', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'AMINE OUAABI', 'AMINE OUAABI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ANNE LAGUTERE', 'ANNE LAGUTERE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ARNAUD PARINET', 'ARNAUD PARINET', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'BARBARA CARRO', 'BARBARA CARRO', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'BARBARA GUERIN-PINAUD', 'BARBARA GUERIN-PINAUD', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'BELLE SERRE', 'BELLE SERRE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'BENJAMIN BELE', 'BENJAMIN BELE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'BERELAX - CARLA GREJALVO', 'BERELAX - CARLA GREJALVO', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'BÉRENGER HUDSON', 'BÉRENGER HUDSON', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'BRUNO TOISER', 'BRUNO TOISER', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CAPUCINE DURY', 'CAPUCINE DURY', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CARYS SHEARS', 'CARYS SHEARS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CATHY LARTELIER', 'CATHY LARTELIER', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CDG SALES', 'CDG SALES', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CECILE STRACK', 'CECILE STRACK', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CÉLINE DESTRUYS', 'CÉLINE DESTRUYS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CHRISTELLE VONESCH', 'CHRISTELLE VONESCH', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CHRISTIE PATRY', 'CHRISTIE PATRY', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CLÉMENT LE ROY BLAVET', 'CLÉMENT LE ROY BLAVET', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CORINNE PANAGIODIS', 'CORINNE PANAGIODIS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'COTATIONS BOD', 'COTATIONS BOD', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CYRILLE MANDARO', 'CYRILLE MANDARO', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'DAMIEN BERTERO', 'DAMIEN BERTERO', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'DAMIEN ROSALIA', 'DAMIEN ROSALIA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'DAVID MBENGI', 'DAVID MBENGI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ELEN CENGIZ', 'ELEN CENGIZ', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ELISABETH', 'ELISABETH', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ELISABETH GITZ', 'ELISABETH GITZ', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ELISE GOSSIN', 'ELISE GOSSIN', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ELIZA BILLAULT', 'ELIZA BILLAULT', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ESTHER SAE CHIAO', 'ESTHER SAE CHIAO', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'FANNY MARTEL', 'FANNY MARTEL', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'FANNY MARTIN', 'FANNY MARTIN', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'FANNY MAUCHAMP', 'FANNY MAUCHAMP', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'FÉLIX DEVILLIERS', 'FÉLIX DEVILLIERS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'FIDO - DINI YANRIANI', 'FIDO - DINI YANRIANI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'FLORENCE LEGROS', 'FLORENCE LEGROS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'FLORENCE MOUSSAVOU', 'FLORENCE MOUSSAVOU', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'FRANCINE LATRASSE', 'FRANCINE LATRASSE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'GHARIB ROBBA', 'GHARIB ROBBA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'HASSINA DASS', 'HASSINA DASS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'HAYET AZZOUZ', 'HAYET AZZOUZ', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'HEIKE', 'HEIKE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'HOURIA RIFFI', 'HOURIA RIFFI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'HOUSSEM BEN TORKIA', 'HOUSSEM BEN TORKIA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'IDAYATH SAKA', 'IDAYATH SAKA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'INGRID DERIMAY', 'INGRID DERIMAY', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'IRENE QUINONES', 'IRENE QUINONES', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ISABELLE BEUSTE', 'ISABELLE BEUSTE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ISABELLE SERRE', 'ISABELLE SERRE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ISMAEL DROUICHE', 'ISMAEL DROUICHE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JEAN LOUIS LEYRE', 'JEAN LOUIS LEYRE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JEAN-BAPTISTE DUBOIS', 'JEAN-BAPTISTE DUBOIS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JEAN-CHARLES HERAULT', 'JEAN-CHARLES HERAULT', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JEAN-FRANCOIS PUJOLAS', 'JEAN-FRANCOIS PUJOLAS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JEANNINE DELERUE', 'JEANNINE DELERUE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JEAN-PHILIPPE GRANDCLEMENT', 'JEAN-PHILIPPE GRANDCLEMENT', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JEMIMA FARATIANA', 'JEMIMA FARATIANA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JÉMIMA FARATIANA', 'JÉMIMA FARATIANA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JEROEN VAN PARIJS', 'JEROEN VAN PARIJS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JESSICA', 'JESSICA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JESSICA GRACE FORTUNEE', 'JESSICA GRACE FORTUNEE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JESSICA SARAIVA', 'JESSICA SARAIVA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JOHANN LEDEZ', 'JOHANN LEDEZ', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JORDAN MORNET', 'JORDAN MORNET', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JOSHUA', 'JOSHUA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JOSHUA COURTAUT', 'JOSHUA COURTAUT', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JULES MONTMAYEUL', 'JULES MONTMAYEUL', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'JUSTINE DUBOSCQ', 'JUSTINE DUBOSCQ', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'KARINE DE SOUSA', 'KARINE DE SOUSA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'KARINE ROBERTON', 'KARINE ROBERTON', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'KARINE DE SOUSA', 'KARINE DE SOUSA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LABINOT NEXHIBI', 'LABINOT NEXHIBI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LAETITIA BLANC', 'LAETITIA BLANC', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LAURELINE COURTAUT', 'LAURELINE COURTAUT', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LAURENCE BUCCI', 'LAURENCE BUCCI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LAURENCE HUI', 'LAURENCE HUI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LAURENT MATHIEU', 'LAURENT MATHIEU', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LILIA AMPLE', 'LILIA AMPLE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LINDA BEDJAOUI', 'LINDA BEDJAOUI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LORIANE BERTOLA', 'LORIANE BERTOLA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LOU-ANNE MAC CARTHY', 'LOU-ANNE MAC CARTHY', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'LUC KASTLER', 'LUC KASTLER', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MAGALI AMORE', 'MAGALI AMORE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MALIKA OUABBOU', 'MALIKA OUABBOU', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MARIE-CHRISTINE BERT', 'MARIE-CHRISTINE BERT', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MATHIEU CASES', 'MATHIEU CASES', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MATHILDE BERNARD', 'MATHILDE BERNARD', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MELANIE SCHNEIDER', 'MELANIE SCHNEIDER', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MOHAMED MOKEDDEM', 'MOHAMED MOKEDDEM', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MORGAN LAROSA', 'MORGAN LAROSA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MURIEL BERTHOLIO', 'MURIEL BERTHOLIO', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'MYLENE PAPILLON', 'MYLENE PAPILLON', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'NARJISSE CHAFI', 'NARJISSE CHAFI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'NATALIIA ROUX', 'NATALIIA ROUX', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'NATHALIE MARION', 'NATHALIE MARION', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'NATHALIE MARONNE', 'NATHALIE MARONNE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'NICOLAS MARCEL', 'NICOLAS MARCEL', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'NICOLAS SCHOTTER', 'NICOLAS SCHOTTER', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'NICOLE MARTIN', 'NICOLE MARTIN', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'NINA - VIRAPHONE SOLIPHANH', 'NINA - VIRAPHONE SOLIPHANH', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'NOUAMAN KOUCHIH', 'NOUAMAN KOUCHIH', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'OLIVIER BLANQUET', 'OLIVIER BLANQUET', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'OLIVIER BRAUD', 'OLIVIER BRAUD', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'OSHAIGER - JULIUS CAESAR B. ROQUE', 'OSHAIGER - JULIUS CAESAR B. ROQUE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'OUAFIA BOUKENSOUS', 'OUAFIA BOUKENSOUS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'OUARDA ELMALLASS', 'OUARDA ELMALLASS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'OUMAROU CISSOKHO', 'OUMAROU CISSOKHO', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'PASCAL BASSET', 'PASCAL BASSET', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'PASCAL VASSEUR', 'PASCAL VASSEUR', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'PAUL TOTAL', 'PAUL TOTAL', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'PAULINA LEWANDOWSKA', 'PAULINA LEWANDOWSKA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'PAULINE DUCERT', 'PAULINE DUCERT', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'PAULINE SANTURENNE', 'PAULINE SANTURENNE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'PIERRE HENRY', 'PIERRE HENRY', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'RACHEL KOELIN', 'RACHEL KOELIN', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'RACHIDA BELAID', 'RACHIDA BELAID', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'RAM AEROSPACE', 'RAM AEROSPACE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ROBIN PAULAS', 'ROBIN PAULAS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ROHAN DELAPORTE', 'ROHAN DELAPORTE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ROMAIN DA SILVA', 'ROMAIN DA SILVA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ROMAIN JANSSENS', 'ROMAIN JANSSENS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ROMANE MAZERAND', 'ROMANE MAZERAND', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'ROYAL AIR MAROC', 'ROYAL AIR MAROC', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SABRINA GRAS', 'SABRINA GRAS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SABRINA HUE', 'SABRINA HUE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SABRINA GRAS', 'SABRINA GRAS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SAMIR REBBOUH', 'SAMIR REBBOUH', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SANDRINE JUILLIEN', 'SANDRINE JUILLIEN', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SANDRINE PIERRET', 'SANDRINE PIERRET', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SARAH DUBUS', 'SARAH DUBUS', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SASHA RONCIN', 'SASHA RONCIN', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SCHNEIDER MÉLANIE', 'SCHNEIDER MÉLANIE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SEBASTIEN', 'SEBASTIEN', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SEBASTIEN BARDIN', 'SEBASTIEN BARDIN', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SEBASTIEN CORDIER', 'SEBASTIEN CORDIER', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SEVERINE BAYLE', 'SEVERINE BAYLE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SIMAR REBBOUH', 'SIMAR REBBOUH', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SOFIEN ATYF', 'SOFIEN ATYF', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'STEPHIE COMBE', 'STEPHIE COMBE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'SYLVAIN FIAKAIFONU', 'SYLVAIN FIAKAIFONU', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'THIBAUT MALFOY', 'THIBAUT MALFOY', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'THOMAS MENNECIER', 'THOMAS MENNECIER', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'TOUFIK SERHIRI', 'TOUFIK SERHIRI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'VALERIA RAHAMEFY', 'VALERIA RAHAMEFY', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'VANESSA BALAVOINE', 'VANESSA BALAVOINE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'VANESSA LEFORT-VENDANGE', 'VANESSA LEFORT-VENDANGE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'VINCENT DUCHESNE', 'VINCENT DUCHESNE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'VINCENT GAUCI', 'VINCENT GAUCI', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'VIRAPHONE SOLIPHANH', 'VIRAPHONE SOLIPHANH', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'VIRGINIE PLOQUIN', 'VIRGINIE PLOQUIN', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'WASSIM GARMA', 'WASSIM GARMA', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'YANN LORÉE', 'YANN LORÉE', 'FR', 'FR-ZIEGLERFRANCE'
  UNION ALL SELECT 'CHANTEL GIBBONS', 'CHANTEL GIBBONS', 'GB', 'GB-ZIEGLERBIRMINGHAM'
  UNION ALL SELECT 'CHRIS BLOWER', 'CHRIS BLOWER', 'GB', 'GB-ZIEGLERBIRMINGHAM'
  UNION ALL SELECT 'NICK POPE', 'NICK POPE', 'GB', 'GB-ZIEGLERBIRMINGHAM'
  UNION ALL SELECT 'PHIL BUCKLE', 'PHIL BUCKLE', 'GB', 'GB-ZIEGLERBIRMINGHAM'
  UNION ALL SELECT 'RUTH BUDD', 'RUTH BUDD', 'GB', 'GB-ZIEGLERBIRMINGHAM'
  UNION ALL SELECT 'TREVOR BROWN', 'TREVOR BROWN', 'GB', 'GB-ZIEGLERBIRMINGHAM'
  UNION ALL SELECT 'ADAM PORRITT', 'ADAM PORRITT', 'GB', 'GB-ZIEGLERBRADFORD'
  UNION ALL SELECT 'BEN CROWE', 'BEN CROWE', 'GB', 'GB-ZIEGLERBRADFORD'
  UNION ALL SELECT 'KATIE-LOUISE SCOTT', 'KATIE-LOUISE SCOTT', 'GB', 'GB-ZIEGLERBRADFORD'
  UNION ALL SELECT 'KIRSTY FEATHERSTONE', 'KIRSTY FEATHERSTONE', 'GB', 'GB-ZIEGLERBRADFORD'
  UNION ALL SELECT 'MATTHEW SMITH', 'MATTHEW SMITH', 'GB', 'GB-ZIEGLERBRADFORD'
  UNION ALL SELECT 'CHRIS TAYLER', 'CHRIS TAYLER', 'GB', 'GB-ZIEGLERBRISTOL'
  UNION ALL SELECT 'MARCUS ASHLEY', 'MARCUS ASHLEY', 'GB', 'GB-ZIEGLERBRISTOL'
  UNION ALL SELECT 'DANIEL SCARLETT', 'DANIEL SCARLETT', 'GB', 'GB-ZIEGLERCOLNBROOK'
  UNION ALL SELECT 'JAKE BROWN', 'JAKE BROWN', 'GB', 'GB-ZIEGLERCOLNBROOK'
  UNION ALL SELECT 'PETER BARKER', 'PETER BARKER', 'GB', 'GB-ZIEGLERCOLNBROOK'
  UNION ALL SELECT 'RYAN HERBERT', 'RYAN HERBERT', 'GB', 'GB-ZIEGLERCOLNBROOK'
  UNION ALL SELECT 'SAMANTHA GIBBON', 'SAMANTHA GIBBON', 'GB', 'GB-ZIEGLERCOLNBROOK'
  UNION ALL SELECT 'STEFANO SEU', 'STEFANO SEU', 'GB', 'GB-ZIEGLERCOLNBROOK'
  UNION ALL SELECT 'STEWART BROOK', 'STEWART BROOK', 'GB', 'GB-ZIEGLERCOLNBROOK'
  UNION ALL SELECT 'HOLLY HADDEN', 'HOLLY HADDEN', 'GB', 'GB-ZIEGLERDURHAM'
  UNION ALL SELECT 'JAMES SMITH', 'JAMES SMITH', 'GB', 'GB-ZIEGLERDURHAM'
  UNION ALL SELECT 'KELLY BRYSON', 'KELLY BRYSON', 'GB', 'GB-ZIEGLERDURHAM'
  UNION ALL SELECT 'ALISON WALKER', 'ALISON WALKER', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'DANNY MOTT', 'DANNY MOTT', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'JAMES MAFFEY', 'JAMES MAFFEY', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'JON CLAY', 'JON CLAY', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'KARNIE CHEUNG', 'KARNIE CHEUNG', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'KATE FLYNN', 'KATE FLYNN', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'KEVIN WALKER', 'KEVIN WALKER', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'LINDA FARROW', 'LINDA FARROW', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'MICHELE RICHARDSON', 'MICHELE RICHARDSON', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'SARAH OMALEY', 'SARAH OMALEY', 'GB', 'GB-ZIEGLERFELIXSTOWE'
  UNION ALL SELECT 'ANDREW JONES', 'ANDREW JONES', 'GB', 'GB-ZIEGLERHEATHROW'
  UNION ALL SELECT 'ANDY ROBERTSON', 'ANDY ROBERTSON', 'GB', 'GB-ZIEGLERHEATHROW'
  UNION ALL SELECT 'JOSH WINN', 'JOSH WINN', 'GB', 'GB-ZIEGLERHEATHROW'
  UNION ALL SELECT 'JOHN WOODS', 'JOHN WOODS', 'GB', 'GB-ZIEGLERMANCHESTER'
  UNION ALL SELECT 'AARON BREWER', 'AARON BREWER', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'CARON PAYNE', 'CARON PAYNE', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'CHRIS LACEY', 'CHRIS LACEY', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'CRAIG WILLIAMS', 'CRAIG WILLIAMS', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'IAN MATTHEWS', 'IAN MATTHEWS', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'JONATHON EDWARDS', 'JONATHON EDWARDS', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'LUCY BUXTON', 'LUCY BUXTON', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'MATTHEW DAVIES', 'MATTHEW DAVIES', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'MATTHEW EVANS', 'MATTHEW EVANS', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'PAUL CONLON', 'PAUL CONLON', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'STEVE SEWARD', 'STEVE SEWARD', 'GB', 'GB-ZIEGLERNEWPORT'
  UNION ALL SELECT 'GARY  MURRAY', 'GARY  MURRAY', 'GB', 'GB-ZIEGLERNORTHAMPTON'
  UNION ALL SELECT 'SAMUEL GARDNER', 'SAMUEL GARDNER', 'GB', 'GB-ZIEGLERNORTHAMPTON'
  UNION ALL SELECT 'SAMUEL NICKLIN', 'SAMUEL NICKLIN', 'GB', 'GB-ZIEGLERNORTHAMPTON'
  UNION ALL SELECT 'CARYS SHEARS', 'CARYS SHEARS', 'GB', 'GB-ZIEGLERPORTSMOUTH'
  UNION ALL SELECT 'ELIN WESTLAKE JONES', 'ELIN WESTLAKE JONES', 'GB', 'GB-ZIEGLERPORTSMOUTH'
  UNION ALL SELECT 'JAMES RAVENHALL', 'JAMES RAVENHALL', 'GB', 'GB-ZIEGLERPORTSMOUTH'
  UNION ALL SELECT 'MICHAEL GILL', 'MICHAEL GILL', 'GB', 'GB-ZIEGLERPORTSMOUTH'
  UNION ALL SELECT 'NIKOLAJ DELRIVO', 'NIKOLAJ DELRIVO', 'GB', 'GB-ZIEGLERPORTSMOUTH'
  UNION ALL SELECT 'ANDY DOMVILLE', 'ANDY DOMVILLE', 'GB', 'GB-ZIEGLERWARRINGTON'
  UNION ALL SELECT 'DANIELLE TOOLE', 'DANIELLE TOOLE', 'GB', 'GB-ZIEGLERWARRINGTON'
  UNION ALL SELECT 'DIANE BOSTOCK', 'DIANE BOSTOCK', 'GB', 'GB-ZIEGLERWARRINGTON'
  UNION ALL SELECT 'DIANE CONWAY', 'DIANE CONWAY', 'GB', 'GB-ZIEGLERWARRINGTON'
  UNION ALL SELECT 'JAMES WILKINSON', 'JAMES WILKINSON', 'GB', 'GB-ZIEGLERWARRINGTON'
  UNION ALL SELECT 'LYNDSEY GARGAN', 'LYNDSEY GARGAN', 'GB', 'GB-ZIEGLERWARRINGTON'
  UNION ALL SELECT 'NICK EVANS', 'NICK EVANS', 'GB', 'GB-ZIEGLERWARRINGTON'
  UNION ALL SELECT 'PAUL RIDGERS', 'PAUL RIDGERS', 'GB', 'GB-ZIEGLERWARRINGTON'
  UNION ALL SELECT 'MARIA FOTI', 'MARIA FOTI', 'GR', 'GR-ZIEGLERGREECE'
  UNION ALL SELECT 'STEFANOS KOUFAKIS', 'STEFANOS KOUFAKIS', 'GR', 'GR-ZIEGLERGREECE'
  UNION ALL SELECT 'BIEN ELHARIRI ESSAMLALI', 'BIEN ELHARIRI ESSAMLALI', 'MA', 'MA-ZIEGLERMOROCCO'
  UNION ALL SELECT 'ELMEHDI BELALIA', 'ELMEHDI BELALIA', 'MA', 'MA-ZIEGLERMOROCCO'
  UNION ALL SELECT 'FATIMA EZZAHRA OUARSANA', 'FATIMA EZZAHRA OUARSANA', 'MA', 'MA-ZIEGLERMOROCCO'
  UNION ALL SELECT 'HAJAR EL HARIRI ESSAMLALI', 'HAJAR EL HARIRI ESSAMLALI', 'MA', 'MA-ZIEGLERMOROCCO'
  UNION ALL SELECT 'HOUDA SBAI LDRISSI', 'HOUDA SBAI LDRISSI', 'MA', 'MA-ZIEGLERMOROCCO'
  UNION ALL SELECT 'JIHANE BAGHDADI', 'JIHANE BAGHDADI', 'MA', 'MA-ZIEGLERMOROCCO'
  UNION ALL SELECT 'LAHLALI SAIF', 'LAHLALI SAIF', 'MA', 'MA-ZIEGLERMOROCCO'
  UNION ALL SELECT 'MYLENE DELORME', 'MYLENE DELORME', 'MA', 'MA-ZIEGLERMOROCCO'
  UNION ALL SELECT 'SANAA ELOUADI', 'SANAA ELOUADI', 'MA', 'MA-ZIEGLERMOROCCO'
  UNION ALL SELECT 'AB AHSAINI', 'AB AHSAINI', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'ADRIANA WESTERHOF', 'ADRIANA WESTERHOF', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'ALI CABUK', 'ALI CABUK', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'DYLAN', 'DYLAN', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'FRANK SPEIJER', 'FRANK SPEIJER', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'HAMZA EL BAKKALI', 'HAMZA EL BAKKALI', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'INES GROL', 'INES GROL', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'JACO MEIJER', 'JACO MEIJER', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'JACO VAN DIJK', 'JACO VAN DIJK', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'KARIMA TIJAMI', 'KARIMA TIJAMI', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'KELLY OGBEIDE', 'KELLY OGBEIDE', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'LENNOX TWUMASI', 'LENNOX TWUMASI', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'MELANIE COX', 'MELANIE COX', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'MET VRIENDELIJKE GROET', 'MET VRIENDELIJKE GROET', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'PASCAL', 'PASCAL', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'PASCAL VAN DER SPEK', 'PASCAL VAN DER SPEK', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'REMCO', 'REMCO', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'REMCO STOFFELS', 'REMCO STOFFELS', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'RUŽICA TUBIN', 'RUŽICA TUBIN', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'SALES TEAM', 'SALES TEAM', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'TACO MEIJER', 'TACO MEIJER', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'TARA DJORAI', 'TARA DJORAI', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'THIJS VAN DER STELT', 'THIJS VAN DER STELT', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'VIRGIL SIWALETTE', 'VIRGIL SIWALETTE', 'NL', 'NL-ZIEGLERNETHERLANDS'
  UNION ALL SELECT 'KATHY LIU', 'KATHY LIU', 'OT', 'OT-AMARIMETALSCHINA'
  UNION ALL SELECT 'MICHAEL CHEUNG', 'MICHAEL CHEUNG', 'OT', 'OT-ATLANTICALCHKLIMITED'
  UNION ALL SELECT 'WINKY WONG', 'WINKY WONG', 'OT', 'OT-ATLANTICALCHKLIMITED'
  UNION ALL SELECT 'JANET', 'JANET', 'OT', 'OT-EC4ULIMITED'
  UNION ALL SELECT 'MATEUS LIMA PEIXOTO', 'MATEUS LIMA PEIXOTO', 'OT', 'OT-GRUPOVSANTOS'
  UNION ALL SELECT 'HUIMIN WU', 'HUIMIN WU', 'OT', 'OT-GUANGHZOUSOURCING'
  UNION ALL SELECT 'IVY HUANG', 'IVY HUANG', 'OT', 'OT-HONGKONGHOYOGO'
  UNION ALL SELECT 'SEVEN ZHONG', 'SEVEN ZHONG', 'OT', 'OT-JABEZFURNITURE'
  UNION ALL SELECT 'CARRIE FENG', 'CARRIE FENG', 'OT', 'OT-SHANDONGJULIALUMINIUM'
  UNION ALL SELECT 'TUAN ANH', 'TUAN ANH', 'OT', 'OT-TAMANHTRADING'
  UNION ALL SELECT 'PASCAL LAROUMANIE', 'PASCAL LAROUMANIE', 'OT', 'OT-TREMAIL'
  UNION ALL SELECT 'RAFAL ADAMCZEWSKI', 'RAFAL ADAMCZEWSKI', 'PL', 'PL-ZIEGLERPOLAND'
  UNION ALL SELECT 'ABBY HUANG', 'ABBY HUANG', 'TB', 'TB-TBA'
  UNION ALL SELECT 'ADITHYA RANJITH', 'ADITHYA RANJITH', 'TB', 'TB-TBA'
  UNION ALL SELECT 'ARIELA', 'ARIELA', 'TB', 'TB-TBA'
  UNION ALL SELECT 'ASAD ISLAM', 'ASAD ISLAM', 'TB', 'TB-TBA'
  UNION ALL SELECT 'DIANA PAOLA CIRO GIRALDO', 'DIANA PAOLA CIRO GIRALDO', 'TB', 'TB-TBA'
  UNION ALL SELECT 'FADY ABIKARAM', 'FADY ABIKARAM', 'TB', 'TB-TBA'
  UNION ALL SELECT 'HARRISON', 'HARRISON', 'TB', 'TB-TBA'
  UNION ALL SELECT 'HELEEMA ASIF', 'HELEEMA ASIF', 'TB', 'TB-TBA'
  UNION ALL SELECT 'ILKER', 'ILKER', 'TB', 'TB-TBA'
  UNION ALL SELECT 'IRENE WONG', 'IRENE WONG', 'TB', 'TB-TBA'
  UNION ALL SELECT 'KC HO', 'KC HO', 'TB', 'TB-TBA'
  UNION ALL SELECT 'LARRY LAMAS', 'LARRY LAMAS', 'TB', 'TB-TBA'
  UNION ALL SELECT 'LEE TYRER', 'LEE TYRER', 'TB', 'TB-TBA'
  UNION ALL SELECT 'LIKER USTUNDAG', 'LIKER USTUNDAG', 'TB', 'TB-TBA'
  UNION ALL SELECT 'PRAJWOL AMATYA', 'PRAJWOL AMATYA', 'TB', 'TB-TBA'
  UNION ALL SELECT 'R SURESH', 'R SURESH', 'TB', 'TB-TBA'
  UNION ALL SELECT 'RENATO TRUST', 'RENATO TRUST', 'TB', 'TB-TBA'
  UNION ALL SELECT 'SA REHMAN', 'SA REHMAN', 'TB', 'TB-TBA'
  UNION ALL SELECT 'SIJY JACOB', 'SIJY JACOB', 'TB', 'TB-TBA'
  UNION ALL SELECT 'AMBER COLES', 'AMBER COLES', 'US', 'US-ZIEGLERUSA'
  UNION ALL SELECT 'JOE ELIZONDO', 'JOE ELIZONDO', 'US', 'US-ZIEGLERUSA'
  UNION ALL SELECT 'AUDREY CONLIN', 'AUDREY CONLIN', 'ZA', 'ZA-'
  UNION ALL SELECT 'ANTHEA WILLIAMS', 'ANTHEA WILLIAMS', 'ZA', 'ZA-ZIEGLERCAPETOWN'
  UNION ALL SELECT 'CHEVONNE ARENDSE', 'CHEVONNE ARENDSE', 'ZA', 'ZA-ZIEGLERCAPETOWN'
  UNION ALL SELECT 'KEATHAN KIEWIET', 'KEATHAN KIEWIET', 'ZA', 'ZA-ZIEGLERCAPETOWN'
  UNION ALL SELECT 'TORIQ DAVIDS', 'TORIQ DAVIDS', 'ZA', 'ZA-ZIEGLERCAPETOWN'
  UNION ALL SELECT 'ZELNA MINNIE', 'ZELNA MINNIE', 'ZA', 'ZA-ZIEGLERCAPETOWN'
  UNION ALL SELECT 'ALEXIS MOGOROSI', 'ALEXIS MOGOROSI', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'ANDRE BERRY', 'ANDRE BERRY', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'ASHNEE CHUNNILALL', 'ASHNEE CHUNNILALL', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'BASIL GEORGILADAKIS', 'BASIL GEORGILADAKIS', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'CAROLINE LESO', 'CAROLINE LESO', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'CRAIG FOX', 'CRAIG FOX', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'CYNTHIA NTINI', 'CYNTHIA NTINI', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'GILLIAN LABUSCHAGNE', 'GILLIAN LABUSCHAGNE', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'ILZE NEETHLING', 'ILZE NEETHLING', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'JESSICA MATLHOGONOLO METSING', 'JESSICA MATLHOGONOLO METSING', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'JYOTHI MAHARAJ', 'JYOTHI MAHARAJ', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'KAYLA DEE ERLANK', 'KAYLA DEE ERLANK', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'KAYLA PRETORIUS', 'KAYLA PRETORIUS', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'KIRSTY PATRICK', 'KIRSTY PATRICK', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'LONWABO MXUMA', 'LONWABO MXUMA', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'LYNTHIA NTINI', 'LYNTHIA NTINI', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'MECALI VAN ROOYEN', 'MECALI VAN ROOYEN', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'MICHELLE MOTHIBA', 'MICHELLE MOTHIBA', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'NOLUTHANDO KHUMALO', 'NOLUTHANDO KHUMALO', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'SIMON KIBI', 'SIMON KIBI', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'STEPHANIE NAIDOO', 'STEPHANIE NAIDOO', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
  UNION ALL SELECT 'TRACY PADAYACHEE', 'TRACY PADAYACHEE', 'ZA', 'ZA-ZIEGLERJOHANNESBURG'
) AS pic_data
INNER JOIN dict_sales_office so ON so.code = pic_data.office_code
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  name_norm = VALUES(name_norm),
  updated_at = CURRENT_TIMESTAMP;

SELECT 'Inserted/updated 735 sales PICs' AS status;

-- ============================================================
-- Step 4: Verify import results
-- ============================================================

SELECT '=== ?摰嗥?霈?===' AS status;
SELECT 
  c.country_code,
  c.country_name_en,
  COUNT(DISTINCT so.id) AS office_count,
  COUNT(DISTINCT sp.id) AS pic_count
FROM country c
LEFT JOIN dict_sales_office so ON so.country_code = c.country_code
LEFT JOIN sales_pic sp ON sp.country_code = c.country_code
WHERE c.country_code IN ('AG', 'BE', 'CN', 'FR', 'DE', 'GR', 'MA', 'NL', 'OT', 'PL', 'ZA', 'CH', 'TB', 'GB', 'US')
GROUP BY c.country_code, c.country_name_en
ORDER BY pic_count DESC;

-- AGENTS 蝷箔??唳
SELECT '=== AGENTS 蝷箔?嚗?10?∴? ===' AS status;
SELECT 
  c.country_name_en AS country,
  so.name AS office,
  sp.name AS pic
FROM sales_pic sp
INNER JOIN dict_sales_office so ON sp.sales_office_id = so.id
INNER JOIN country c ON sp.country_code = c.country_code
WHERE c.country_code = 'AG'
LIMIT 10;

-- FRANCE 蝷箔??唳
SELECT '=== FRANCE 蝷箔?嚗?10?∴? ===' AS status;
SELECT 
  c.country_name_en AS country,
  so.name AS office,
  sp.name AS pic
FROM sales_pic sp
INNER JOIN dict_sales_office so ON sp.sales_office_id = so.id
INNER JOIN country c ON sp.country_code = c.country_code
WHERE c.country_code = 'FR'
LIMIT 10;

SET FOREIGN_KEY_CHECKS = 1;

SELECT '=== Import completed! ===' AS status;
