-- ============================================================
-- Patch SQL: 只补充 List.csv 中缺失的数据
-- 不会影响已存在的数据
-- ============================================================

USE logitrack;
SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

-- ──────────────────────────────────────────────────────────
-- Fix: 修正 AG-PCS2 的 country_code (AGENTS -> AG)
-- ──────────────────────────────────────────────────────────
UPDATE dict_sales_office SET country_code = 'AG', updated_at = CURRENT_TIMESTAMP
WHERE code = 'AG-PCS2' AND country_code = 'AGENTS';

-- ──────────────────────────────────────────────────────────
-- Step 1: 插入缺失国家 (1 个)
-- ──────────────────────────────────────────────────────────
INSERT INTO country (country_code, country_name_en, country_name_cn, is_active, is_core) VALUES
  ('GB', 'United Kingdom', 'United Kingdom', 1, 1)
ON DUPLICATE KEY UPDATE
  country_name_en = VALUES(country_name_en),
  country_name_cn = VALUES(country_name_cn),
  updated_at = CURRENT_TIMESTAMP;
SELECT 'Inserted 1 missing countries' AS status;

-- ──────────────────────────────────────────────────────────
-- Step 2: 插入缺失办公室 (1 个)
-- ──────────────────────────────────────────────────────────
INSERT INTO dict_sales_office (code, name, name_norm, country_code, is_active, sort_order) VALUES
  ('AG-TAMANHTRADING', 'TAM ANH TRADING', 'TAM ANH TRADING (AG)', 'AG', 1, 10)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  name_norm = VALUES(name_norm),
  country_code = VALUES(country_code),
  updated_at = CURRENT_TIMESTAMP;
SELECT 'Inserted 1 missing offices' AS status;

-- ──────────────────────────────────────────────────────────
-- Step 3: 插入缺失 PIC (229 个)
-- ──────────────────────────────────────────────────────────
INSERT INTO sales_pic (name, name_norm, country_code, sales_office_id, is_active)
SELECT pic_data.name, pic_data.name_norm, pic_data.country_code, so.id, 1
FROM (
  SELECT 'SHAHEBAZ KHAN' AS name, 'SHAHEBAZ KHAN' AS name_norm, 'AG' AS country_code, 'AG-AI' AS office_code
  UNION ALL SELECT 'LAIBA ARSHAD ALI', 'LAIBA ARSHAD ALI', 'AG', 'AG-AL'
  UNION ALL SELECT 'KARUNA BHATE', 'KARUNA BHATE', 'AG', 'AG-AGL'
  UNION ALL SELECT 'MAYUR', 'MAYUR', 'AG', 'AG-AGL'
  UNION ALL SELECT 'RUPALI DESHMUKH', 'RUPALI DESHMUKH', 'AG', 'AG-AGL'
  UNION ALL SELECT 'SERGIO BUSTAMANTE', 'SERGIO BUSTAMANTE', 'AG', 'AG-AC'
  UNION ALL SELECT 'BURCU DÜZDAŞ', 'BURCU DÜZDAŞ', 'AG', 'AG-ATS'
  UNION ALL SELECT 'EMIR SOYSAL', 'EMIR SOYSAL', 'AG', 'AG-ATS'
  UNION ALL SELECT 'SINAN SENER', 'SINAN SENER', 'AG', 'AG-BB'
  UNION ALL SELECT 'DINO SKRIJELJ', 'DINO SKRIJELJ', 'AG', 'AG-BT'
  UNION ALL SELECT 'GAYLIN FERRIER', 'GAYLIN FERRIER', 'AG', 'AG-BP'
  UNION ALL SELECT 'BAN NGUYEN', 'BAN NGUYEN', 'AG', 'AG-BI'
  UNION ALL SELECT 'JOE CHAN', 'JOE CHAN', 'AG', 'AG-BI'
  UNION ALL SELECT 'LAURA SCULL', 'LAURA SCULL', 'AG', 'AG-BI'
  UNION ALL SELECT 'NICOLA SCULL', 'NICOLA SCULL', 'AG', 'AG-BI'
  UNION ALL SELECT 'RACHAEL PLUMB', 'RACHAEL PLUMB', 'AG', 'AG-BI'
  UNION ALL SELECT 'VAN NGUYEN', 'VAN NGUYEN', 'AG', 'AG-BI'
  UNION ALL SELECT 'VAN THANH NGUYEN', 'VAN THANH NGUYEN', 'AG', 'AG-BI'
  UNION ALL SELECT 'GIOVANNI PIMENTEL', 'GIOVANNI PIMENTEL', 'AG', 'AG-BE'
  UNION ALL SELECT 'VINÍCIUS BLAU', 'VINÍCIUS BLAU', 'AG', 'AG-BE'
  UNION ALL SELECT 'GIGI LIU', 'GIGI LIU', 'AG', 'AG-CL'
  UNION ALL SELECT 'DAN ULEIA', 'DAN ULEIA', 'AG', 'AG-CC'
  UNION ALL SELECT 'LESLIE ESPINOZA', 'LESLIE ESPINOZA', 'AG', 'AG-CL2'
  UNION ALL SELECT 'XUKA', 'XUKA', 'AG', 'AG-CL3'
  UNION ALL SELECT 'MOHAMMAD AHMED SHEIKH', 'MOHAMMAD AHMED SHEIKH', 'AG', 'AG-CFI2'
  UNION ALL SELECT 'CHUNGTAI', 'CHUNGTAI', 'AG', 'AG-CZ'
  UNION ALL SELECT 'ADRIANA CASALLAS PENA', 'ADRIANA CASALLAS PENA', 'AG', 'AG-CA'
  UNION ALL SELECT 'CHRISTINE KNUTH', 'CHRISTINE KNUTH', 'AG', 'AG-DACOTRAN'
  UNION ALL SELECT 'FANNY HUANG', 'FANNY HUANG', 'AG', 'AG-DDSL'
  UNION ALL SELECT 'JENNY DONG', 'JENNY DONG', 'AG', 'AG-DG'
  UNION ALL SELECT 'MAXIM EVTUSHENKO', 'MAXIM EVTUSHENKO', 'AG', 'AG-DH'
  UNION ALL SELECT 'HINSON', 'HINSON', 'AG', 'AG-DS'
  UNION ALL SELECT 'CESAR MOLINA', 'CESAR MOLINA', 'AG', 'AG-EB'
  UNION ALL SELECT 'MARKK CUCEK', 'MARKK CUCEK', 'AG', 'AG-EGL'
  UNION ALL SELECT 'SYED WASI IMRAN', 'SYED WASI IMRAN', 'AG', 'AG-EFS'
  UNION ALL SELECT 'PINTU DATTA', 'PINTU DATTA', 'AG', 'AG-FS&L'
  UNION ALL SELECT 'PULAK DATTA', 'PULAK DATTA', 'AG', 'AG-FS&L'
  UNION ALL SELECT 'RENNY', 'RENNY', 'AG', 'AG-FL'
  UNION ALL SELECT 'SONYA THELMA', 'SONYA THELMA', 'AG', 'AG-FL'
  UNION ALL SELECT 'AAZMA SIDDIQUI', 'AAZMA SIDDIQUI', 'AG', 'AG-FL3'
  UNION ALL SELECT 'ELLA GU', 'ELLA GU', 'AG', 'AG-FSG'
  UNION ALL SELECT 'FRED LUAHA', 'FRED LUAHA', 'AG', 'AG-FL2'
  UNION ALL SELECT 'JASMIN AHMED', 'JASMIN AHMED', 'AG', 'AG-FS'
  UNION ALL SELECT 'MENNA-TULLAH NABIL', 'MENNA-TULLAH NABIL', 'AG', 'AG-FS'
  UNION ALL SELECT 'MOHAMED GAWEESH', 'MOHAMED GAWEESH', 'AG', 'AG-FS'
  UNION ALL SELECT 'MS. JASMIN AHMED', 'MS. JASMIN AHMED', 'AG', 'AG-FS'
  UNION ALL SELECT 'RUPALI TARACHAND', 'RUPALI TARACHAND', 'AG', 'AG-FREIGHTL'
  UNION ALL SELECT 'CAROL MWANGI', 'CAROL MWANGI', 'AG', 'AG-FGS'
  UNION ALL SELECT 'EMMANUEL', 'EMMANUEL', 'AG', 'AG-FGS'
  UNION ALL SELECT 'EMMANUEL CHUMBA', 'EMMANUEL CHUMBA', 'AG', 'AG-FGS'
  UNION ALL SELECT 'HELLEN KYALO', 'HELLEN KYALO', 'AG', 'AG-FGS'
  UNION ALL SELECT 'SHELLY SHIMON', 'SHELLY SHIMON', 'AG', 'AG-FRIDENSO'
  UNION ALL SELECT 'TAL LEVY', 'TAL LEVY', 'AG', 'AG-FRIDENSO'
  UNION ALL SELECT 'JOE WANG', 'JOE WANG', 'AG', 'AG-GC'
  UNION ALL SELECT 'DORA CHANG', 'DORA CHANG', 'AG', 'AG-GMC'
  UNION ALL SELECT 'ABIDJAH KAGUONGO', 'ABIDJAH KAGUONGO', 'AG', 'AG-GL'
  UNION ALL SELECT 'CYNTHIA BUJULA', 'CYNTHIA BUJULA', 'AG', 'AG-GL'
  UNION ALL SELECT 'ESTHER ABIGAEL KIMANI', 'ESTHER ABIGAEL KIMANI', 'AG', 'AG-GL'
  UNION ALL SELECT 'RACHEAL MARTHA ATOO', 'RACHEAL MARTHA ATOO', 'AG', 'AG-GL'
  UNION ALL SELECT 'SHARON OJUNJU', 'SHARON OJUNJU', 'AG', 'AG-GL'
  UNION ALL SELECT 'THUSHARA PRIYADHARSHANA', 'THUSHARA PRIYADHARSHANA', 'AG', 'AG-GL'
  UNION ALL SELECT 'OSEN ARABOGA', 'OSEN ARABOGA', 'AG', 'AG-GT'
  UNION ALL SELECT 'YUSUF YAZIRLIOGLU', 'YUSUF YAZIRLIOGLU', 'AG', 'AG-GT'
  UNION ALL SELECT 'ROOPA SHRISHAR', 'ROOPA SHRISHAR', 'AG', 'AG-GFSC'
  UNION ALL SELECT 'SPYROS ZAFEIRIS', 'SPYROS ZAFEIRIS', 'AG', 'AG-GH'
  UNION ALL SELECT 'BANSI AHARI', 'BANSI AHARI', 'AG', 'AG-GL2'
  UNION ALL SELECT 'JAYDEV OZA', 'JAYDEV OZA', 'AG', 'AG-GL2'
  UNION ALL SELECT 'ANNE CHANG', 'ANNE CHANG', 'AG', 'AG-GT2'
  UNION ALL SELECT 'JOAN LIN', 'JOAN LIN', 'AG', 'AG-GT2'
  UNION ALL SELECT 'MANDY LIN', 'MANDY LIN', 'AG', 'AG-GT2'
  UNION ALL SELECT 'VESTA WANG', 'VESTA WANG', 'AG', 'AG-GT2'
  UNION ALL SELECT 'J.XIN.Y', 'J.XIN.Y', 'AG', 'AG-GD'
  UNION ALL SELECT 'GABRIEL MANRIQUE', 'GABRIEL MANRIQUE', 'AG', 'AG-GB'
  UNION ALL SELECT 'GIANNA TESTA', 'GIANNA TESTA', 'AG', 'AG-GS'
  UNION ALL SELECT 'LIZ', 'LIZ', 'AG', 'AG-GMT'
  UNION ALL SELECT 'SNEHA SAAMPAT', 'SNEHA SAAMPAT', 'AG', 'AG-GAC'
  UNION ALL SELECT 'NATALYA EROKHINA', 'NATALYA EROKHINA', 'AG', 'AG-GMG'
  UNION ALL SELECT 'JOPHY LAM', 'JOPHY LAM', 'AG', 'AG-HML'
  UNION ALL SELECT 'WINDY MAO', 'WINDY MAO', 'AG', 'AG-HFS'
  UNION ALL SELECT 'KEILAH CHAO', 'KEILAH CHAO', 'AG', 'AG-HFSG'
  UNION ALL SELECT 'MIKO DONG', 'MIKO DONG', 'AG', 'AG-HFSG'
  UNION ALL SELECT 'SANDRA', 'SANDRA', 'AG', 'AG-HBI'
  UNION ALL SELECT 'LATHA', 'LATHA', 'AG', 'AG-HL'
  UNION ALL SELECT 'SRIDHAR BABU', 'SRIDHAR BABU', 'AG', 'AG-HL'
  UNION ALL SELECT 'NOHA MOUSTAFA', 'NOHA MOUSTAFA', 'AG', 'AG-INCOTRAN'
  UNION ALL SELECT 'RANDA SABER', 'RANDA SABER', 'AG', 'AG-INCOTRAN'
  UNION ALL SELECT 'ANTON ELOFSSON', 'ANTON ELOFSSON', 'AG', 'AG-ITS'
  UNION ALL SELECT 'FACUNDO CUELLO', 'FACUNDO CUELLO', 'AG', 'AG-INTERBOR'
  UNION ALL SELECT 'GABI AVNI', 'GABI AVNI', 'AG', 'AG-IC'
  UNION ALL SELECT 'KELLY SHUKRON', 'KELLY SHUKRON', 'AG', 'AG-IC'
  UNION ALL SELECT 'LANICE FERNANDES', 'LANICE FERNANDES', 'AG', 'AG-KLB'
  UNION ALL SELECT 'ADOLPHE MARRACHE', 'ADOLPHE MARRACHE', 'AG', 'AG-KT'
  UNION ALL SELECT 'JOSEPH', 'JOSEPH', 'AG', 'AG-KS'
  UNION ALL SELECT 'KARINA BORGES', 'KARINA BORGES', 'AG', 'AG-KS2'
  UNION ALL SELECT 'MS. DENIZ AKSOY', 'MS. DENIZ AKSOY', 'AG', 'AG-LW'
  UNION ALL SELECT 'KUTAL TASKAYA', 'KUTAL TASKAYA', 'AG', 'AG-LU'
  UNION ALL SELECT 'ANITHA', 'ANITHA', 'AG', 'AG-LL'
  UNION ALL SELECT 'DIVYA CHAUDHARY', 'DIVYA CHAUDHARY', 'AG', 'AG-LL'
  UNION ALL SELECT 'E ATMARAM', 'E ATMARAM', 'AG', 'AG-LL'
  UNION ALL SELECT 'E. RANI', 'E. RANI', 'AG', 'AG-LL'
  UNION ALL SELECT 'K.ANITHA', 'K.ANITHA', 'AG', 'AG-LL'
  UNION ALL SELECT 'RAKESH G', 'RAKESH G', 'AG', 'AG-LL'
  UNION ALL SELECT 'SATYAJIT DAS', 'SATYAJIT DAS', 'AG', 'AG-LL'
  UNION ALL SELECT 'VINNY P. KUMAR', 'VINNY P. KUMAR', 'AG', 'AG-LL'
  UNION ALL SELECT 'EMAD ALADEM', 'EMAD ALADEM', 'AG', 'AG-LP'
  UNION ALL SELECT 'M. ZAHID', 'M. ZAHID', 'AG', 'AG-LSP'
  UNION ALL SELECT 'AYSENUR KABADAYI', 'AYSENUR KABADAYI', 'AG', 'AG-LOGIWORK'
  UNION ALL SELECT 'VINNI VARGHESE', 'VINNI VARGHESE', 'AG', 'AG-LS'
  UNION ALL SELECT 'GILBERT WANG', 'GILBERT WANG', 'AG', 'AG-LGL'
  UNION ALL SELECT 'MARY D''SOUZA', 'MARY D''SOUZA', 'AG', 'AG-MS'
  UNION ALL SELECT 'SHAYIL IRSHAD', 'SHAYIL IRSHAD', 'AG', 'AG-MS'
  UNION ALL SELECT 'TESNY THOMAS', 'TESNY THOMAS', 'AG', 'AG-MS'
  UNION ALL SELECT 'MICHELLE LAM', 'MICHELLE LAM', 'AG', 'AG-MA'
  UNION ALL SELECT 'ALEJANDRA GONZALEZ', 'ALEJANDRA GONZALEZ', 'AG', 'AG-MG'
  UNION ALL SELECT 'SANJAY TALAISA', 'SANJAY TALAISA', 'AG', 'AG-ML'
  UNION ALL SELECT 'SURESH', 'SURESH', 'AG', 'AG-MV'
  UNION ALL SELECT 'BHAJAN VINODKUMAR', 'BHAJAN VINODKUMAR', 'AG', 'AG-MMFS'
  UNION ALL SELECT 'GLENDA SAKAITIS', 'GLENDA SAKAITIS', 'AG', 'AG-NNC'
  UNION ALL SELECT 'GWEN AREVALO', 'GWEN AREVALO', 'AG', 'AG-NNC'
  UNION ALL SELECT 'JENNIFER HALE SANDERS', 'JENNIFER HALE SANDERS', 'AG', 'AG-NNC'
  UNION ALL SELECT 'JENNIFER HALE-SANDERS', 'JENNIFER HALE-SANDERS', 'AG', 'AG-NNC'
  UNION ALL SELECT 'KIM EDMUNSON', 'KIM EDMUNSON', 'AG', 'AG-NNC'
  UNION ALL SELECT 'MELISSA CAMPBELL', 'MELISSA CAMPBELL', 'AG', 'AG-NNC'
  UNION ALL SELECT 'NHI NGUY', 'NHI NGUY', 'AG', 'AG-NNC'
  UNION ALL SELECT 'RINA PRICE', 'RINA PRICE', 'AG', 'AG-NNC'
  UNION ALL SELECT 'SHEFALI PANCHAL', 'SHEFALI PANCHAL', 'AG', 'AG-NNC'
  UNION ALL SELECT 'TRACIE SILVER-WILSON', 'TRACIE SILVER-WILSON', 'AG', 'AG-NNC'
  UNION ALL SELECT 'VEENA ABRAHAM', 'VEENA ABRAHAM', 'AG', 'AG-NNC'
  UNION ALL SELECT 'RICARDO VILA', 'RICARDO VILA', 'AG', 'AG-NL'
  UNION ALL SELECT 'SHAHNAS PN', 'SHAHNAS PN', 'AG', 'AG-OL'
  UNION ALL SELECT 'CRYSTAL LABORTE', 'CRYSTAL LABORTE', 'AG', 'AG-OT'
  UNION ALL SELECT 'LUZEL LANUZO', 'LUZEL LANUZO', 'AG', 'AG-OT'
  UNION ALL SELECT 'NEIL TAYLOR M.', 'NEIL TAYLOR M.', 'AG', 'AG-PAL'
  UNION ALL SELECT 'ARPITA', 'ARPITA', 'AG', 'AG-PO'
  UNION ALL SELECT 'HALEEMA ASIF', 'HALEEMA ASIF', 'AG', 'AG-PCS'
  UNION ALL SELECT 'MUHAMMAD NAEEM', 'MUHAMMAD NAEEM', 'AG', 'AG-PCS'
  UNION ALL SELECT 'MUHAMMAD USMAN UL HAQ', 'MUHAMMAD USMAN UL HAQ', 'AG', 'AG-PCS'
  UNION ALL SELECT 'DYLAN TAYLOR', 'DYLAN TAYLOR', 'AG', 'AG-PL'
  UNION ALL SELECT 'CHRISTA', 'CHRISTA', 'AG', 'AG-PI'
  UNION ALL SELECT 'HAMID MUMTAZ', 'HAMID MUMTAZ', 'AG', 'AG-PCS2'
  UNION ALL SELECT 'IMRAN KHAN', 'IMRAN KHAN', 'AG', 'AG-PCS2'
  UNION ALL SELECT 'MUHAMMAD', 'MUHAMMAD', 'AG', 'AG-PCS2'
  UNION ALL SELECT 'ERIC TRUC', 'ERIC TRUC', 'AG', 'AG-PO2'
  UNION ALL SELECT 'ZIPPI ZIMMERMAN', 'ZIPPI ZIMMERMAN', 'AG', 'AG-PLL'
  UNION ALL SELECT 'ZEINA HAMED', 'ZEINA HAMED', 'AG', 'AG-PREMIUM-'
  UNION ALL SELECT 'DINI', 'DINI', 'AG', 'AG-PF'
  UNION ALL SELECT 'DINI YANRIANI', 'DINI YANRIANI', 'AG', 'AG-PF'
  UNION ALL SELECT 'HARRISON TAMPUBOLON', 'HARRISON TAMPUBOLON', 'AG', 'AG-PF'
  UNION ALL SELECT 'RENNNY LUBIS', 'RENNNY LUBIS', 'AG', 'AG-PF'
  UNION ALL SELECT 'ANGGIE', 'ANGGIE', 'AG', 'AG-PSI'
  UNION ALL SELECT 'DIOFALDO D ARDHANA', 'DIOFALDO D ARDHANA', 'AG', 'AG-PSI'
  UNION ALL SELECT 'SARAH F LIANDAR', 'SARAH F LIANDAR', 'AG', 'AG-PSI'
  UNION ALL SELECT 'LIELA MONICA', 'LIELA MONICA', 'AG', 'AG-PMAM'
  UNION ALL SELECT 'GITA MAULINDA', 'GITA MAULINDA', 'AG', 'AG-PS'
  UNION ALL SELECT 'MARIAN PARK', 'MARIAN PARK', 'AG', 'AG-PS'
  UNION ALL SELECT 'RACHAEL MARTHA ATOO', 'RACHAEL MARTHA ATOO', 'AG', 'AG-RMA'
  UNION ALL SELECT 'QIUER WU', 'QIUER WU', 'AG', 'AG-RS'
  UNION ALL SELECT 'ASIF HUSSAIN', 'ASIF HUSSAIN', 'AG', 'AG-RI'
  UNION ALL SELECT 'NAVEED', 'NAVEED', 'AG', 'AG-RI'
  UNION ALL SELECT 'UROOJ MEHAR', 'UROOJ MEHAR', 'AG', 'AG-RI'
  UNION ALL SELECT 'ALAA KAMEL', 'ALAA KAMEL', 'AG', 'AG-ST'
  UNION ALL SELECT 'MS. ALAA KAMEL', 'MS. ALAA KAMEL', 'AG', 'AG-ST'
  UNION ALL SELECT 'LILIANA ALFARO ALVAREZ', 'LILIANA ALFARO ALVAREZ', 'AG', 'AG-SL'
  UNION ALL SELECT 'JIHEN SALLEM', 'JIHEN SALLEM', 'AG', 'AG-SG'
  UNION ALL SELECT 'NEDRA BEN SALEM', 'NEDRA BEN SALEM', 'AG', 'AG-SG'
  UNION ALL SELECT 'AKCES', 'AKCES', 'AG', 'AG-SC'
  UNION ALL SELECT 'CESAR AKOU', 'CESAR AKOU', 'AG', 'AG-SC'
  UNION ALL SELECT 'CESAR AYETCHO', 'CESAR AYETCHO', 'AG', 'AG-SC'
  UNION ALL SELECT 'FREDERICK HAGGOO', 'FREDERICK HAGGOO', 'AG', 'AG-SPEEDFRE'
  UNION ALL SELECT 'HARISH BHAGIRATTY', 'HARISH BHAGIRATTY', 'AG', 'AG-SPEEDFRE'
  UNION ALL SELECT 'JUILA WONG', 'JUILA WONG', 'AG', 'AG-SPEEDFRE'
  UNION ALL SELECT 'JULIA WONG', 'JULIA WONG', 'AG', 'AG-SPEEDFRE'
  UNION ALL SELECT 'RUBINA RAMUDU', 'RUBINA RAMUDU', 'AG', 'AG-SPEEDFRE'
  UNION ALL SELECT 'SAROJA PILLAY', 'SAROJA PILLAY', 'AG', 'AG-SPEEDFRE'
  UNION ALL SELECT 'SHANDOSHINI GOVINDEN', 'SHANDOSHINI GOVINDEN', 'AG', 'AG-SPEEDFRE'
  UNION ALL SELECT 'STEFFEN MANZ', 'STEFFEN MANZ', 'AG', 'AG-SPEEDFRE'
  UNION ALL SELECT 'WENDY', 'WENDY', 'AG', 'AG-SPEEDFRE'
  UNION ALL SELECT 'RIZKI SETIAWAN', 'RIZKI SETIAWAN', 'AG', 'AG-SL2'
  UNION ALL SELECT 'DOM MCSPORRAN', 'DOM MCSPORRAN', 'AG', 'AG-SI'
  UNION ALL SELECT 'TUAN ANH (MR.)', 'TUAN ANH (MR.)', 'AG', 'AG-TAMANHTRADING'
  UNION ALL SELECT 'YEN DOAN', 'YEN DOAN', 'AG', 'AG-TAMANHTRADING'
  UNION ALL SELECT 'FAYYAZ GAZIANI', 'FAYYAZ GAZIANI', 'AG', 'AG-TFM'
  UNION ALL SELECT 'TAHIR ALI', 'TAHIR ALI', 'AG', 'AG-TFM'
  UNION ALL SELECT 'ESSAM NOUR EL AWAMRY', 'ESSAM NOUR EL AWAMRY', 'AG', 'AG-TCS'
  UNION ALL SELECT 'GLORIA', 'GLORIA', 'AG', 'AG-TRANSMER'
  UNION ALL SELECT 'NICODEMUS KILONZO', 'NICODEMUS KILONZO', 'AG', 'AG-TRANSMER'
  UNION ALL SELECT 'ASHIK NAZEER', 'ASHIK NAZEER', 'AG', 'AG-UBL'
  UNION ALL SELECT 'ALESSANDRA COMOTTO', 'ALESSANDRA COMOTTO', 'AG', 'AG-UMS'
  UNION ALL SELECT 'ALESSANDRO BUFFA', 'ALESSANDRO BUFFA', 'AG', 'AG-UMS'
  UNION ALL SELECT 'ALESSIO DE NICOLO', 'ALESSIO DE NICOLO', 'AG', 'AG-UMS'
  UNION ALL SELECT 'DAVIDE SCOVERO', 'DAVIDE SCOVERO', 'AG', 'AG-UMS'
  UNION ALL SELECT 'LAURA TORRE', 'LAURA TORRE', 'AG', 'AG-UMS'
  UNION ALL SELECT 'NICOLA CALLERI', 'NICOLA CALLERI', 'AG', 'AG-UMS'
  UNION ALL SELECT 'BIKI', 'BIKI', 'AG', 'AG-VLB'
  UNION ALL SELECT 'BIKIRAN BARUA BIKI', 'BIKIRAN BARUA BIKI', 'AG', 'AG-VLB'
  UNION ALL SELECT 'RUTABA BUTT', 'RUTABA BUTT', 'AG', 'AG-VS('
  UNION ALL SELECT 'GERARD MALCAHY', 'GERARD MALCAHY', 'AG', 'AG-WCA'
  UNION ALL SELECT 'GUSTAVO HENRIQUE CARDOSO', 'GUSTAVO HENRIQUE CARDOSO', 'AG', 'AG-WL'
  UNION ALL SELECT 'AZM SALAH UDDIN CHOWDHURY', 'AZM SALAH UDDIN CHOWDHURY', 'AG', 'AG-WF'
  UNION ALL SELECT 'SALAH UDDIN', 'SALAH UDDIN', 'AG', 'AG-WF'
  UNION ALL SELECT 'JASON', 'JASON', 'AG', 'AG-WJIF'
  UNION ALL SELECT 'FIONA', 'FIONA', 'AG', 'AG-WJI'
  UNION ALL SELECT 'IRIS', 'IRIS', 'AG', 'AG-WJI'
  UNION ALL SELECT 'FILIPPA NICOSIA', 'FILIPPA NICOSIA', 'AG', 'AG-ZA'
  UNION ALL SELECT 'LUC AUDIENS', 'LUC AUDIENS', 'BE', 'BE-ZB'
  UNION ALL SELECT 'WOLF KUSSÉ', 'WOLF KUSSÉ', 'BE', 'BE-ZB'
  UNION ALL SELECT 'JACQUELINE CABRERA', 'JACQUELINE CABRERA', 'DE', 'DE-ZG'
  UNION ALL SELECT 'CÉLINE DESTRUYS', 'CÉLINE DESTRUYS', 'FR', 'FR-ZF'
  UNION ALL SELECT 'JEAN LOUIS LEYRE', 'JEAN LOUIS LEYRE', 'FR', 'FR-ZF'
  UNION ALL SELECT 'JEAN-FRANCOIS PUJOLAS', 'JEAN-FRANCOIS PUJOLAS', 'FR', 'FR-ZF'
  UNION ALL SELECT 'JEMIMA FARATIANA', 'JEMIMA FARATIANA', 'FR', 'FR-ZF'
  UNION ALL SELECT 'KARINE DE SOUSA', 'KARINE DE SOUSA', 'FR', 'FR-ZF'
  UNION ALL SELECT 'NINA - VIRAPHONE SOLIPHANH', 'NINA - VIRAPHONE SOLIPHANH', 'FR', 'FR-ZF'
  UNION ALL SELECT 'SABRINA GRAS', 'SABRINA GRAS', 'FR', 'FR-ZF'
  UNION ALL SELECT 'JON CLAY', 'JON CLAY', 'GB', 'GB-ZF'
  UNION ALL SELECT 'STEVE SEWARD', 'STEVE SEWARD', 'GB', 'GB-ZN'
  UNION ALL SELECT 'GARY  MURRAY', 'GARY  MURRAY', 'GB', 'GB-ZN2'
  UNION ALL SELECT 'CARYS SHEARS', 'CARYS SHEARS', 'GB', 'GB-ZP'
  UNION ALL SELECT 'ELMEHDI BELALIA', 'ELMEHDI BELALIA', 'MA', 'MA-ZM'
  UNION ALL SELECT 'KATHY LIU', 'KATHY LIU', 'OT', 'OT-AMC'
  UNION ALL SELECT 'MICHAEL CHEUNG', 'MICHAEL CHEUNG', 'OT', 'OT-AA(L'
  UNION ALL SELECT 'WINKY WONG', 'WINKY WONG', 'OT', 'OT-AA(L'
  UNION ALL SELECT 'JANET', 'JANET', 'OT', 'OT-EL'
  UNION ALL SELECT 'MATEUS LIMA PEIXOTO', 'MATEUS LIMA PEIXOTO', 'OT', 'OT-GV'
  UNION ALL SELECT 'HUIMIN WU', 'HUIMIN WU', 'OT', 'OT-GS'
  UNION ALL SELECT 'IVY HUANG', 'IVY HUANG', 'OT', 'OT-HKH'
  UNION ALL SELECT 'SEVEN ZHONG', 'SEVEN ZHONG', 'OT', 'OT-JF'
  UNION ALL SELECT 'CARRIE FENG', 'CARRIE FENG', 'OT', 'OT-SJA'
  UNION ALL SELECT 'TUAN ANH', 'TUAN ANH', 'OT', 'AG-TAT'
) AS pic_data
INNER JOIN dict_sales_office so ON so.code = pic_data.office_code
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  name_norm = VALUES(name_norm),
  updated_at = CURRENT_TIMESTAMP;
SELECT 'Inserted 229 missing PICs' AS status;

SET FOREIGN_KEY_CHECKS = 1;

-- ──────────────────────────────────────────────────────────
-- 验证结果
-- ──────────────────────────────────────────────────────────
SELECT c.country_code, c.country_name_en,
  COUNT(DISTINCT so.id) AS offices,
  COUNT(DISTINCT sp.id) AS pics
FROM country c
LEFT JOIN dict_sales_office so ON so.country_code = c.country_code
LEFT JOIN sales_pic sp ON sp.country_code = c.country_code
WHERE c.country_code IN ('AG','BE','CN','FR','DE','GR','MA','NL','OT','PL','ZA','CH','TB','GB','US')
GROUP BY c.country_code, c.country_name_en
ORDER BY pics DESC;