# -*- coding: utf-8 -*-
"""将 List1.csv 数据写入文件并导入数据库"""

import unicodedata, re, mysql.connector, os

# ── 国家映射 ──────────────────────────────────────────────────────────────────
COUNTRY_MAP = {
    'AGENTS': 'AG', 'OTHERS': 'OT', 'TBA': 'TBA',
    'BELGIUM': 'BE', 'CHINA': 'CN', 'FRANCE': 'FR', 'GERMANY': 'DE',
    'GREECE': 'GR', 'MOROCCO': 'MA', 'NETHERLANDS': 'NL', 'POLAND': 'PL',
    'SOUTH_AFRICA': 'ZA', 'SOUTH AFRICA': 'ZA',
    'SWITZERLAND': 'CH', 'UK': 'GB', 'USA': 'US',
}

# ── List1.csv 原始数据（TSV 格式） ────────────────────────────────────────────
RAW = """\
SALESCOUNTRY\tSALESOFFICE\tSALESPIC
AGENTS\tAABITORT\tRAJ KUMAR
AGENTS\tAFS\tMELANIE CASTILLO
AGENTS\tAIRMAX\tGERGELY BARANYAI
AGENTS\tALASR INTERNATIONAL\tSHAHEBAZ KHAN
AGENTS\tALLIED LOGISTICS\tLAIBA ARSHAD ALI
AGENTS\tAMI GLOBAL LOGISTICS\tKARUNA BHATE
AGENTS\tAMI GLOBAL LOGISTICS\tMAYUR
AGENTS\tAMI GLOBAL LOGISTICS\tRUPALI DESHMUKH
AGENTS\tANICAM CARGO\tSERGIO BUSTAMANTE
AGENTS\tAREO\tRAY LIU
AGENTS\tATAT TRANSPORT SOLUTIONS\tBURCU DÜZDAŞ
AGENTS\tATAT TRANSPORT SOLUTIONS\tEMIR SOYSAL
OTHERS\tATLANTIC ALC (HK) LIMITED\tMICHAEL CHEUNG
OTHERS\tATLANTIC ALC (HK) LIMITED\tWINKY WONG
AGENTS\tAUSCORP\tANA JULIA PRADO
AGENTS\tAVIATUR\tLUISA FERNANDA SUAREZ CASALLAS
AGENTS\tBANWARI\tPRAVIN JAISWAR
AGENTS\tBELGO BEARINGS\tSINAN SENER
AGENTS\tBENDIX TRANSPORT\tDINO SKRIJELJ
AGENTS\tBERELAX\tCARLA GREJALVO
AGENTS\tBERELAX\tGISSELLE OCOT
AGENTS\tBERELAX\tKEN ZHANG
AGENTS\tBLUE PLANET\tGAYLIN FERRIER
AGENTS\tBRENDON INTERNATIONAL\tBAN NGUYEN
AGENTS\tBRENDON INTERNATIONAL\tJOE CHAN
AGENTS\tBRENDON INTERNATIONAL\tLAURA SCULL
AGENTS\tBRENDON INTERNATIONAL\tNICOLA SCULL
AGENTS\tBRENDON INTERNATIONAL\tRACHAEL PLUMB
AGENTS\tBRENDON INTERNATIONAL\tVAN NGUYEN
AGENTS\tBRENDON INTERNATIONAL\tVAN THANH NGUYEN
AGENTS\tBRUNIN EXPRESS\tGIOVANNI PIMENTEL
AGENTS\tBRUNIN EXPRESS\tVINÍCIUS BLAU
AGENTS\tCALGARY LOGISTICS\tGIGI LIU
AGENTS\tCARGO CARE\tDAN ULEIA
AGENTS\tCARGOCORP LOGISTICS\tLESLIE ESPINOZA
AGENTS\tCCR\tFERNANDO ARMIJO
AGENTS\tCELERCO\tANDREEA APOSTOL
AGENTS\tCELERCO\tCOSTI COSTACHE
AGENTS\tCELERITY\tNAEEM UDDIN
AGENTS\tCELERITY\tRAMEEZ SARWAR
AGENTS\tCELERITY\tSARFRAZ AHMAD
AGENTS\tCESAR\tAYETCHO
AGENTS\tCFI\tAHMED
AGENTS\tCLKWORLD\tSERAP KARAHUN UZUN
AGENTS\tCMPI LOGISTICS\tXUKA
AGENTS\tCOMBINED FREIGHT INTERNATIONAL\tMOHAMMAD AHMED SHEIKH
AGENTS\tCRAY ZHAO\tCHUNGTAI
AGENTS\tCUSTOMER AGENCY\tADRIANA CASALLAS PENA
AGENTS\tDACOTRANS\tCHRISTINE KNUTH
AGENTS\tDCS DAH STAR LOGISTICS CO.,LTD\tFANNY HUANG
AGENTS\tDEGO GLOBAL\tJENNY DONG
AGENTS\tDESERT HORIZON\tMAXIM EVTUSHENKO
AGENTS\tDUPORT\tMIRANDA
AGENTS\tDYNASTY SHIPPING\tHINSON
AGENTS\tELOG\tDANIELA CARVAJAL
AGENTS\tELOG\tEDUARDO MALDONADO
AGENTS\tELOG\tGEOVANA MOLLINEDO
AGENTS\tELOG\tKATHERINE ANDRADE
AGENTS\tELOG BOLIVIA\tCESAR MOLINA
AGENTS\tELOTRANS\tJEFFERSON JANZEN
AGENTS\tESSERS\tEVA FERRER
AGENTS\tEUROATLA\tMÓNICA ROLDÃO
AGENTS\tEXCEL FREIGHT SYSTEMS\tSYED WASI IMRAN
AGENTS\tFALCON SHIPPING & LOGISTICS\tPINTU DATTA
AGENTS\tFALCON SHIPPING & LOGISTICS\tPULAK DATTA
AGENTS\tFF LOGISTIK\tRENNY
AGENTS\tFF LOGISTIK\tSONYA THELMA
AGENTS\tFIGWAL\tANDRE ALMEIDA
AGENTS\tFIGWAL\tDAVID MAIA
AGENTS\tFIGWAL\tFABIO BADIA
AGENTS\tFIGWAL\tPATRÍCIA MEDEIROS
AGENTS\tFIGWAL\tSONIA SALOMAO
AGENTS\tFIGWAL\tCLANAIR GURGEL
AGENTS\tFIGWAL\tWALTER COSTA
AGENTS\tFIGWAL\tDIEGO DA SILVA
AGENTS\tFLYING SHRIMP GROUP\tELLA GU
AGENTS\tFORWARDAIR LTD\tFRED LUAHA
AGENTS\tFREIGHT SOLUTIONS\tJASMIN AHMED
AGENTS\tFREIGHT SOLUTIONS\tMENNA-TULLAH NABIL
AGENTS\tFREIGHT SOLUTIONS\tMOHAMED GAWEESH
AGENTS\tFREIGHT SOLUTIONS\tMS. JASMIN AHMED
AGENTS\tFREIGHTLINKS\tRUPALI TARACHAND
AGENTS\tFREIGHTWAYS GLOBAL SOLUTIONS\tCAROL MWANGI
AGENTS\tFREIGHTWAYS GLOBAL SOLUTIONS\tEMMANUEL
AGENTS\tFREIGHTWAYS GLOBAL SOLUTIONS\tHELLEN KYALO
AGENTS\tFREIGHTWAYS GLOBAL SOLUTIONS\tEMMANUEL CHUMBA
AGENTS\tFRIDENSON\tTAL LEVY
AGENTS\tFRIDENSON\tSHELLY SHIMON
AGENTS\tGALPER\tRODRIGO MONSALVE SOLAR
AGENTS\tGAME CHANGE\tJOE WANG
AGENTS\tGENERAL MERCHANDISE CONSOLIDATORS\tDORA CHANG
AGENTS\tGEX LOGISTICS\tSHARON OJUNJU
AGENTS\tGEX LOGISTICS\tTHUSHARA PRIYADHARSHANA
AGENTS\tGEX LOGISTICS\tABIDJAH KAGUONGO
AGENTS\tGEX LOGISTICS\tCYNTHIA BUJULA
AGENTS\tGEX LOGISTICS\tESTHER ABIGAEL KIMANI
AGENTS\tGEX LOGISTICS\tRACHEAL MARTHA ATOO
AGENTS\tGEX LOGISTICS\tSHARON OJUNJU 
AGENTS\tGEZAIRI TRANSPORT\tOSEN ARABOGA
AGENTS\tGEZAIRI TRANSPORT\tYUSUF YAZIRLIOGLU
AGENTS\tGHABZE\tTIBOR BALAZS
AGENTS\tGIMEX\tDELIA GOMARA NAVARRO
AGENTS\tGLOBAL HELLENIC\tSPYROS ZAFEIRIS
AGENTS\tGLOBAL LOGISTICS\tBANSI AHARI
AGENTS\tGLOBAL LOGISTICS\tJAYDEV OZA
AGENTS\tGMC TXG\tANNE CHANG
AGENTS\tGMC TXG\tJOAN LIN
AGENTS\tGMC TXG\tMANDY LIN
AGENTS\tGMC TXG\tVESTA WANG
AGENTS\tGOLDEN DRAGON\tJ.XIN.Y
AGENTS\tGOLDLOG BRAZIL\tGABRIEL MANRIQUE
AGENTS\tGORGONI SRL\tGIANNA TESTA
AGENTS\tGSM\tISMAIL NAZAR
AGENTS\tGUANGZHOU MINTONG TRADING\tLIZ
AGENTS\tGULF AGENCY COMPANY\tSNEHA SAAMPAT
AGENTS\tGUNTER MEDICAL GMBH\tNATALYA EROKHINA
AGENTS\tGWL\tCAMILA ALVES
AGENTS\tGWL\tCARLOS BATISTA
AGENTS\tGWL\tGUSTAVO HENRIQUE
AGENTS\tGWL\tMURILO LUIZ
AGENTS\tHARFORD METALWARE LTD.\tJOPHY LAM
AGENTS\tHK FLYING SHRIMP\tWINDY MAO
AGENTS\tHK FLYING SHRIMP GROUP\tKEILAH CHAO
AGENTS\tHK FLYING SHRIMP GROUP\tMIKO DONG
AGENTS\tHOME BEST INTERNATIONAL\tSANDRA
AGENTS\tHTL LOGISTICS\tSRIDHAR BABU
AGENTS\tHTL LOGISTICS\tLATHA
AGENTS\tINCOTRANS\tRANDA SABER
AGENTS\tINCOTRANS\tNOHA MOUSTAFA
AGENTS\tINTERBORDERS\tFACUNDO CUELLO
AGENTS\tINTERGLOBAL CARGO\tKELLY SHUKRON
AGENTS\tINTERGLOBAL CARGO\tGABI AVNI
AGENTS\tISOX\tOLALEKAN OKEBANJO 
AGENTS\tKERRY LOGISTICS BAHRAIN\tLANICE FERNANDES
AGENTS\tKEYSTONE TRADING\tADOLPHE MARRACHE
AGENTS\tKINIFI SOLOPRIMO\tJOSEPH
AGENTS\tKLM\tMINH HA
AGENTS\tKONNECT SHIPPING\tKARINA BORGES
AGENTS\tLAM WORLD\tMS. DENIZ AKSOY
AGENTS\tLEMAN\tDAVID SIMMONS
AGENTS\tLEMAN\tROY PLUSH
AGENTS\tLEMAN\tSUSANA MARTINEZ
AGENTS\tLEMAN\tTRICIA PREESADA
AGENTS\tLEX ULUSLARARASI\tKUTAL TASKAYA
AGENTS\tLOGENIX LOGISTICS\tANITHA
AGENTS\tLOGENIX LOGISTICS\tDIVYA CHAUDHARY
AGENTS\tLOGENIX LOGISTICS\tE ATMARAM
AGENTS\tLOGENIX LOGISTICS\tE. RANI
AGENTS\tLOGENIX LOGISTICS\tK.ANITHA
AGENTS\tLOGENIX LOGISTICS\tRAKESH G
AGENTS\tLOGENIX LOGISTICS\tSATYAJIT DAS
AGENTS\tLOGENIX LOGISTICS\tVINNY P. KUMAR
AGENTS\tLOGISTICS PLUS\tEMAD ALADEM
AGENTS\tLOGISTICS SERVICES PAKISTAN\tM. ZAHID
AGENTS\tLOGIWORKS\tAYSENUR KABADAYI
AGENTS\tLUSTER SHIPPING\tVINNI VARGHESE
AGENTS\tLXC GLOBAL LOGISTICS\tGILBERT WANG
AGENTS\tMAINSTREAM SHIPPING\tMARY D'SOUZA
AGENTS\tMAINSTREAM SHIPPING\tSHAYIL IRSHAD 
AGENTS\tMAINSTREAM SHIPPING\tTESNY THOMAS
AGENTS\tMARIA ASIA\tMICHELLE LAM
AGENTS\tMASTERLINE GROUP\tALEJANDRA GONZALEZ
AGENTS\tMCTC\tLEILA EL ATRI
AGENTS\tMENIL LOGISTICS\tSANJAY TALAISA
AGENTS\tMFS\tBHAJAN
AGENTS\tMFS\tSREEKUTTAN K.P
AGENTS\tMII\tHERI ABDULRACHMAN
AGENTS\tMII\tPRASETYO WIBOWO
AGENTS\tMII\tVICKY W ZAHID
AGENTS\tMII\tDEDE FITRIA
AGENTS\tMII\tDINA
AGENTS\tMII\tDINA NURSANTI
AGENTS\tMII\tDONNY
AGENTS\tMII\tDONNY DHARMAWAN ASSAARIE
AGENTS\tMII\tHERI
AGENTS\tMII\tVICKY
AGENTS\tMII\tNAIMA
AGENTS\tMII\tWIRANJANI ADE
AGENTS\tMODA\tSUBU
AGENTS\tMODA VITTA\tSURESH
AGENTS\tMULTI MODEL FREIGHT SOLUTIONS\tBHAJAN VINODKUMAR
AGENTS\tNEAR NORTH CUSTOMS\tGLENDA SAKAITIS
AGENTS\tNEAR NORTH CUSTOMS\tGWEN AREVALO
AGENTS\tNEAR NORTH CUSTOMS\tJENNIFER HALE-SANDERS
AGENTS\tNEAR NORTH CUSTOMS\tKIM EDMUNSON
AGENTS\tNEAR NORTH CUSTOMS\tMELISSA CAMPBELL
AGENTS\tNEAR NORTH CUSTOMS\tNHI NGUY
AGENTS\tNEAR NORTH CUSTOMS\tRINA PRICE
AGENTS\tNEAR NORTH CUSTOMS\tSHEFALI PANCHAL
AGENTS\tNEAR NORTH CUSTOMS\tTRACIE SILVER-WILSON
AGENTS\tNEAR NORTH CUSTOMS\tVEENA ABRAHAM
AGENTS\tNEAR NORTH CUSTOMS\tJENNIFER HALE SANDERS
AGENTS\tNENACOMEX LOGISTICS\tRICARDO VILA
AGENTS\tOCEAN LINK\tSHAHNAS PN
AGENTS\tON TIME\tCRYSTAL LABORTE
AGENTS\tON TIME\tLUZEL LANUZO
AGENTS\tONWARD\tSHAHAB KHAN
AGENTS\tOSHAIGER\tCRISTALLE LIMJOCO
AGENTS\tOSHAIGER\tJANE MANGARING
AGENTS\tOSHAIGER\tJENZEL MARIE M. NARCISO
AGENTS\tOSHAIGER\tJULIUS CAESAR B. ROQUE
AGENTS\tPACIFIC ANCHOR LINE\tNEIL TAYLOR M.
AGENTS\tPACIFIC OCEAN\tARPITA
AGENTS\tPAKISTAN CARGO SERVICE\tHALEEMA ASIF
AGENTS\tPAKISTAN CARGO SERVICE\tMUHAMMAD NAEEM
AGENTS\tPAKISTAN CARGO SERVICE\tMUHAMMAD USMAN UL HAQ
AGENTS\tPACIFIC ANCHOR LINE\tDYLAN TAYLOR
AGENTS\tPAN INDIA/CHRISTA\tCHRISTA
AGENTS\tPARC\tCYRIL SORDA
AGENTS\tPCS\tHAMID MUMTAZ
AGENTS\tPCS\tIMRAN KHAN
AGENTS\tPCS\tMUHAMMAD
AGENTS\tPHILI ORIENT\tERIC TRUC
AGENTS\tPLASCOW LOGISTICS LTD\tZIPPI ZIMMERMAN
AGENTS\tPREMIUM-PARTNERS\tZEINA HAMED
AGENTS\tPT FIDO\tDINI
AGENTS\tPT FIDO\tDINI YANRIANI
AGENTS\tPT FIDO\tHARRISON TAMPUBOLON
AGENTS\tPT FIDO\tRENNNY LUBIS
AGENTS\tPT SILKARGO INDONESIA\tANGGIE
AGENTS\tPT SILKARGO INDONESIA\tDIOFALDO D ARDHANA
AGENTS\tPT SILKARGO INDONESIA\tSARAH F LIANDAR
AGENTS\tPT. MILITZER AND MUENCH INDONESIA\tLIELA MONICA
AGENTS\tPT. SENATOR\tGITA MAULINDA
AGENTS\tPT. SENATOR\tMARIAN PARK
AGENTS\tQUALITY\tMUDASSAR
AGENTS\tQUALITY\tMUDASSAR BASHIR KAMBOH
AGENTS\tRACHAEL MARTHA ATOO\tRACHAEL MARTHA ATOO
AGENTS\tRAINBOW SPRING\tQIUER WU
AGENTS\tRAVIAN INTERNATIONAL\tASIF HUSSAIN
AGENTS\tRAVIAN INTERNATIONAL\tNAVEED
AGENTS\tRAVIAN INTERNATIONAL\tUROOJ MEHAR
AGENTS\tREXCARGO\tELUANI VILLALOBOS NUÑEZ
AGENTS\tREXCARGO\tJAMIE
AGENTS\tREXCARGO\tKENSY TRIGUEROS ESTRADA
AGENTS\tREXCARGO\tSABRINA MARIN
AGENTS\tSAMMAN TRANS\tMS. ALAA KAMEL
AGENTS\tSAMMAN TRANS\tALAA KAMEL
AGENTS\tSAMUDERA\tINDRA PRASETIA KUSUMA
AGENTS\tSAMUDERA\tSHINTA APRILIA
AGENTS\tSAMUDERA\tWAHYU PUSPITA ANGGRAENI (ANGGIE)
AGENTS\tSB LOGISTICS\tLILIANA ALFARO ALVAREZ
AGENTS\tSEGURO\tNIA SANDEEP
AGENTS\tSES\tNATALIA VÉLIZ
AGENTS\tSES\tORBETA 
AGENTS\tSF\tADAM BULLAS
AGENTS\tSHIFTCO\tGOPI R.
AGENTS\tSHPR\tCSD FASHION
AGENTS\tSINDBAD\tHELMI BEN SHIL
AGENTS\tSINDBAD\tMENYAR HAMLIA
AGENTS\tSINDBAD GROUPE\tJIHEN SALLEM
AGENTS\tSINDBAD GROUPE\tSANA NACCACHE
AGENTS\tSINDBAD GROUPE\tNEDRA BEN SALEM
AGENTS\tSPEED CARGO\tAKCES
AGENTS\tSPEED CARGO\tCESAR AKOU
AGENTS\tSPEED CARGO\tCESAR AYETCHO
AGENTS\tSPEEDFREIGHT\tWENDY
AGENTS\tSPEEDFREIGHT\tFREDERICK HAGGOO
AGENTS\tSPEEDFREIGHT\tHARISH BHAGIRATTY
AGENTS\tSPEEDFREIGHT\tJUILA WONG
AGENTS\tSPEEDFREIGHT\tJULIA WONG
AGENTS\tSPEEDFREIGHT\tRUBINA RAMUDU
AGENTS\tSPEEDFREIGHT\tSAROJA PILLAY
AGENTS\tSPEEDFREIGHT\tSHANDOSHINI GOVINDEN
AGENTS\tSPEEDFREIGHT\tSTEFFEN MANZ
AGENTS\tSUNGGONG LOGISTICS\tRIZKI SETIAWAN
AGENTS\tSUREFREIGHT INTERNATIONAL\tDOM MCSPORRAN
AGENTS\tTALOS\tMRS.GULMIRA AKYÜREK
AGENTS\tTAM ANH TRADING\tTUAN ANH (MR.)
AGENTS\tTAM ANH TRADING\tYEN DOAN
AGENTS\tTEAM FREIGHT MANAGEMENT\tFAYYAZ GAZIANI
AGENTS\tTEAM FREIGHT MANAGEMENT\tTAHIR ALI
AGENTS\tTIFFANY CARGO SYSTEM\tESSAM NOUR EL AWAMRY
AGENTS\tTRACOSA\tJUAN GONZALEZ
AGENTS\tTRANSMERIDIAN\tGLORIA
AGENTS\tTRANSMERIDIAN\tNICODEMUS KILONZO
AGENTS\tUCI\tTERUKO YASUSHIRO
AGENTS\tUNIVERSAL BRIDGE LOGISTICS\tASHIK NAZEER
AGENTS\tUTC MEDITERRANEAN SRLU\tALESSANDRA COMOTTO
AGENTS\tUTC MEDITERRANEAN SRLU\tALESSANDRO BUFFA
AGENTS\tUTC MEDITERRANEAN SRLU\tALESSIO DE NICOLO
AGENTS\tUTC MEDITERRANEAN SRLU\tDAVIDE SCOVERO
AGENTS\tUTC MEDITERRANEAN SRLU\tLAURA TORRE
AGENTS\tUTC MEDITERRANEAN SRLU\tNICOLA CALLERI
AGENTS\tUTC MEDITERRANEAN SRLU\tLUCA BREZZA
AGENTS\tVAN LOGISTICS BGD\tBIKI
AGENTS\tVAN LOGISTICS BGD\tBIKIRAN BARUA BIKI
AGENTS\tVELOCITY SHIPPING (PVT)\tRUTABA BUTT
AGENTS\tVIECOM\tVINCE CURRO
AGENTS\tVINALINK\tAMY
AGENTS\tVRRDHI\tOM PRASAD
AGENTS\tWEST COAST AVIATION\tGERARD MALCAHY
AGENTS\tWIDE LOGISTICS\tGUSTAVO HENRIQUE CARDOSO
AGENTS\tWIDEAL\tWINNIE CHEUNG
AGENTS\tWORLD FAMOUS\tAZM SALAH UDDIN CHOWDHURY
AGENTS\tWORLD FAMOUS\tSALAH UDDIN
AGENTS\tWUXI JIAHUA INTERNATIONAL FREIGHT\tJASON
AGENTS\tWUXI JIAYI INTERNATIONAL\tFIONA
AGENTS\tWUXI JIAYI INTERNATIONAL\tIRIS
AGENTS\tZUST AMBROSETTI\tFILIPPA NICOSIA
AGENTS\tGLOBAL FREIGHT SYSTEMS CO\tROOPA SHRISHAR
AGENTS\tINDEPENDENT TRANSPORT SHIPPING\tANTON ELOFSSON
AGENTS\tCMSHIP\tCRISTIAN MASSARA
AGENTS\tMII\tFAJAR WIDIARTO
AGENTS\tASELTRANS\tATAMAN BABAKAYA
AGENTS\tHBH\tMOHAMED ZEMNI
AGENTS\tMAYOR EXPRESS FREIGHT SERVICES PTE LTD\tNICOLE BOON
AGENTS\tRIDE-LINK LOGISTICS\tALICIA NALUGYA
AGENTS\tSPEDMAN\tGAŠPER POTISEK
AGENTS\tREXCARGO\tLIZZI EXPINAL ALVARENGA
OTHERS\tSTARPOWER EUROPE AG\tELENA GHILOTTI
AGENTS\tENERGY GLOBAL LOGISTICS\tTANJA CLARKE
AGENTS\tSUNJIN LOGISTICS\tHANLA LEE
AGENTS\tGREEN WORLD\tTOBIAS RIESCH
AGENTS\tA&A CARGO TRANSPORT\tKAMRAN KHAN
AGENTS\tMII\tMS.WIRANJANI ADE
AGENTS\tGRUBER LOGISTICS LIMITED\tMARY MUVYA
AGENTS\tASIA SKY EXPRESS\tGULNAR GASANOVA
BELGIUM\tZIEGLER BELGIUM\tANN ABRAMS
BELGIUM\tZIEGLER BELGIUM\tARIANE DE RAYMAEKER
BELGIUM\tZIEGLER BELGIUM\tBART VANHAM
BELGIUM\tZIEGLER BELGIUM\tBETTINA VAN DER LINDEN
BELGIUM\tZIEGLER BELGIUM\tCATHY CLERBOIS
BELGIUM\tZIEGLER BELGIUM\tCHRISTIAN
BELGIUM\tZIEGLER BELGIUM\tCHRISTINE TRAPPENIERS
BELGIUM\tZIEGLER BELGIUM\tCHRISTOPHE VERMEULEN
BELGIUM\tZIEGLER BELGIUM\tGUILAINE LAYAN
BELGIUM\tZIEGLER BELGIUM\tGUY GOESTSCHALCKX
BELGIUM\tZIEGLER BELGIUM\tINGE RYDANT
BELGIUM\tZIEGLER BELGIUM\tINGEMAR ANDERSSON
BELGIUM\tZIEGLER BELGIUM\tISAM EL BEKKAYE
BELGIUM\tZIEGLER BELGIUM\tIVAN DE PAUW
BELGIUM\tZIEGLER BELGIUM\tJOERI KENNES
BELGIUM\tZIEGLER BELGIUM\tJOHAN ENGELBRECHT
BELGIUM\tZIEGLER BELGIUM\tKARINE VANHUMBEECK
BELGIUM\tZIEGLER BELGIUM\tLAETITIA SEDDA
BELGIUM\tZIEGLER BELGIUM\tLUC AUDIENS
BELGIUM\tZIEGLER BELGIUM\tMATHIAS VERMEIREN
BELGIUM\tZIEGLER BELGIUM\tMICHIEL JACOBS
BELGIUM\tZIEGLER BELGIUM\tNATALIA GURANDA
BELGIUM\tZIEGLER BELGIUM\tPETER DANIELS
BELGIUM\tZIEGLER BELGIUM\tRUDI VERSCHUEREN
BELGIUM\tZIEGLER BELGIUM\tSOFIE MILANTS
BELGIUM\tZIEGLER BELGIUM\tSTEPHAN VAN DEN BRUEL
BELGIUM\tZIEGLER BELGIUM\tTOM VERKOELEN
BELGIUM\tZIEGLER BELGIUM\tWIM PEETERS
BELGIUM\tZIEGLER BELGIUM\tLIEVEN DE DONCKER
BELGIUM\tZIEGLER BELGIUM\tWOLF KUSSÉ
BELGIUM\tZIEGLER BELGIUM\tJEROEN VAN PARIJS
CHINA\tZIEGLER HONG KONG\tANGEL TSE
CHINA\tZIEGLER HONG KONG\tDOROTHY LAI
CHINA\tZIEGLER HONG KONG\tKRISTINE HO
CHINA\tZIEGLER HONG KONG\tLOUIS CHAN
CHINA\tZIEGLER HONG KONG\tPHILIP WONG
CHINA\tZIEGLER HONG KONG\tSTONE CHAN
CHINA\tZIEGLER HONG KONG\tSUSANA WONG
CHINA\tZIEGLER HONG KONG\tYUKI CHAN
CHINA\tZIEGLER HONG KONG\tZAKY
CHINA\tZIEGLER HONG KONG\tSTEVE KWAN
CHINA\tZIEGLER NINGBO\tNICY YANG
CHINA\tZIEGLER NINGBO\tVIVIAN LI
CHINA\tZIEGLER QINGDAO\tHETTY HAO
CHINA\tZIEGLER QINGDAO\tNICOLE YUAN
CHINA\tZIEGLER SHANGHAI\tAMY CHEN
CHINA\tZIEGLER SHANGHAI\tHAIQING SONG
CHINA\tZIEGLER SHANGHAI\tRAMPO FANG
CHINA\tZIEGLER SHANGHAI\tJASON JI
CHINA\tZIEGLER SHENZHEN\tSAM LIN
CHINA\tZIEGLER SHENZHEN\tSUSAN ZHAO
CHINA\tZIEGLER SHENZHEN\tSHAWN LUO
CHINA\tZIEGLER TIANJIN\tTINA WANG
CHINA\tZIEGLER XIAMEN\tHELEN WU
FRANCE\tZIEGLER FRANCE\tADAN BULLAS
FRANCE\tZIEGLER FRANCE\tAHDMRA
FRANCE\tZIEGLER FRANCE\tALICE CAMI
FRANCE\tZIEGLER FRANCE\tALIX MEYER
FRANCE\tZIEGLER FRANCE\tAMELIE ZIEGLER
FRANCE\tZIEGLER FRANCE\tAMINE OUAABI
FRANCE\tZIEGLER FRANCE\tANNE LAGUTERE
FRANCE\tZIEGLER FRANCE\tARNAUD PARINET
FRANCE\tZIEGLER FRANCE\tBARBARA CARRO
FRANCE\tZIEGLER FRANCE\tBARBARA GUERIN-PINAUD
FRANCE\tZIEGLER FRANCE\tBELLE SERRE
FRANCE\tZIEGLER FRANCE\tBENJAMIN BELE
FRANCE\tZIEGLER FRANCE\tBERELAX - CARLA GREJALVO
FRANCE\tZIEGLER FRANCE\tBÉRENGER HUDSON
FRANCE\tZIEGLER FRANCE\tBRUNO TOISER
FRANCE\tZIEGLER FRANCE\tCAPUCINE DURY
FRANCE\tZIEGLER FRANCE\tCARYS SHEARS
FRANCE\tZIEGLER FRANCE\tCATHY LARTELIER
FRANCE\tZIEGLER FRANCE\tCDG SALES
FRANCE\tZIEGLER FRANCE\tCECILE STRACK
FRANCE\tZIEGLER FRANCE\tCÉLINE DESTRUYS
FRANCE\tZIEGLER FRANCE\tCHRISTELLE VONESCH
FRANCE\tZIEGLER FRANCE\tCHRISTIE PATRY
FRANCE\tZIEGLER FRANCE\tCLÉMENT LE ROY BLAVET
FRANCE\tZIEGLER FRANCE\tCORINNE PANAGIODIS
FRANCE\tZIEGLER FRANCE\tCOTATIONS BOD
FRANCE\tZIEGLER FRANCE\tCYRILLE MANDARO
FRANCE\tZIEGLER FRANCE\tDAMIEN BERTERO
FRANCE\tZIEGLER FRANCE\tDAMIEN ROSALIA
FRANCE\tZIEGLER FRANCE\tDAVID MBENGI
FRANCE\tZIEGLER FRANCE\tELEN CENGIZ
FRANCE\tZIEGLER FRANCE\tELISABETH
FRANCE\tZIEGLER FRANCE\tELISABETH GITZ
FRANCE\tZIEGLER FRANCE\tELISE GOSSIN
FRANCE\tZIEGLER FRANCE\tELIZA BILLAULT
FRANCE\tZIEGLER FRANCE\tESTHER SAE CHIAO
FRANCE\tZIEGLER FRANCE\tFANNY MARTEL
FRANCE\tZIEGLER FRANCE\tFANNY MARTIN
FRANCE\tZIEGLER FRANCE\tFANNY MAUCHAMP
FRANCE\tZIEGLER FRANCE\tFÉLIX DEVILLIERS
FRANCE\tZIEGLER FRANCE\tFIDO - DINI YANRIANI
FRANCE\tZIEGLER FRANCE\tFLORENCE LEGROS
FRANCE\tZIEGLER FRANCE\tFRANCINE LATRASSE
FRANCE\tZIEGLER FRANCE\tGHARIB ROBBA
FRANCE\tZIEGLER FRANCE\tHASSINA DASS
FRANCE\tZIEGLER FRANCE\tHAYET AZZOUZ
FRANCE\tZIEGLER FRANCE\tHEIKE
FRANCE\tZIEGLER FRANCE\tHOURIA RIFFI
FRANCE\tZIEGLER FRANCE\tHOUSSEM BEN TORKIA
FRANCE\tZIEGLER FRANCE\tIDAYATH SAKA
FRANCE\tZIEGLER FRANCE\tINGRID DERIMAY
FRANCE\tZIEGLER FRANCE\tIRENE QUINONES
FRANCE\tZIEGLER FRANCE\tISABELLE BEUSTE
FRANCE\tZIEGLER FRANCE\tISABELLE SERRE
FRANCE\tZIEGLER FRANCE\tISMAEL DROUICHE
FRANCE\tZIEGLER FRANCE\tJEAN LOUIS LEYRE
FRANCE\tZIEGLER FRANCE\tJEAN-BAPTISTE DUBOIS
FRANCE\tZIEGLER FRANCE\tJEAN-CHARLES HERAULT
FRANCE\tZIEGLER FRANCE\tJEAN-FRANCOIS PUJOLAS
FRANCE\tZIEGLER FRANCE\tJEANNINE DELERUE
FRANCE\tZIEGLER FRANCE\tJEAN-PHILIPPE GRANDCLEMENT
FRANCE\tZIEGLER FRANCE\tJEMIMA FARATIANA
FRANCE\tZIEGLER FRANCE\tJÉMIMA FARATIANA
FRANCE\tZIEGLER FRANCE\tJEROEN VAN PARIJS
FRANCE\tZIEGLER FRANCE\tJESSICA
FRANCE\tZIEGLER FRANCE\tJESSICA GRACE FORTUNEE
FRANCE\tZIEGLER FRANCE\tJESSICA SARAIVA
FRANCE\tZIEGLER FRANCE\tJOHANN LEDEZ
FRANCE\tZIEGLER FRANCE\tJORDAN MORNET
FRANCE\tZIEGLER FRANCE\tJOSHUA
FRANCE\tZIEGLER FRANCE\tJOSHUA COURTAUT
FRANCE\tZIEGLER FRANCE\tJULES MONTMAYEUL
FRANCE\tZIEGLER FRANCE\tJUSTINE DUBOSCQ
FRANCE\tZIEGLER FRANCE\tKARINE DE SOUSA
FRANCE\tZIEGLER FRANCE\tKARINE ROBERTON
FRANCE\tZIEGLER FRANCE\tLABINOT NEXHIBI
FRANCE\tZIEGLER FRANCE\tLAETITIA BLANC
FRANCE\tZIEGLER FRANCE\tLAURELINE COURTAUT
FRANCE\tZIEGLER FRANCE\tLAURENCE BUCCI
FRANCE\tZIEGLER FRANCE\tLAURENCE HUI
FRANCE\tZIEGLER FRANCE\tLAURENT MATHIEU
FRANCE\tZIEGLER FRANCE\tLILIA AMPLE
FRANCE\tZIEGLER FRANCE\tLINDA BEDJAOUI
FRANCE\tZIEGLER FRANCE\tLORIANE BERTOLA
FRANCE\tZIEGLER FRANCE\tLOU-ANNE MAC CARTHY
FRANCE\tZIEGLER FRANCE\tLUC KASTLER
FRANCE\tZIEGLER FRANCE\tMAGALI AMORE
FRANCE\tZIEGLER FRANCE\tMALIKA OUABBOU
FRANCE\tZIEGLER FRANCE\tMARIE-CHRISTINE BERT
FRANCE\tZIEGLER FRANCE\tMATHIEU CASES
FRANCE\tZIEGLER FRANCE\tMATHILDE BERNARD
FRANCE\tZIEGLER FRANCE\tMELANIE SCHNEIDER
FRANCE\tZIEGLER FRANCE\tMOHAMED MOKEDDEM
FRANCE\tZIEGLER FRANCE\tMORGAN LAROSA
FRANCE\tZIEGLER FRANCE\tMURIEL BERTHOLIO
FRANCE\tZIEGLER FRANCE\tMYLENE PAPILLON
FRANCE\tZIEGLER FRANCE\tNARJISSE CHAFI
FRANCE\tZIEGLER FRANCE\tNATALIIA ROUX
FRANCE\tZIEGLER FRANCE\tNATHALIE MARION
FRANCE\tZIEGLER FRANCE\tNATHALIE MARONNE
FRANCE\tZIEGLER FRANCE\tNICOLAS MARCEL
FRANCE\tZIEGLER FRANCE\tNICOLAS SCHOTTER
FRANCE\tZIEGLER FRANCE\tNICOLE MARTIN
FRANCE\tZIEGLER FRANCE\tNINA - VIRAPHONE SOLIPHANH
FRANCE\tZIEGLER FRANCE\tNOUAMAN KOUCHIH
FRANCE\tZIEGLER FRANCE\tOLIVIER BLANQUET
FRANCE\tZIEGLER FRANCE\tOLIVIER BRAUD
FRANCE\tZIEGLER FRANCE\tOSHAIGER - JULIUS CAESAR B. ROQUE
FRANCE\tZIEGLER FRANCE\tOUAFIA BOUKENSOUS
FRANCE\tZIEGLER FRANCE\tOUARDA ELMALLASS
FRANCE\tZIEGLER FRANCE\tOUMAROUCISSOKHO
FRANCE\tZIEGLER FRANCE\tPASCAL BASSET
FRANCE\tZIEGLER FRANCE\tPASCAL VASSEUR
FRANCE\tZIEGLER FRANCE\tPAUL TOTAL
FRANCE\tZIEGLER FRANCE\tPAULINA LEWANDOWSKA
FRANCE\tZIEGLER FRANCE\tPAULINE DUCERT
FRANCE\tZIEGLER FRANCE\tPAULINE SANTURENNE
FRANCE\tZIEGLER FRANCE\tPIERRE HENRY
FRANCE\tZIEGLER FRANCE\tRACHEL KOELIN
FRANCE\tZIEGLER FRANCE\tRACHIDA BELAID
FRANCE\tZIEGLER FRANCE\tRAM AEROSPACE
FRANCE\tZIEGLER FRANCE\tROBIN PAULAS
FRANCE\tZIEGLER FRANCE\tROHAN DELAPORTE
FRANCE\tZIEGLER FRANCE\tROMAIN DA SILVA
FRANCE\tZIEGLER FRANCE\tROMAIN JANSSENS
FRANCE\tZIEGLER FRANCE\tROMANE MAZERAND
FRANCE\tZIEGLER FRANCE\tROYAL AIR MAROC
FRANCE\tZIEGLER FRANCE\tSABRINA GRAS
FRANCE\tZIEGLER FRANCE\tSABRINA HUE
FRANCE\tZIEGLER FRANCE\tSAMIR REBBOUH
FRANCE\tZIEGLER FRANCE\tSANDRINE JUILLIEN
FRANCE\tZIEGLER FRANCE\tSANDRINE PIERRET
FRANCE\tZIEGLER FRANCE\tSARAH DUBUS
FRANCE\tZIEGLER FRANCE\tSASHA RONCIN
FRANCE\tZIEGLER FRANCE\tSCHNEIDER MÉLANIE
FRANCE\tZIEGLER FRANCE\tSEBASTIEN
FRANCE\tZIEGLER FRANCE\tSEBASTIEN BARDIN
FRANCE\tZIEGLER FRANCE\tSEBASTIEN CORDIER
FRANCE\tZIEGLER FRANCE\tSEVERINE BAYLE
FRANCE\tZIEGLER FRANCE\tSIMAR REBBOUH
FRANCE\tZIEGLER FRANCE\tSOFIEN ATYF
FRANCE\tZIEGLER FRANCE\tSTEPHIE COMBE
FRANCE\tZIEGLER FRANCE\tSYLVAIN FIAKAIFONU
FRANCE\tZIEGLER FRANCE\tTHIBAUT MALFOY
FRANCE\tZIEGLER FRANCE\tTHOMAS MENNECIER
FRANCE\tZIEGLER FRANCE\tTOUFIK SERHIRI
FRANCE\tZIEGLER FRANCE\tVALERIA RAHAMEFY
FRANCE\tZIEGLER FRANCE\tVANESSA BALAVOINE
FRANCE\tZIEGLER FRANCE\tVANESSA LEFORT-VENDANGE
FRANCE\tZIEGLER FRANCE\tVINCENT DUCHESNE
FRANCE\tZIEGLER FRANCE\tVINCENT GAUCI
FRANCE\tZIEGLER FRANCE\tVIRAPHONE SOLIPHANH
FRANCE\tZIEGLER FRANCE\tVIRGINIE PLOQUIN
FRANCE\tZIEGLER FRANCE\tWASSIM GARMA
FRANCE\tZIEGLER FRANCE\tYANN LORÉE
FRANCE\tZIEGLER FRANCE\tFLORENCE MOUSSAVOU
FRANCE\tZIEGLER FRANCE\tCLARISSE JEUDY
FRANCE\tZIEGLER FRANCE\tAKIM JEGO
FRANCE\tZIEGLER FRANCE\tYASSINE HAMADOUCH
FRANCE\tZIEGLER FRANCE\tANAELLE MARSOLLIER
FRANCE\tZIEGLER FRANCE\tGUILLAUME STEINER
FRANCE\tZIEGLER FRANCE\tJULIE DA FIES
FRANCE\tZIEGLER FRANCE\tLYNDA BENBECHEM
GERMANY\tZIEGLER GERMANY\tAARON KIRBERG
GERMANY\tZIEGLER GERMANY\tANGELIKA
GERMANY\tZIEGLER GERMANY\tANN-KATHRIN ZEHM
GERMANY\tZIEGLER GERMANY\tBARBARA HOFFMANN
GERMANY\tZIEGLER GERMANY\tBURAK HISARKAYA
GERMANY\tZIEGLER GERMANY\tDANIEL STENZEL
GERMANY\tZIEGLER GERMANY\tDENNIS HASSE
GERMANY\tZIEGLER GERMANY\tDILAN ULUS
GERMANY\tZIEGLER GERMANY\tEBRU LOVRIC
GERMANY\tZIEGLER GERMANY\tEDHOFER HANS
GERMANY\tZIEGLER GERMANY\tEMILY MAIER
GERMANY\tZIEGLER GERMANY\tENES AKBALIK
GERMANY\tZIEGLER GERMANY\tHAMZA CHAWKI
GERMANY\tZIEGLER GERMANY\tHEIKE OHDE
GERMANY\tZIEGLER GERMANY\tHYEYOUN NAM
GERMANY\tZIEGLER GERMANY\tJACQUELINE CABRERA
GERMANY\tZIEGLER GERMANY\tJAKOB MATERI
GERMANY\tZIEGLER GERMANY\tJEROME MARSHALL
GERMANY\tZIEGLER GERMANY\tJONAS NEVALA
GERMANY\tZIEGLER GERMANY\tJULIA SCHLZE
GERMANY\tZIEGLER GERMANY\tJULIAN SCHERR
GERMANY\tZIEGLER GERMANY\tJUSTINE RICH
GERMANY\tZIEGLER GERMANY\tLARA DAUM
GERMANY\tZIEGLER GERMANY\tMARA TABEA ROSEMEIER
GERMANY\tZIEGLER GERMANY\tMARCEL BUNDGENS
GERMANY\tZIEGLER GERMANY\tMARIUS BOEHM
GERMANY\tZIEGLER GERMANY\tMARIUS PETERS
GERMANY\tZIEGLER GERMANY\tMARKUS MARQUARDT
GERMANY\tZIEGLER GERMANY\tMATTHIAS PICHER
GERMANY\tZIEGLER GERMANY\tMOHAMED MIYARA
GERMANY\tZIEGLER GERMANY\tMANUEL RENZ
GERMANY\tZIEGLER GERMANY\tNICOLE DOERRHOEFER
GERMANY\tZIEGLER GERMANY\tNILS BERGHOF
GERMANY\tZIEGLER GERMANY\tSABINE STÄBLER
GERMANY\tZIEGLER GERMANY\tSAMIRA HOFBAUER
GERMANY\tZIEGLER GERMANY\tSELIN TEKER
GERMANY\tZIEGLER GERMANY\tTANJA DEGENHARDT
GERMANY\tZIEGLER GERMANY\tTANJA
GERMANY\tZIEGLER GERMANY\tTHORSTEN SCHOLZ
GERMANY\tZIEGLER GERMANY\tTIM STECK
GERMANY\tZIEGLER GERMANY\tTOBIAS SCHROTH
GERMANY\tZIEGLER GERMANY\tUFUK YILDIZ
GERMANY\tZIEGLER GERMANY\tYOUNG KANG
GERMANY\tZIEGLER GERMANY\tPETRA JESNOWSKI
GERMANY\tZIEGLER GERMANY\tDANIEL HANISCH
GERMANY\tZIEGLER GERMANY\tNADINE GRUNNERT
GERMANY\tZIEGLER GERMANY\tFELIX HÖRMANN
GERMANY\tZIEGLER GERMANY\tNICO FUCHS
GREECE\tZIEGLER GREECE\tMARIA FOTI
GREECE\tZIEGLER GREECE\tSTEFANOS KOUFAKIS
GREECE\tZIEGLER GREECE\tELEFTHERIA KOTSOVASILI
MOROCCO\tZIEGLER MOROCCO\tBIEN ELHARIRI ESSAMLALI
MOROCCO\tZIEGLER MOROCCO\tELMEHDI BELALIA
MOROCCO\tZIEGLER MOROCCO\tFATIMA EZZAHRA OUARSANA
MOROCCO\tZIEGLER MOROCCO\tHAJAR EL HARIRI ESSAMLALI
MOROCCO\tZIEGLER MOROCCO\tHOUDA SBAI LDRISSI
MOROCCO\tZIEGLER MOROCCO\tJIHANE BAGHDADI
MOROCCO\tZIEGLER MOROCCO\tLAHLALI SAIF
MOROCCO\tZIEGLER MOROCCO\tMYLENE DELORME
MOROCCO\tZIEGLER MOROCCO\tSANAA ELOUADI
MOROCCO\tZIEGLER MOROCCO\tWIAM LAHMAM
NETHERLANDS\tZIEGLER NETHERLANDS\tAB AHSAINI
NETHERLANDS\tZIEGLER NETHERLANDS\tADRIANA WESTERHOF
NETHERLANDS\tZIEGLER NETHERLANDS\tALI CABUK
NETHERLANDS\tZIEGLER NETHERLANDS\tDYLAN
NETHERLANDS\tZIEGLER NETHERLANDS\tFRANK SPEIJER
NETHERLANDS\tZIEGLER NETHERLANDS\tHAMZA EL BAKKALI
NETHERLANDS\tZIEGLER NETHERLANDS\tINES GROL
NETHERLANDS\tZIEGLER NETHERLANDS\tJACO MEIJER
NETHERLANDS\tZIEGLER NETHERLANDS\tJACO VAN DIJK
NETHERLANDS\tZIEGLER NETHERLANDS\tKARIMA TIJAMI
NETHERLANDS\tZIEGLER NETHERLANDS\tKELLY OGBEIDE
NETHERLANDS\tZIEGLER NETHERLANDS\tMELANIE COX
NETHERLANDS\tZIEGLER NETHERLANDS\tMET VRIENDELIJKE GROET
NETHERLANDS\tZIEGLER NETHERLANDS\tPASCAL
NETHERLANDS\tZIEGLER NETHERLANDS\tPASCAL VAN DER SPEK
NETHERLANDS\tZIEGLER NETHERLANDS\tREMCO
NETHERLANDS\tZIEGLER NETHERLANDS\tREMCO STOFFELS
NETHERLANDS\tZIEGLER NETHERLANDS\tRUŽICA TUBIN
NETHERLANDS\tZIEGLER NETHERLANDS\tSALES TEAM
NETHERLANDS\tZIEGLER NETHERLANDS\tTACO MEIJER
NETHERLANDS\tZIEGLER NETHERLANDS\tTARA DJORAI
NETHERLANDS\tZIEGLER NETHERLANDS\tTHIJS VAN DER STELT
NETHERLANDS\tZIEGLER NETHERLANDS\tVIRGIL SIWALETTE
NETHERLANDS\tZIEGLER NETHERLANDS\tLENNOX TWUMASI
OTHERS\tAMARI METALS CHINA\tKATHY LIU
OTHERS\tEC4U LIMITED\tJANET
OTHERS\tGRUPO V.SANTOS\tMATEUS LIMA PEIXOTO
OTHERS\tGUANGHZOU SOURCING\tHUIMIN WU
OTHERS\tHONG KONG HOYOGO\tIVY HUANG
OTHERS\tJABEZ FURNITURE\tSEVEN ZHONG
OTHERS\tSHANDONG JULI ALUMINIUM\tCARRIE FENG
OTHERS\tTAM ANH TRADING\tTUAN ANH
OTHERS\tTREMAIL\tPASCAL LAROUMANIE
OTHERS\tVIECOM\tVINCE CURRO
OTHERS\tNOVOBOX\tYANNIS FONTAINE
POLAND\tZIEGLER POLAND\tRAFAL ADAMCZEWSKI
SOUTH_AFRICA\t-\tAUDREY CONLIN
SOUTH_AFRICA\tZIEGLER CAPETOWN\tANTHEA WILLIAMS
SOUTH_AFRICA\tZIEGLER CAPETOWN\tCHEVONNE ARENDSE
SOUTH_AFRICA\tZIEGLER CAPETOWN\tKEATHAN KIEWIET
SOUTH_AFRICA\tZIEGLER CAPETOWN\tTORIQ DAVIDS
SOUTH_AFRICA\tZIEGLER CAPETOWN\tZELNA MINNIE
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tALEXIS MOGOROSI
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tANDRE BERRY
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tASHNEE CHUNNILALL
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tBASIL GEORGILADAKIS
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tCAROLINE LESO
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tCRAIG FOX
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tCYNTHIA NTINI
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tGILLIAN LABUSCHAGNE
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tILZE NEETHLING
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tJESSICA MATLHOGONOLO METSING
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tJYOTHI MAHARAJ
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tKAYLA DEE ERLANK
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tKAYLA PRETORIUS
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tKIRSTY PATRICK
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tLONWABO MXUMA
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tLYNTHIA NTINI
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tMECALI VAN ROOYEN
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tMICHELLE MOTHIBA
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tNOLUTHANDO KHUMALO
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tSIMON KIBI
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tSTEPHANIE NAIDOO
SOUTH_AFRICA\tZIEGLER JOHANNESBURG\tTRACY PADAYACHEE
SWITZERLAND\tZIEGLER SWITZERLAND\tALEX
SWITZERLAND\tZIEGLER SWITZERLAND\tALEXANDER REISER
SWITZERLAND\tZIEGLER SWITZERLAND\tANDY
SWITZERLAND\tZIEGLER SWITZERLAND\tANDY EGGENBERGER
SWITZERLAND\tZIEGLER SWITZERLAND\tBAHRIYE ÖZALP
SWITZERLAND\tZIEGLER SWITZERLAND\tCAMILLE PARENT
SWITZERLAND\tZIEGLER SWITZERLAND\tCASHROM SELVARATNAM
SWITZERLAND\tZIEGLER SWITZERLAND\tCÉLINE
SWITZERLAND\tZIEGLER SWITZERLAND\tCELYA GOUBERT
SWITZERLAND\tZIEGLER SWITZERLAND\tCHRISTIAN BRECHENMACHER
SWITZERLAND\tZIEGLER SWITZERLAND\tDANIEL MELE
SWITZERLAND\tZIEGLER SWITZERLAND\tDANIEL SIGRIST
SWITZERLAND\tZIEGLER SWITZERLAND\tEMANUEL RECHSTEINER
SWITZERLAND\tZIEGLER SWITZERLAND\tEMRE KARADENIZ
SWITZERLAND\tZIEGLER SWITZERLAND\tESTELLE KOEHL
SWITZERLAND\tZIEGLER SWITZERLAND\tFITIM KRYEZIU
SWITZERLAND\tZIEGLER SWITZERLAND\tJOEL WALTER
SWITZERLAND\tZIEGLER SWITZERLAND\tJOFFREY FELIX
SWITZERLAND\tZIEGLER SWITZERLAND\tMARCO SUTER
SWITZERLAND\tZIEGLER SWITZERLAND\tMELANIE KÄLIN
SWITZERLAND\tZIEGLER SWITZERLAND\tMIRJAM BAERLOCHER
SWITZERLAND\tZIEGLER SWITZERLAND\tPATRICK GALLAIS
SWITZERLAND\tZIEGLER SWITZERLAND\tESRA SAHIN
TBA\tTBA\tABBY HUANG
TBA\tTBA\tADITHYA RANJITH
TBA\tTBA\tARIELA
TBA\tTBA\tASAD ISLAM
TBA\tTBA\tDIANA PAOLA CIRO GIRALDO
TBA\tTBA\tFADY ABIKARAM
TBA\tTBA\tHARRISON
TBA\tTBA\tHELEEMA ASIF
TBA\tTBA\tILKER
TBA\tTBA\tIRENE WONG
TBA\tTBA\tKC HO
AGENTS\tREX CARGO\tLARRY LAMAS
TBA\tTBA\tLEE TYRER
TBA\tTBA\tLIKER USTUNDAG
TBA\tTBA\tPRAJWOL AMATYA
TBA\tTBA\tR SURESH
TBA\tTBA\tRENATO TRUST
TBA\tTBA\tSA REHMAN
TBA\tTBA\tSIJY JACOB
UK\tZIEGLER BIRMINGHAM\tCHRIS BLOWER
UK\tZIEGLER BIRMINGHAM\tNICK POPE
UK\tZIEGLER BIRMINGHAM\tPHIL BUCKLE
UK\tZIEGLER BIRMINGHAM\tRUTH BUDD
UK\tZIEGLER BIRMINGHAM\tTREVOR BROWN
UK\tZIEGLER BIRMINGHAM\tCHANTEL GIBBONS
UK\tZIEGLER BRADFORD\tADAM PORRITT
UK\tZIEGLER BRADFORD\tBEN CROWE
UK\tZIEGLER BRADFORD\tKATIE-LOUISE SCOTT
UK\tZIEGLER BRADFORD\tKIRSTY FEATHERSTONE
UK\tZIEGLER BRADFORD\tMATTHEW SMITH
UK\tZIEGLER BRISTOL\tCHRIS TAYLER
UK\tZIEGLER BRISTOL\tMARCUS ASHLEY
UK\tZIEGLER COLNBROOK\tRYAN HERBERT
UK\tZIEGLER COLNBROOK\tSAMANTHA GIBBON
UK\tZIEGLER COLNBROOK\tSTEFANO SEU
UK\tZIEGLER COLNBROOK\tDANIEL SCARLETT
UK\tZIEGLER COLNBROOK\tJAKE BROWN
UK\tZIEGLER COLNBROOK\tPETER BARKER
UK\tZIEGLER COLNBROOK\tSTEWART BROOK
UK\tZIEGLER COLNBROOK\tCHRIS MOORE
UK\tZIEGLER DURHAM\tHOLLY HADDEN
UK\tZIEGLER DURHAM\tJAMES SMITH
UK\tZIEGLER DURHAM\tKELLY BRYSON
UK\tZIEGLER FELIXSTOWE\tALISON WALKER
UK\tZIEGLER FELIXSTOWE\tDANNY MOTT
UK\tZIEGLER FELIXSTOWE\tJAMES MAFFEY
UK\tZIEGLER FELIXSTOWE\tJON CLAY
UK\tZIEGLER FELIXSTOWE\tKARNIE CHEUNG
UK\tZIEGLER FELIXSTOWE\tKATE FLYNN
UK\tZIEGLER FELIXSTOWE\tKEVIN WALKER
UK\tZIEGLER FELIXSTOWE\tLINDA FARROW
UK\tZIEGLER FELIXSTOWE\tMICHELE RICHARDSON
UK\tZIEGLER FELIXSTOWE\tSARAH OMALEY
UK\tZIEGLER HEATHROW\tANDREW JONES
UK\tZIEGLER HEATHROW\tANDY ROBERTSON
UK\tZIEGLER HEATHROW\tJOSH WINN
UK\tZIEGLER WARRINGTON\tJOHN WOODS
UK\tZIEGLER NEWPORT\tAARON BREWER
UK\tZIEGLER NEWPORT\tCARON PAYNE
UK\tZIEGLER NEWPORT\tCHRIS LACEY
UK\tZIEGLER NEWPORT\tCRAIG WILLIAMS
UK\tZIEGLER NEWPORT\tIAN MATTHEWS
UK\tZIEGLER NEWPORT\tJONATHON EDWARDS
UK\tZIEGLER NEWPORT\tLUCY BUXTON
UK\tZIEGLER NEWPORT\tMATTHEW DAVIES
UK\tZIEGLER NEWPORT\tMATTHEW EVANS
UK\tZIEGLER NEWPORT\tPAUL CONLON
UK\tZIEGLER NEWPORT\tSTEVE SEWARD
UK\tZIEGLER NORTHAMPTON\tGARY MURRAY
UK\tZIEGLER NORTHAMPTON\tSAMUEL GARDNER
UK\tZIEGLER NORTHAMPTON\tSAMUEL NICKLIN
UK\tZIEGLER PORTSMOUTH\tCARYS SHEARS
UK\tZIEGLER PORTSMOUTH\tELIN WESTLAKE JONES
UK\tZIEGLER PORTSMOUTH\tJAMES RAVENHALL
UK\tZIEGLER PORTSMOUTH\tMICHAEL GILL
UK\tZIEGLER PORTSMOUTH\tNIKOLAJ DELRIVO
UK\tZIEGLER WARRINGTON\tANDY DOMVILLE
UK\tZIEGLER WARRINGTON\tDIANE BOSTOCK
UK\tZIEGLER WARRINGTON\tDIANE CONWAY
UK\tZIEGLER WARRINGTON\tJAMES WILKINSON
UK\tZIEGLER WARRINGTON\tLYNDSEY GARGAN
UK\tZIEGLER WARRINGTON\tNICK EVANS
UK\tZIEGLER WARRINGTON\tPAUL RIDGERS
UK\tZIEGLER WARRINGTON\tDANIELLE TOOLE
UK\tZIEGLER LONDON GATEWAY\tADAM JEFFERIES
UK\tZIEGLER SOUTHAMPTON\tPHIL COPLAND
USA\tZIEGLER USA\tAMBER COLES
USA\tZIEGLER USA\tJOE ELIZONDO
USA\tZIEGLER USA\tSARAH PINKSTON
AGENTS\tFIBS LOGISTICS\tAAZMA SIDDIQUI
AGENTS\tENGERGY GLOAL LOGSITICS\tMARKK CUCEK
AGENTS\tSUNJIN LOGISTICS\tJIHYE HYUN
AGENTS\tSUNJIN LOGISTICS\tJIMIN CHUNG
AGENTS\tHIGH TECH WORLD CARGO\tRAJAI MUSLEH
AGENTS\tLOGSHIP SRL\tSILVIA
AGENTS\tLEOPARD SHIPPING & LOGISTICS LIMITED\tANNY KHAN
AGENTS\tATE GROUP\tWENDY THOM
AGENTS\tLEX LOGISTICS\tKUTAL TASKAYA
AGENTS\tREXCARGO\tLIZZI ESPINAL ALVARENGA
AGENTS\tA&A CARGO TRANSPORT\tASHAR SAEED
FRANCE\tZIEGLER FRANCE\tMORGANE CHEVRAUX
OTHERS\tSHENZHEN CENTER INT'L LOGISTICS CO.,LTD\tTIM SU
AGENTS\tMAYA TURKEY\tLLKER USTUNDAG
AGENTS\tAUSCORP\tVALDEMAR ENGEL
BELGIUM\tZIEGLER BELGIUM\tTHOMAS BENTLEY
AGENTS\tXCEED LOGISTICS\tASSEM OMAR
OTHERS\tGUANGZHOU GIB HORTI LIMITED\tANNA
OTHERS\tGREEN WORLDWIDE SHIPPING\tNICK HOWE
OTHERS\tSHENZHEN CENTER INT'L LOGISTICS CO.,LTD\tSELINA
AGENTS\tBEN LINE LOGISTICS\tKHANDAKAR SHAH-E-ALAM
FRANCE\tZIEGLER FRANCE\tLINE BUTSCHA
FRANCE\tZIEGLER FRANCE\tGHARIB ROBBA
FRANCE\tZIEGLER FRANCE\tALICIA PRODHON
GERMANY\tZIEGLER GERMANY\tLARA PROKISCH
GERMANY\tZIEGLER GERMANY\tLEONARD HANSER
AGENTS\tWEST COAST AVIATION(SHANNON) LIMITED\tGERARD MULCAHY
GREECE\tZIEGLER GREECE\tMARY TOURLIDA
GERMANY\tZIEGLER GERMANY\tYANNICK SKIBA
GERMANY\tZIEGLER GERMANY\tDENIZ ROSS
AGENTS\tHIGH TECH WORLD CARGO\tWAFAI MUSLEH
SWITZERLAND\tZIEGLER SWITZERLAND\tCLAUDIO MEIER
"""

# ── normalize 函数 ────────────────────────────────────────────────────────────
def normalize(s):
    if s is None:
        return ''
    s = s.replace('\xa0', ' ')
    s = ''.join(c for c in unicodedata.normalize('NFKD', s)
                if unicodedata.category(c) != 'Mn')
    return re.sub(r'\s+', ' ', s).strip().upper()

def make_code(country_code, office_name, existing_codes):
    """生成唯一 office code，格式: {country_code}-{ABBREV}"""
    words = re.findall(r'[A-Za-z0-9]+', office_name)
    if not words:
        base = 'X'
    elif len(words) == 1:
        base = words[0][:10].upper()
    else:
        base = ''.join(w[0] for w in words).upper()
    
    candidate = f"{country_code}-{base}"
    if candidate not in existing_codes:
        return candidate
    # 冲突时加数字后缀
    for i in range(2, 100):
        c2 = f"{country_code}-{base}{i}"
        if c2 not in existing_codes:
            return c2
    return f"{country_code}-{base}-{id(office_name)}"

# ── 解析 RAW 数据 ─────────────────────────────────────────────────────────────
rows = []
for line in RAW.strip().splitlines():
    parts = line.split('\t')
    if len(parts) < 3:
        continue
    country_raw, office_raw, pic_raw = parts[0].strip(), parts[1].strip(), parts[2].strip()
    if country_raw == 'SALESCOUNTRY':
        continue
    country_code = COUNTRY_MAP.get(country_raw.upper(), country_raw.upper())
    rows.append((country_code, office_raw, pic_raw))

print(f"CSV 数据解析: {len(rows)} 行")

# ── 连接数据库 ────────────────────────────────────────────────────────────────
conn = mysql.connector.connect(host='localhost', port=3306,
                               user='root', password='ldf123',
                               database='logitrack', charset='utf8mb4')
cur = conn.cursor()

# ── 读取已有数据 ──────────────────────────────────────────────────────────────
cur.execute("SELECT id, country_code, name, code FROM dict_sales_office")
db_offices = {}       # (country_code, norm_name) -> id
existing_codes = set()
for r in cur.fetchall():
    db_offices[(r[1], normalize(r[2]))] = r[0]
    existing_codes.add(r[3])

cur.execute("SELECT sales_office_id, name_norm FROM sales_pic")
db_pics = set()
for r in cur.fetchall():
    db_pics.add((r[0], r[1]))

# ── 收集需要插入的 offices ────────────────────────────────────────────────────
need_offices = {}  # (country_code, norm_name) -> original_name
for country_code, office_raw, pic_raw in rows:
    key = (country_code, normalize(office_raw))
    if key not in db_offices and key not in need_offices:
        need_offices[key] = office_raw

print(f"→ 需要新增 offices: {len(need_offices)}")

# ── 插入新 offices ────────────────────────────────────────────────────────────
inserted_offices = 0
for (country_code, norm_name), orig_name in need_offices.items():
    code = make_code(country_code, orig_name, existing_codes)
    existing_codes.add(code)
    try:
        cur.execute(
            "INSERT INTO dict_sales_office (code, name, name_norm, country_code) VALUES (%s, %s, %s, %s)",
            (code, orig_name, norm_name, country_code)
        )
        db_offices[(country_code, norm_name)] = cur.lastrowid
        inserted_offices += 1
    except mysql.connector.errors.IntegrityError as e:
        print(f"  [SKIP office] {country_code} / {orig_name}: {e}")
        # 尝试重新查询
        cur.execute("SELECT id FROM dict_sales_office WHERE country_code=%s AND name_norm=%s",
                    (country_code, norm_name))
        row = cur.fetchone()
        if row:
            db_offices[(country_code, norm_name)] = row[0]
conn.commit()
print(f"  ✅ 已插入 {inserted_offices} 个新 office")

# ── 收集需要插入的 PICs ───────────────────────────────────────────────────────
need_pics = []
for country_code, office_raw, pic_raw in rows:
    office_id = db_offices.get((country_code, normalize(office_raw)))
    if office_id is None:
        print(f"  [WARN] office 未找到: {country_code} / {office_raw}")
        continue
    norm_pic = normalize(pic_raw)
    if norm_pic and (office_id, norm_pic) not in db_pics:
        need_pics.append((office_id, country_code, pic_raw.strip(), norm_pic))
        db_pics.add((office_id, norm_pic))

print(f"→ 需要新增 PICs: {len(need_pics)}")

# ── 插入新 PICs ───────────────────────────────────────────────────────────────
inserted_pics = 0
for office_id, country_code, pic_name, norm_pic in need_pics:
    try:
        cur.execute(
            "INSERT INTO sales_pic (name, name_norm, country_code, sales_office_id) VALUES (%s, %s, %s, %s)",
            (pic_name, norm_pic, country_code, office_id)
        )
        inserted_pics += 1
    except mysql.connector.errors.IntegrityError as e:
        print(f"  [SKIP pic] office_id={office_id} / {pic_name}: {e}")
conn.commit()
print(f"  ✅ 已插入 {inserted_pics} 个新 PIC")

# ── 最终统计 ──────────────────────────────────────────────────────────────────
cur.execute("SELECT COUNT(*) FROM dict_sales_office")
total_offices = cur.fetchone()[0]
cur.execute("SELECT COUNT(*) FROM sales_pic")
total_pics = cur.fetchone()[0]
cur.close()
conn.close()

print(f"\n🎉 导入完成！")
print(f"   数据库中共: {total_offices} 个 offices，{total_pics} 个 PICs")
